### ISSUE TITLE
Case A MT ending prematurely

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1001]
**Describe the bug**
Fast case A MT is ending prematurely, before mass ratio inversion. In reality, fast case A may not always end before mass ratio inversion (see Sen et al. 2023), but in COMPAS it should if the binary doesn't merge. 

If the stellar attributes are recalculated in the middle of this rapid phase, this could be affecting the outcome of the MT, potentially impacting many of our predictions.

Here's a test run I did on some data I had lying around. There should be no points below the orange line, but there are many. (I confirmed that with the latest version of `dev`, I still see some binaries populate this region, but it was a bit sparse and I didn't want to wait for a larger run to finish). 

![image](https://github.com/TeamCOMPAS/COMPAS/assets/33348824/c87c1b22-b758-4c23-8135-a4d254201215)

**Label the issue**
Please label the 'severity' and 'urgency' of this issue. You can choose:

`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**

You can run the following, e.g in a notebook, to make a similar plot

```
myf = h5.File('COMPAS_DATA_DIR/COMPAS_Output.h5', 'r')
MTs= myf['BSE_RLOF']

seeds = MTs['SEED'][()]
st1 = MTs['Stellar_Type(1)<MT'][()]
cee = MTs['CEE>MT'][()] == 1
mrg = MTs['Merger'][()] == 1
m1pre = MTs['Mass(1)<MT'][()]
m1post = MTs['Mass(1)>MT'][()]
m2pre = MTs['Mass(2)<MT'][()]
m2post = MTs['Mass(2)>MT'][()]
qpre = m2pre/m1pre
qpost = m2post/m1post

#masks
mask1stMT = np.append(np.array([True]), np.diff(seeds)>0)
maskCaseA = st1 < 2
maskNotCEE = ~cee
maskNotMerger = ~mrg
mask = mask1stMT & maskCaseA & maskNotCEE & maskNotMerger

fig, ax = plt.subplots()
x = qpre[mask]
y = qpost[mask]
ax.plot(x, y, 'o', ms=0.5)
ax.plot(ax.get_xlim(), [1, 1], lw=2, label=r'$q_{{post}}$=1')
ax.plot([0.5, 1], [0.5, 1], lw=2, label=r'$q_{{post}}=q_{{pre}}$')
ax.set_title(r'Fast Case A MT mass ration inversion $(q = M_{{2}}/M_{{1}})$')
ax.set_xlabel(r'$q$ pre-mass transfer')
ax.set_ylabel(r'$q$ post-mass transfer')
ax.legend()
#fig.show()
```

**Expected behavior**
If I understand correctly, the fast (thermal) part of Case A MT should always result in a mass ratio inversion in COMPAS. 

**Versioning (please complete the following information):**
 - COMPAS v02.39.01

**Comment by ilyamandel** [comment]
@reinhold-willcox -- we don't really distinguish between fast and slow case A any more in COMPAS.  The thing to check is what happens after the last step of MT from star 1 to star 2 (while star 1 is still on the MS).  I only spot-checked, but I think we do end up with mass ratio inversion, as you rightly expect.

**Comment by reinhold-willcox** [comment]
Huh ok, I hadn't appreciated that fast and slow case A were no longer clearly distinguished... Yes, I agree that after this first timestep the mass ratios do invert.
