### ISSUE TITLE
make fast on M1 Mac gives march error

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#1003]
**Describe the bug**
When we compile COMPAS with make fast it is supposed to use the flag -march=native . On my M1 Mac, this gave me this error:
clang: error: the clang compiler does not support '-march=native'
Some googling suggests that I can swap this out for `-mcpu=apple-m1` . 

What's the best way to modify Makefile to make this work for both cases (for now, I've just changed it locally).

**Label the issue**
Please label the 'severity' and 'urgency' of this issue. You can choose:

`urgency_low`      - This issue is not urgent

`severity_moderate` - This is a moderately severe bug

**To Reproduce**
run 
make fast
on an M1 Mac

**Expected behavior**
Code should compile, but for me throws the above error

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Mac OS v12.4 (M1 MacBook Pro)
 - COMPAS [e.g. v02.09.02]

**Additional context**

**Comment by jeffriley** [comment]
I don't see any errors with:

    Apple clang version 14.0.3 (clang-1403.0.22.14.1)
    Target: arm64-apple-darwin22.5.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Every build of `clang` for a new architecture must choose to provide defaults for "march=native" or not - I guess support for `-march-native` didn't make its way into `clang` until (at least) 14.0.3

Closing this.

**Comment by jeffriley** [comment]
Fixed by updating `clang` to at least 14.0.3
