### ISSUE TITLE
Semi-major axis < 0.0 / eccentricity > 1.0 in BaseBinaryStar::ResolveSupernova()

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#1005]
Adding the following diagnostic code to BaseBinaryStar::ResolveSupernova():

        Vector3d companionRecoilVector = Vector3d(0.0, 0.0, 0.0);                                                       // km/s - The recoil of the companion due to ablation
        double m1 = m_Supernova->Mass();                                                                                // Mo   - supernova star postSN mass
        double m2 = m_Companion->Mass();                                                                                // Mo   - companion star postSN mass
        double totalMass = m1 + m2;                                                                                     // Mo   - Total binary postSN mass

        double dm1 = (m1Prev - m1);                                                                                     // Mo   - Mass difference of supernova star
        double dm2 = (m2Prev - m2);                                                                                     // Mo   - Mass difference of companion star

        Vector3d centerOfMassVelocity = (-m2Prev * dm1 / (totalMassPrev*totalMass) + m1Prev * dm2 / (totalMassPrev * totalMass)) * relativeVelocityVectorPrev 
                                         + (m1 / totalMass) * natalKickVector 
                                         + (m2 / totalMass) * companionRecoilVector;                                    // km/s       - PostSN center of mass velocity vector

        Vector3d relativeVelocityVector = relativeVelocityVectorPrev + (natalKickVector - companionRecoilVector);       // km/s       - PostSN relative velocity vector

        Vector3d orbitalAngularMomentumVector = cross(separationVectorPrev, relativeVelocityVector);                    // km^2 s^-1  - PostSN specific orbital angular momentum vector
        double   orbitalAngularMomentum = orbitalAngularMomentumVector.mag;                                             // km^2 s^-1  - PostSN specific orbital angular momentum 
        m_OrbitalAngularMomentumVector = orbitalAngularMomentumVector/orbitalAngularMomentum;                           // set unit vector here to make printing out the inclination vector easier

        Vector3d eccentricityVector = cross(relativeVelocityVector, orbitalAngularMomentumVector) / (G_SN * totalMass) 
                                      - separationVectorPrev / separationPrev;                                          // PostSN Laplace-Runge-Lenz vector
        m_Eccentricity = eccentricityVector.mag;                                                                        // PostSN eccentricity
        double eccSquared = m_Eccentricity * m_Eccentricity;                                                            // useful function of eccentricity

        double semiMajorAxis_km = (orbitalAngularMomentum*orbitalAngularMomentum) / (G_SN * totalMass * (1 - eccSquared));  // km         - PostSN semi-major axis
        m_SemiMajorAxis = semiMajorAxis_km * KM_TO_AU;                                                                  // AU         - PostSN semi-major axis 
        if (m_SemiMajorAxis < 0.0) {
            std::cout << "m_SemiMajorAxis        = " << m_SemiMajorAxis << "\n";
            std::cout << "semiMajorAxis_km       = " << semiMajorAxis_km << "\n";
            std::cout << "m_Eccentricity         = " << m_Eccentricity << "\n";
            std::cout << "orbitalAngularMomentum = " << orbitalAngularMomentum << "\n";
            std::cout << "totalMass              = " << totalMass << "\n";
            std::exit(1);
        }

(EDIT: Diagnostics added at line 1296 of BaseBinaryStar.cpp)

Results in:

    ./compas -n 1 --random-seed 0
    
    COMPAS v02.39.01
    Compact Object Mergers: Population Astrophysics and Statistics
    by Team COMPAS (http://compas.science/index.html)
    A binary star simulator

    Start generating binaries at Tue Oct 24 09:35:45 2023

    m_SemiMajorAxis        = -0.146368
    semiMajorAxis_km       = -2.18963e+07
    m_Eccentricity         = 764.338
    orbitalAngularMomentum = 2.95595e+12
    totalMass              = 5.14885

`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
1. Run COMPAS as noted above'

**Expected behavior**
Semi-major axis >= 0.0; eccentricity <= 1.0

**Versioning (please complete the following information):**
 - OS: Ubuntu 22.04
 - COMPAS: v02.39.01

**Comment by jeffriley** [comment]
Oh wait - we set UNBOUND = true later.  Hmm.  I think there are places in the code we just blindly use m_SemiMajorAxis without checking for unbound.  Let me check that and I may come back to this...

**Comment by ilyamandel** [comment]
Don't we always check for UNBOUND at the end of the evolutionary step?  Intermediate results are allowed to be non-sensical...

**Comment by jeffriley** [comment]
We do, but I'm not convinced we don't actually use a negative semi-major axis to calculate other things, where instead we should check for unbound (or negative) and not propagate the negative.  But maybe I'll just close this and check as we make changes to the code...

**Comment by jeffriley** [comment]
Closed
