### ISSUE TITLE
Documentation of Optimistic_CE

### ISSUE THREAD

**Issue by stegmaja** [TeamCOMPAS/COMPAS#1014]
**Describe the bug**
The COMPAS variable `BaseBinaryStar::m_CEDetails.optimisticCE` is described as a

> Flag that returns TRUE if we have a Hertzsprung-gap star, and we allow it to survive the CE.

This is I think only partially true for the default assumptions. In my default runs all binaries where the flag is true actually merge and only do survive if I additionally set `--common-envelope-allow-radiative-envelope-survive TRUE`. Dropping the second part of the description would make it correct, however, I think then the name of the variable as implying an optimistic (i.e. surviving) evolution of the CE is not really applicable. I suggest keeping the description and setting the flag only to true if the merger is avoided, line 1626 ff. in BaseBinaryStar.cpp

**Label the issue**
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Run COMPAS with default assumption and count in the `BSE_Common-Envelopes` the number of systems where `Optimistic_CE` is true *and* `merger` is false. There will be none contrary to the description 

> ... *and* we allow it to survive the CE.

**Expected behavior**
Given that `Optimistic_CE` is described to be true only if the binary also survived the CE I would not expect all of `Optimistic_CE=True` systems to yield a merger too.

Cheers

Jakob Stegmann

**Comment by ilyamandel** [comment]
I think @stegmaja is absolutely right -- thank you for the report! -- but as far as the correction goes, the documentation should also be changed to refer to radiative envelope stars (which is what the --common-envelope-allow-radiative-envelope-survive flag affects, and what is done in the code), rather than Hertzsprung gap stars.

**Comment by ilyamandel** [comment]
Sorry to have taken so long, @stegmaja!
Fixed in #1108 .
