### ISSUE TITLE
Mass transfer fraction description error

### ISSUE THREAD

**Issue by lrauf** [TeamCOMPAS/COMPAS#1073]
https://compas.readthedocs.io/en/latest/pages/User%20guide/Post-processing/hdf5/WorkingWithHDF5.html#1.-Producing-HDF5-output

--mass-transfer-fa
  Mass Transfer fraction accreted in FIXED prescription (default = 0.500000, fully conservative)

Should be non-conservative for fa<1?

**Comment by jeffriley** [comment]
I was going to fix this, but I think it is a notebook generated thing... not my forte :-)

**Comment by ilyamandel** [comment]
You don't have to fix this, @jeffriley , I can -- but it's not a notebook thing.  ;-) 
Run 
./COMPAS -- help
on the command line; the output includes the following line which is, indeed, incorrect:

--mass-transfer-fa
  Mass Transfer fraction accreted in FIXED prescription (default = 0.500000, fully conservative)

**Comment by ilyamandel** [comment]
[The default value is correct; just the comment "fully conservative" should be removed.  Actually I'll fix that in a PR I'm preparing, so no need to do anything on your end.]

**Comment by jeffriley** [comment]
Oh - I see :-)  No worries - all good.

**Comment by ilyamandel** [comment]
Fixed in #1108 , closing.
