### ISSUE TITLE
Supernova being recorded twice in SSE_Supernovae output

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#1074]
**Describe the bug**
I am trying to look at a population of supernovae using COMPAS. I noticed that I was getting more supernovae than the number of (single) stars that I evolved, which seemed weird. Turns out each supernova appears twice in my output (example below).

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
MWE:
./COMPAS --mode SSE --metallicity 0.0142 --maximum-evolution-time 500 --initial-mass-min 10.0 --remnant-mass-prescription FRYER2012 --kick-magnitude-distribution MAXWELLIAN --number-of-systems 100 --logfile-type CSV --quiet

This runs a small population of single stars. Inspect COMPAS_Output_X/SSE_Supernovae.csv and see that each supernova is listed twice (same seed, same time) with some differences in other parameters. 

**Expected behavior**
Each supernova record occurs only once.

**Versioning (please complete the following information):**
 - OS: MacOS v12.4
 - COMPAS v02.42.01

**Comment by jeffriley** [comment]
l'll take a look at this one - I think I might have introduced this when I did the BSE vs SSE changes.

**Comment by ilyamandel** [comment]
Could this be related to #1084 (i.e., could we be logging a clone)?

**Comment by jeffriley** [comment]
No, this was an unintended consequence of the BSE vs SSE changes.  See PR #1092
