### ISSUE TITLE
Stroopwafel produces no hits

### ISSUE THREAD

**Issue by nsteinle** [TeamCOMPAS/COMPAS#1088]
StroopwafelInterface.py runs (after a few edits explained below) but does not find any hits and so does not perform better than usual COMPAS run at producing a population of specific DCO type. An example samples.csv output file from Stroopwafel is attached. This seems to be independent of the input parameters. 
[samples.csv](https://github.com/TeamCOMPAS/COMPAS/files/14960571/samples.csv)

Issue 'severity' and 'urgency' (but not actually sure!):
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

1. Go to StroopwafelInterface.py and use it to obtain ZAMS parameters for BNSs that merge within t_universe, but first have to edit it to fix logic errors.
2. Pass the following variables (debug, mc_only, run_on_hpc, output_filename, output_folder, userunSubmit) to the function main() to fix error.
3.  Move the function configure_code_run() to be inside of the main() function (ie b/w steps 1 and 2) to fix error.
4. Run it with the default config.yaml file.
5. Examine the csv output  - the column with 'is_hit' has all zero entries meaning no hits.
6. Convert that csv output into a Grid file and run the binaries with COMPAS to confirm that no additional BNSs are produced 

I expected stroopwafel to produce a number of ZAMS binaries that evolve into BNSs, and then I could run those binaries in COMPAS forward evolution to get a BNS population that is much larger than what a normal COMPAS run gives in the same amount of time. This would be nice to save on computational resources and time. I do not expect that the edits I made in steps 2 and 3 above will be the cause of this issue but I very well might be doing something wrong here.

Versioning:
 - OS: Ubuntu-22.04
 - COMPAS: v02.39.00

Any help would be greatly appreciated!

**Comment by FloorBroekgaarden** [comment]
Thanks Nathan, I will try to look at this today, but latest on Monday! Thanks for your clear message! 
Floor

**Comment by ilyamandel** [comment]
@FloorBroekgaarden, @nsteinle  , has this been resolved?

**Comment by nsteinle** [comment]
@ilyamandel Thanks for checking! It has not been resolved

**Comment by ilyamandel** [comment]
Dear @nsteinle ,

Stroopwafel is an add-on to COMPAS and is not a core COMPAS component.  I do not work on Stroopwafel code development myself and therefore, unfortunately, cannot help.  I understand that Floor, Stephen Justham and others are working on a new version of the code, but it is not yet ready for public release.  

At the moment, my advice would be to run COMPAS directly, without using Stroopwafel.  (This is how most of us use it, and it's fast enough for direct Monte Carlo integration to be sufficient for most use cases.) As part of PR  #1123, I will update the documentation to not mention Stroopwafel for the time being.
