### ISSUE TITLE
py_tests/test_data/fiducial-bbh-config.yaml needs to produce a BBH + CE  for pytests to pass

### ISSUE THREAD

**Issue by avivajpeyi** [TeamCOMPAS/COMPAS#1104]
@jeffriley's #1102 makes enough changes to COMPAS that the fiducial-bbh.yml no longer produces a CE. 

We need to adjust either the yaml or the grid file to create a CE event.

**Comment by ilyamandel** [comment]
Updated yaml file in #1109 .
