### ISSUE TITLE
MandelMueller prescription overwrites maximum neutron star mass option

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#1114]
**Describe the bug**
The default --maximum-neutron-star mass is 2.5 Msun. However, if you use the Mandel&Mueller prescription, it has its own hardcoded parameter MULLERMANDEL_MAXNS which is 2.0 Msun by default

This is kind of similar to https://github.com/TeamCOMPAS/COMPAS/issues/1000 where this prescription overrides some other COMPAS input option. 

Issue identified by @stellarphysicsandpopulations 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
See GiantBranch::CalculateRemnantMassByMullerMandel

**Expected behavior**
Either we should update the documentation/warn the user, or we should make this prescription use the user specified maximum neutron star mass, or something along those lines.

**Versioning (please complete the following information):**
 - OS: MacOS 12.4
 - any recent version of COMPAS e.g., COMPAS v02.44.05

**Comment by ilyamandel** [comment]
Removed MULLERMANDEL_MAXNS  in lieu of just using the choice provided by the user via --maximum-neutron-star in PR #1123 .   I agree that a single max NS choice for all prescriptions is sensible.  I'd personally prefer to set it to something we now know to be more realistic (2.2 Msun?) by default, but that's not urgent.  Closing.
