### ISSUE TITLE
Inconsistent radius values

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#1135]
When I ask a MainSequence star that's about to transfer mass (but hasn't done anything yet, just at the start of BaseBinaryStar::CalculateMassTransfer() ) what is its Radius() and compare that to the value of CalculateRadiusOnPhase() evaluated at the same time, they don't match.

[Personally, I would prefer not to store parameters like radius that can be easily recomputed at all, but compute them on the fly when needed; storing them saves computer time, but wastes programmer time when such inconsistencies arise and can lead to incorrect behaviour.]

**Comment by jeffriley** [comment]
@ilyamandel I can't duplicate this with v02.47.01 - can you check, and if you can tell me the commandline you use?

EDIT: and how you check the radius of the MainSequence star

And...

> [Personally, I would prefer not to store parameters like radius that can be easily recomputed at all, but compute them on
> the fly when needed; storing them saves computer time, but wastes programmer time when such inconsistencies arise and 
> can lead to incorrect behaviour.]

Two things.  First, the stored variable will be equal to the computed value if computed in the right place - I don't think you should necessarily expect that at random times during a timestep - and if it's not, yes, we have a problem.  Next, I'd balance your frustration (and mine when it happens to me...) against the knowledge that COMPAS runtime performance affects all users all the time, whereas ease of debug affects one programmer occasionally.

**Comment by ilyamandel** [comment]
I believe the problem was because I was using the current value of tau to compute the radius on phase, but that value was not, in fact, current.  I agree with @jeffriley's points above, so closing this issue.
