### ISSUE TITLE
--create-yaml-file default value

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1137]
**Describe the bug**
Currently, when we run `COMPAS --create-yaml-file` with no argument, we get the error `Commandline Options error: the required argument for option '--create-YAML-file' is missing`. But we provide a default yaml file in the preprocesing directory with the name `compasConfigDefault.yaml`. It would be better if this specifc name was the default if no argument is specified. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact
If there was an option for `urgency_extremely_low` I would choose that...

**Versioning (please complete the following information):**
 - COMPAS v02.48.00

**Comment by jeffriley** [comment]
The `--create-yaml-file` option has a number of use cases:

1. Create a yaml file known to contain all COMPAS options and their default values

2. Create a yaml file with specific option values set to values specified by the user (any options specified on the command line along with the `--create-yaml-file` option are written to the resultant yaml file.

Use case 1 allows users to have a local copy of a known complete yaml file with default values - which they can then use for their project, or (in the case of developers changing options), copy to the COMPAS default yaml file (`compasConfigDefault.yaml`).

Use case 2 allows users to create project-specific yaml files (of different names) that they can use as required.

Should the option have a default value for the resultant yaml file, and if so, should it be `compasConfigDefault.yaml`?  I suppose that depends on which use case we think is the most often used.  I'm not the best person to answer that - I don't use `runSubmit` and/or yaml files - so I'll leave it to someone else to decide (and implement if necessary).

**Comment by ilyamandel** [comment]
I would actually prefer not to set that option as the default, just in case we choose to rearrange our directory structure, or if the user has a different intention...  I.e., I prefer the current behaviour on this one.

**Comment by jeffriley** [comment]
I'll close this at the end of the week if there is no further comment.
