### ISSUE TITLE
Unsupported option PULSAR_BIRTH_SPIN_PERIOD_DISTRIBUTION::FIXED

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#1179]
We have the following code snippet in  NS.cpp:

        case PULSAR_BIRTH_SPIN_PERIOD_DISTRIBUTION::FIXED:                                                      // FIXED  constant value as used in default model in Oslowski et al 2011 https://arxiv.org/abs/0903.3538
            SHOW_WARN_STATIC(ERROR::UNSUPPORTED_PULSAR_BIRTH_SPIN_PERIOD_DISTRIBUTION, "Using spin = 0.0");     // show warning
            pSpin = 0.0;
            break;
            
As @jeffriley points out, it's odd to give the user the option "FIXED" here to then say it's not supported.  We should either support it or remove the option.

Ditto for PULSAR_BIRTH_MAGNETIC_FIELD_DISTRIBUTION::FIXED.

**Comment by jeffriley** [comment]
Opened PR https://github.com/TeamCOMPAS/COMPAS/pull/1194
