### ISSUE TITLE
Switch log issue

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#1182]
The switch logs are no longer working as of version 03.00.00.

I believe the problem is with object IDs.  

Adding the following print statements in BinaryStar::PrintSwitchLog() shows that the objectIdSwitching (which correctly matches the value set in Star::SwitchTo() ) is not the object ID of either the primary or secondary.  So this must have to do with changes in object ID assignments, but I have not been able to diagnose further yet.

    OBJECT_ID primaryObjectId   = m_BinaryStar->Star1()->ObjectId();
    OBJECT_ID secondaryObjectId = m_BinaryStar->Star2()->ObjectId();
    OBJECT_ID objectIdSwitching = LOGGING->ObjectIdSwitching();

    std::cout<<primaryObjectId<<std::endl;
    std::cout<<secondaryObjectId<<std::endl;
    std::cout<<objectIdSwitching<<std::endl;

**Comment by jeffriley** [comment]
@Ilya Mandel ***@***.***> can you show how to reproduce?

**Comment by jeffriley** [comment]
./COMPAS --switch-log

No switch log is created

**Comment by jeffriley** [comment]
Well that's disappointing.  I was sure I tested that, but I can't have.
Sorry, I'll take a look as soon as I can.

**Comment by jeffriley** [comment]
PR https://github.com/TeamCOMPAS/COMPAS/pull/1188 opened.

Hopefully fixed this time...
