### ISSUE TITLE
Move enhancement STROOPWAFEL from Legacy COMPAS to new COMPAS

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#12]
this is for me

**Comment by ilyamandel** [comment]
@FloorBroekgaarden , @lokiysh -- does this still need to be a separate issue?

**Comment by TeamCOMPAS** [comment]
Yes please. There is definitely some code that still needs to move, even if we focus on using STROOPWAFEL outside of COMPAS BPS code. I'm planning to work on this on the short term (i.e. within 2 months from now)

**Comment by ilyamandel** [comment]
This issue has been around for exactly one year. :)  What is the status, @lokiysh, @FloorBroekgaarden?

**Comment by ilyamandel** [comment]
Closing this issue -- as I understand, AIS sampling should work through external scripts.  If there are specific bugs/features, please add them as new issues.
