### ISSUE TITLE
Missing system in system parameters file when using range

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#1202]
**Describe the bug**
When running a grid of single stars, I noticed that the first star was missing from the system parameters output. 

I also noticed that I get an error message printed to the terminal about PO_LBV_Mass_Loss_Prscrptn, which may be related:

```
./COMPAS --mode SSE --initial-mass r[10,10,1]

COMPAS v03.01.02
Compact Object Mergers: Population Astrophysics and Statistics
by Team COMPAS (http://compas.science/index.html)
A binary star simulator

Go to https://compas.readthedocs.io/en/latest/index.html for the online documentation
Check https://compas.readthedocs.io/en/latest/pages/whats-new.html to see what's new in the latest release

Start generating stars at Tue Aug 27 14:25:58 2024

ERROR: Unable to create HDF5 dataSet PO_LBV_Mass_Loss_Prscrptn for file SSE_System_Parameters
0: Simulation completed: RandomSeed = 1724790358, Initial Mass = 10, Metallicity = 0.0142, Neutron_Star
1: Simulation completed: RandomSeed = 1724790359, Initial Mass = 11, Metallicity = 0.0142, Neutron_Star
2: Simulation completed: RandomSeed = 1724790360, Initial Mass = 12, Metallicity = 0.0142, Neutron_Star
3: Simulation completed: RandomSeed = 1724790361, Initial Mass = 13, Metallicity = 0.0142, Black_Hole
4: Simulation completed: RandomSeed = 1724790362, Initial Mass = 14, Metallicity = 0.0142, Neutron_Star
5: Simulation completed: RandomSeed = 1724790363, Initial Mass = 15, Metallicity = 0.0142, Black_Hole
6: Simulation completed: RandomSeed = 1724790364, Initial Mass = 16, Metallicity = 0.0142, Black_Hole
7: Simulation completed: RandomSeed = 1724790365, Initial Mass = 17, Metallicity = 0.0142, Neutron_Star
8: Simulation completed: RandomSeed = 1724790366, Initial Mass = 18, Metallicity = 0.0142, Neutron_Star
9: Simulation completed: RandomSeed = 1724790367, Initial Mass = 19, Metallicity = 0.0142, Neutron_Star

Generated 10 of 10 stars requested

Simulation completed

End generating stars at Tue Aug 27 14:25:58 2024

Clock time = 0.098246 CPU seconds
Wall time  = 00:00:00 (hh:mm:ss)
```

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Run something like 
./COMPAS --mode SSE --initial-mass r[10,10,1]

This runs 10 systems
and then check the output hdf5 file (using compas_h5view or otherwise) and see that only 

The same thing seems to happen with BSE as well
./COMPAS --mode BSE --initial-mass-1 r[10,10,1]

**Expected behavior**
All systems evolved appear in system parameters file, with no error message (as happens for ./COMPAS)

**Versioning (please complete the following information):**
 - OS: [e.g. MacOS 12.4 ]
 - COMPAS [e.g. v03.01.02]

**Comment by jeffriley** [comment]
Odd.  Workarounds are:

(a) use CSV files, or
(b) add option `--add-options-to-sysparms never`

Meanwhile I'll work on fixing it.

**Comment by jeffriley** [comment]
Program options added to sysparms file here because `range` is effectively a shortcut for a grid file, and the default for `--add-options-to-sysparms` is `GRID`.

Root cause of problem is duplicate column header introduced in v03.00.00 (for one of the deprecated program options) - fix was to modify the deprecated header string.

Opened PR https://github.com/TeamCOMPAS/COMPAS/pull/1204
