### ISSUE TITLE
COMPAS docker images not being created

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#1227]
COMPAS docker images not being created.  Problem seems to be new docker login procedure:

Run docker login -u *** -p ***
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://registry-[1](https://github.com/TeamCOMPAS/COMPAS/actions/runs/10988193990/job/30504211303#step:3:1).docker.io/v2/": unauthorized: your account must log in with a Personal Access Token (PAT) - learn more at docs.docker.com/go/access-tokens
Error: Process completed with exit code 1.

Fix needed in dockerhub-ci.yml ?

**Comment by avivajpeyi** [comment]
Fixed by setting up a new TeamCOMPAS docker user: https://hub.docker.com/r/teamcompas/compas
Had to change the settings (docker credentials) in the repo secrets and authorise github to write to the docker (from within the docker account).
