### ISSUE TITLE
Remove CENTRIFUGAL from documentation

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#1239]
The options CENTRIFUGAL appears in the online documentation for --mass-transfer-accretion-efficiency-prescription 
https://compas.readthedocs.io/en/latest/pages/User%20guide/Program%20options/program-options-list-defaults.html

Noticed by Pinaki Roy. 

--mass-transfer-accretion-efficiency-prescription 
Mass transfer accretion efficiency prescription. 
Options: { THERMAL, FIXED, CENTRIFUGAL } 
Default = THERMAL

It appears to have been removed from the code, and so should be removed from the documentation as well.

**Comment by ilyamandel** [comment]
Thanks for listing this issue; fixing in current PR.

**Comment by ilyamandel** [comment]
Fixed in #1240 , closing.
