### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by dumbscholar** [TeamCOMPAS/COMPAS#1254]
In main.cpp, line 315, it should be "as it is" instead of "as it"

In options.cpp, line 4833, it should be "returned" instead of "retunred"

**Comment by reinhold-willcox** [comment]
@dumbscholar nice catch! Do you know how to setup a pull request? This is a good first issue if you are interested in contributing.

**Comment by dumbscholar** [comment]
I have created one.

**Comment by ilyamandel** [comment]
Resolved in #1260 , closing.
