### ISSUE TITLE
Strange switch log output for some binaries that experience CE

### ISSUE THREAD

**Issue by todoherty** [TeamCOMPAS/COMPAS#1262]
**Describe the bug**
In discussion with Ilya we found some systems that merge in CE have unreasonable outputs in the switch log. See the below two figures.

![switch_log_output](https://github.com/user-attachments/assets/309f4a98-19f6-4cd3-b208-203ea2b2de44)
![relevant_CE_output](https://github.com/user-attachments/assets/5bf9853e-b1b1-424a-b779-64fb35448192)

The top figure shows all entries in the switch log for said SEED. The second figure shows the relevant columns from the CE output. Note the time column in both figures. In particular, the final entry in the switch log occurs after the system has merged.

**To reproduce**
Run COMPAS with the following settings in config.yaml
```
booleanChoices:
     --switch-log: True

numericalChoices:
     --number-of-systems: 1
     --random-seed: 1728964061

stringChoices:
     --eccentricity-distribution: 'GELLER+2013'

listChoices:

```

**Expected behaviour**
Final output in the switch log should not be after the system merges

**Versioning**
COMPAS: v03.05.02
OS: Ubuntu 20.04

**Comment by ilyamandel** [comment]
Thank you, @todoherty , and sorry it took a while.  This is fixed as of #1291  (03.09.03).  

Tested with

./COMPAS -n 1 --random-seed 1728964061 --eccentricity-distribution 'GELLER+2013' --switch-log --logfile-type 'CSV'
