### ISSUE TITLE
Do white dwarfs ever rise above the Chandrasekhar mass?

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#1264]
@jeffriley says they sometimes do (to be reproduced -- he will check for the right parameters?), in which case 
WhiteDwarfs::CalculateRadiusOnPhase_Static() will have a square root of a negative number.
[Also, the comparison with zero in that function should be a direct comparison, without using Compare() ]

**Comment by ilyamandel** [comment]
@jeffriley -- did you find an example?

**Comment by jeffriley** [comment]
I did not - because I didn't look.  Let me try, and if I can't find an example in the next few days I'll close the issue.

**Comment by jeffriley** [comment]
@ilyamandel with COMPAS v03.09.02 execute `./compas --random-seed 11` and you'll get `MCH_Mass_two_thirds = 0.978247`, so `sqrt(-0.021753)`, in `WhiteDwarfs::CalculateRadiusOnPhase_Static()`

**Comment by ilyamandel** [comment]
I am reproducing this with random-seed 12 rather than 11, but definitely an issue -- working on it...

**Comment by ilyamandel** [comment]
Fixed in #1298 , closing.
