### ISSUE TITLE
Misleading description of --fryer-22-fmix

### ISSUE THREAD

**Issue by dumbscholar** [TeamCOMPAS/COMPAS#1273]
Under the --fryer-22-fmix heading in the Program Option page,

In the first line, it should be "remnant mass prescription" instead of "remnant mass distribution".

In the second and third lines, it should be "model" (as referred in the Fryer+2022 paper) or "Fryer supernova engine" instead of "remnant mass prescription".

**Comment by ilyamandel** [comment]
Agree with the first change (remnant mass distribution -> remnant mass prescription).  I think the others can stay as they are  since we are comparing to the --fryer-supernova-engine remnant mass prescription described just above.
