### ISSUE TITLE
BSE_System_Parameters may contain unreasonable values for radius and luminosity

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#1307]
BSE_System_Parameters may contain unreasonable values for the radius and luminosity if such outputs are included, e.g., via

BSE_SYSPARMS_REC += {
    STAR_1_PROPERTY::RADIUS,
    STAR_2_PROPERTY::RADIUS,
    STAR_1_PROPERTY::LUMINOSITY,
    STAR_2_PROPERTY::LUMINOSITY,
    STAR_1_PROPERTY::TEMPERATURE,
    STAR_2_PROPERTY::TEMPERATURE,
}

This is presumably happening because the stars are not fully initialised at the time of the recording (the record type is 1 in the file).  However, this is confusing for the user who may reasonably expect this output to contain initial values.

Given that this is an initialisation issue, it's not clear whether a given random seed is fully reproducible -- but in a run of 10 binaries, one is certain to find some with masses of a few Msol and luminosities of <0.001 Msol.

**Comment by jeffriley** [comment]
@ilyamandel Record type 1 for BSE_System_Parameters is the default record type, and is currently the only record type.  The BSE_System_Parameters record is written only once - at the end of evolution (at the end of `BaseBinaryStar::Evolve()`).  The values printed should be the final values of the attributes.  What was the evolution status of the binary - did it stop evolution early perhaps, and leave attribute values in (what should have been) transient states?

**Comment by ilyamandel** [comment]
I had forgotten that BSE_System_Parameters specifies parameters at the end of evolution (I always use it for ZAMS values).  Thanks for the reminder; will close this.
