### ISSUE TITLE
An error in one line of a grid file stops the evolution of the rest

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1310]
**Describe the bug**
If you are running a grid file and one of the lines initializes a system with bad attributes (e.g too close) and throws an error, it stops evolving the rest of the grid. It used to be that an error was thrown and then the binary was skipped, and the older functionality is preferable. 

I've traced it back to the changes to error handling in v03.00.00, but I don't speak enough C++ to decipher all the changes that happened there, so passing it onto @jeffriley  

**Label the issue**
Please label the 'severity' and 'urgency' of this issue. You can choose:

`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
The following gridfile errors at line 6 and then stops.
```
 --initial-mass-1  4.310578135449729   --initial-mass-2  3.680782927348429    --orbital-period  30254.55716028927
 --initial-mass-1  1.937526581018889   --initial-mass-2  0.8062812603305858   --orbital-period  316.7950041674364
 --initial-mass-1  11.66619595587778   --initial-mass-2  7.1865107118533285   --orbital-period  32895.77462922232
 --initial-mass-1  1.0252660476805548  --initial-mass-2  0.182548414602229    --orbital-period  2744.1414559260324
 --initial-mass-1  0.7602165453894933  --initial-mass-2  0.5737660693698196   --orbital-period  720633838.3645189
 --initial-mass-1  0.8857655149667173  --initial-mass-2  0.09793527960238715  --orbital-period  61418.17369038843
 --initial-mass-1  5.136254185357829   --initial-mass-2  4.581266061687629    --orbital-period  39416762.1418845
 --initial-mass-1  1.6613218256434759  --initial-mass-2  0.19752246738956122  --orbital-period  101994.6609861836
 --initial-mass-1  0.8278485386513602  --initial-mass-2  0.44228408698998345  --orbital-period  440467.11201443494
 --initial-mass-1  0.7894098615547711  --initial-mass-2  0.3834616851397609   --orbital-period  3549009.302465318
```

**Expected behavior**
The problem binary should throw an error and then continue onto the next one.

**Versioning (please complete the following information):**
 - COMPAS v03.10.01 (but introduced in v03.00.00)

**Comment by jeffriley** [comment]
Ok, I'll fix this in the next couple of days.
