### ISSUE TITLE
Implement continuous integration

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#146]
We discussed at the code meeting today the benefits of having at least basic continuous integration (CI) to test pull requests. This could be as simple as checking that the code compiles and successfully runs for a simple, small test run.

**Comment by SimonStevenson** [comment]
I have started putting this together on my fork
https://github.com/SimonStevenson/COMPAS/tree/Trying-out-CI

Here is an example of COMPAS successfully building
https://github.com/SimonStevenson/COMPAS/actions/runs/72366890

Currently, this is set to run on pull/push to master/dev and my test branch (which can be removed once we have it working).

To do:
- Add linux/ubuntu build
- Test make fast as well as make
- Run additional tests

**Comment by SimonStevenson** [comment]
Updated example building on Ubuntu
https://github.com/SimonStevenson/COMPAS/runs/566811599?check_suite_focus=true

**Comment by jeffriley** [comment]
@SimonStevenson  We've implemented CI - we build a docker image whenever dev is updated.  Do we want to add more tests?

**Comment by SimonStevenson** [comment]
I don't think we have any additional automated tests at the moment, so I'm happy to close this. We should continue to think of extra automated tests we could run.

**Comment by reinhold-willcox** [comment]
Agreed on additional tests, but this is something we should discuss on a call, there will probably be a lot of nuance and caveats to hash through.
