### ISSUE TITLE
To-do items for public release

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#147]
Long test (compare to Coen’s output) — @Mike Lau 
Documentation, including description of output variables - @Jeff, @Mike Lau 
Post-processing check - @Reinhold Willcox, all
Sanity checks with non-standard inputs - @Ilya Mandel, @Debatri Chattopadhyay, @Serena Vinciguerra, all
Test/fix HPC - @Simon Stevenson, @Mike Lau 
Advertisement - @Ilya Mandel 
Websites - @Reinhold Willcox, @Ilya Mandel 
Git workflow update - @Reinhold Willcox 
Final pull from dev to master, release tag - @Reinhold Willcox 
[optional] Docker - Tim’s help

**Comment by SimonStevenson** [comment]
Did we do this? Can we close?

**Comment by ilyamandel** [comment]
Thank you for the reminder, Simon!  I think it's safe to close this one.
