### ISSUE TITLE
Test compatibility of CompasHPC and BSE_Grid.txt

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#154]
Users can specify a list of binaries to evolve using a `BSE_grid.txt` file. 

I suspect that this may not work as intended in conjunction with CompasHPC.

My concern is that if the user runs a grid file of N_lines run on HPC using N_batches, presumably the intended result is for each batch to run N_lines/N_batches (in order to speed up the run). Currently, I think you would get N_batches versions of the same run. I haven't tested this though, but unless someone else has implemented the splitting of the file, I think this will be an issue.

**Comment by TeamCOMPAS** [comment]
@SimonStevenson -- is this still a bug, or has it been resolved?  If so, please close this issue.

**Comment by SimonStevenson** [comment]
This is still a bug, I almost have a solution, will test it next week and
close with a pull request.

**Comment by SimonStevenson** [comment]
@reinhold-willcox was asking about this, so I should try to finish this off

**Comment by ilyamandel** [comment]
Any updates on this, @SimonStevenson , @reinhold-willcox ?

**Comment by ilyamandel** [comment]
Status ping?

**Comment by reinhold-willcox** [comment]
@ilyamandel Sorry - just now getting to a backlog of git notifications.

I haven't looked at this in a while, but I can if desired. Should we assign priority labels?

**Comment by jeffriley** [comment]
> Should we assign priority labels?

I thought that's what the urgency and severity labels were for.  The most severe most urgent should be the highest priority shouldn't it? Urgency should be the first sort key, and severity the next.  Are they not granular enough?

**Comment by reinhold-willcox** [comment]
> > Should we assign priority labels?
> 
> I thought that's what the urgency and severity labels were for. The most severe most urgent should be the highest priority shouldn't it? Urgency should be the first sort key, and severity the next. Are they not granular enough?

Yes, I wrote that before remembering / assigning them!

**Comment by ilyamandel** [comment]
Closing this issue since @reinhold-willcox resolved it with #359 .
