### ISSUE TITLE
Add Coen's alternative model for core mass following MS mass transfer

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#166]

**Comment by avigna** [comment]
Is this realistically going to be impemented? If so, maybe worth adding an explanation/description?

**Comment by ilyamandel** [comment]
I've assigned myself. :)

**Comment by ilyamandel** [comment]
Possibly not quite @cneijssel 's model, and took longer than I hoped (sorry, @avigna ), but this is done in https://github.com/TeamCOMPAS/COMPAS/pull/799 , so finally closing this issue. :)
