### ISSUE TITLE
Evolve after 2nd supernova

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#167]
We should make sure that all commits here http://gitlab.sr.bham.ac.uk/COMPAS/COMPAS/commits/evolve_after_2nd_SN after 10th Dec 2018 are ported over to new COMPAS. This includes some tweaks to timestepping for pulsar evolution (should check pulsar properties don't change more than few percent per timestep), and allowing the binary to contiue evolving after DCO formation.

**Comment by ilyamandel** [comment]
Any updates, @debatric ?

**Comment by debatric** [comment]
I have updated everything except allowing evolution after DCO formation. Should I do the old way of introducing a new switch to turn on or off by the user if they wish to continue evolution after DCO forms ? We used 'evolve_after_2nd_SN' tag in the python submit file for legacy. Right now, this may be only needed for pulsar-related projects.

**Comment by ilyamandel** [comment]
Why not just continue the evolution past DCO formation whenever --evolve-pulsars is on, @debatric ?

**Comment by SimonStevenson** [comment]
Sounds sensible :)

**Comment by ilyamandel** [comment]
@SimonStevenson -- so, if either binary in a DCO is an NS, and --evolve-pulsars is on, we should just continue the evolution until we hit one of the other termination conditions (time steps or total time), correct?

**Comment by SimonStevenson** [comment]
Yes (or until the binary merges due to gravitational wave emission)

**Comment by ilyamandel** [comment]
But that's not something we actually do at the moment (change the orbit in response to GW emission).  Though I agree that we should. :)

**Comment by SimonStevenson** [comment]
Right, in Debatri's code we just used the merger time (which we do calculate) as a stopping condition.

**Comment by ilyamandel** [comment]
OK, doing that in the next commit.

**Comment by ilyamandel** [comment]
Implemented in #407, closing.
