### ISSUE TITLE
double check STROOPWAFEL works in newCOMPAS 

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#18]

**Comment by ilyamandel** [comment]
@FloorBroekgaarden , @lokiysh -- does this still need to be a separate issue?

**Comment by lokiysh** [comment]
I dont think so, but since @FloorBroekgaarden created this, I will leave it upto her. Actually we might need to create a clean up ticket on the other hand.

**Comment by FloorBroekgaarden** [comment]
Yes please. There is definitely some code that still needs to move, even if we focus on using STROOPWAFEL outside of COMPAS BPS code. I'm planning to work on this on the short term (i.e. within 2 months from now)

**Comment by ilyamandel** [comment]
Closing this issue following #359 .  However, as I understand it, adaptive sampling is still not fully ready for non-expert users.  I suggest that the experts (@FloorBroekgaarden , @lokiysh , @reinhold-willcox ) set up a new Enhancement issue if that is the case.
