### ISSUE TITLE
Add Which_SN event it is in the supernova file

### ISSUE THREAD

**Issue by lokiysh** [TeamCOMPAS/COMPAS#185]
From the slack discussion ( https://compashq.slack.com/archives/CMCEQ0RS8/p1584992239352700 ), 
it is now not so easy to determine if the given record from the BSE_supernova is for the first SN event in the binary or the second ? From what I understand, Supernova_State tells us if the primary star undergoes SN or the secondary, and not the whether its the first SN event or the second. So the only way I can think of is to compare these events by the Time field, which is too much of a hassle everytime. Ideally we should add a field saying which SN event it was in the output, like it was the 1st SN or 2nd SN?

**Comment by SimonStevenson** [comment]
There is a field Supernova_State in BSE_Supernovae which is 1 if the primary star goes SN, and 2 if the secondary star goes SN. See explanation of this variable in COMPAS_Doc.pdf. This seems to do what you are asking for, so I will close the issue. If I have misunderstood, and you're actually asking for something else, please reopen with additional details.

**Comment by lokiysh** [comment]
As described above, the Supernova_State tells us if the star that went SN was primary or secondary. However, it doesnt tell us if the SN was the first SN that happened or the 2nd. The secondary star could also be the first to go SN. This discussion is also recorded in the slack link pasted originally in the issue.

This issue therefore wanted a new field "Which_SN" (or better naming) that tells if its the first SN event in the system, or the 2nd (or if both happened at the same time)

**Comment by ilyamandel** [comment]
@lokiysh -- there is a Time variable in the SN file.  You can trivially check if there is another system with the same ID in that file and compare the SN times.  So I don't think this needs to be added as an extra field -- we do not need to make the evolution code more complicated and duplicate information that can be obtained through simple post-processing.

**Comment by ilyamandel** [comment]
I haven't heard anything on this recently [no response to my last comment from 9 days ago], and as mentioned above, the information is available when parsing the SN output file.  So I am closing this issue.
