### ISSUE TITLE
USSN terminology

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#189]
Suggest changing code terminology regarding USSN to avoid future confusion about when the star is ultra-stripped (so that when it explodes in the future, it will be a USSN) vs. the supernova itself.

**Comment by avigna** [comment]
Agreed! My suggestion is for each star to have a `stripped` and `ultra-stripped` flag. And then in the case of an USSN, we can check for the `ultra-stripped` flag.

**Comment by ilyamandel** [comment]
Fixed in PR #313 , closing.
