### ISSUE TITLE
Option values incorrectly initialised?

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#196]
In Options::InitialiseMemberVariables() the following variables are initialised  thus:

    zetaMainSequence = 2.0;
    zetaHertzsprungGap = 6.5;

yet in Options::SetToFiducialValues() they are initialised thus:

    zetaMainSequence = 6.5;
    zetaHertzsprungGap = 2.0; 

I checked legacy code - they are initialised the same way.  Looks suspicious - typo?

**Comment by ilyamandel** [comment]
I believe these should be 6.5 on HG and 2 on MS.

**Comment by avigna** [comment]
Typo indeed. Fiducial options should be:
zetaMainSequence = 2.0;
zetaHertzsprungGap = 6.5;

**Comment by SimonStevenson** [comment]
Fixed in PR https://github.com/TeamCOMPAS/COMPAS/pull/205 (I hope)

**Comment by SimonStevenson** [comment]
Merged into dev
