### ISSUE TITLE
Eccentricity<2ndSN should be renamed Eccentricity<SN

### ISSUE THREAD

**Issue by lokiysh** [TeamCOMPAS/COMPAS#197]
And, the same applies to Separation<2ndSN and OrbitalVelocity<2ndSN. [Issue related to [183](https://github.com/TeamCOMPAS/COMPAS/issues/183)]

What is this?
These are the values for the respective parameters right before the SN took place.

Why should we do this?
Because the values are also correct (holds) for the 1st SN event. At this moment, for the first SN event, the header file reads them as Eccentricity<2ndSN, but the value is essentially Eccentricity<1stSN (and it is correct).

How do we know that?
For each of the SN events, we do the following, 

- we first store the currrent Eccentricity value(m_Eccentricity) to the variable m_EccentricityPre2ndSN [[link to code](https://github.com/TeamCOMPAS/COMPAS/blob/master/src/BaseBinaryStar.cpp#L1627)]
- We then update the m_Eccentricity value [[link to code](https://github.com/TeamCOMPAS/COMPAS/blob/master/src/BaseBinaryStar.cpp#L1629)]
- we finally print the SN, so the value stored in m_EccentricityPre2ndSN is printed in the column Eccentricity<2ndSN. [[link to code](https://github.com/TeamCOMPAS/COMPAS/blob/master/src/BaseBinaryStar.cpp#L1672)]

So this is correct, however, this also hold for 1st SN event. Then why do we call the variable m_EccentricityPre2ndSN, and not m_EccentricityPre1stSN? Hence, Ideally we should call it just m_EccentricityPreSN and the header name as Eccentricity<SN.

**Comment by SimonStevenson** [comment]
I have put together a pull request here https://github.com/TeamCOMPAS/COMPAS/pull/204 which should address this.

**Comment by SimonStevenson** [comment]
Merged into dev
