### ISSUE TITLE
COMPAS random seed changes with time, documentation says it is fixed

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#199]
./COMPAS --help claims
--random-seed arg (=0)                                        Random seed to use (default = 0)

However running ./COMPAS a couple of times in succession will show you that the 10 random binaries are not identical, but change each time. @jeffriley says this is because he is using the system time as the default seed for the gsl random number generator.

There are 2 possible solutions:
1) Change the documentation to accurately reflect what is happening in the code
2) Change the code to use the same default random seed as the help message says

I slightly prefer option 2, as it allows easy comparison between runs, but this can easily be achieved with 
./COMPAS --random-seed 0 
so it doesn't really matter that much.

**Comment by manodeep** [comment]
In case this is helpful, a good source of random bits is through the file-like interface of `/dev/urandom`. Simply reading in the requisite number of bytes from `/dev/urandom` with `fread` is the recommended (for non-cryptographic uses) method of "randomly" seeding RNGs. The `/dev/urandom` device is available on all Unix-like operating systems (https://en.wikipedia.org/wiki//dev/random). I will note that any such run will only be reproducible if the seed is logged for posterity.

**Comment by ilyamandel** [comment]
Two sub-issues here:
1. The default choice should be to have a fixed random seed.
2. When something other than a fixed random seed is used, the random seed in runDetails should record the actual random seed that was used.

**Comment by ilyamandel** [comment]
Actually, @SimonStevenson , do we really want the default choice to use a fixed random seed?  E.g., if you don't specify a seed explicitly when running pythonSubmit, do you want the seed of 0 to always be used?  If not, then perhaps the current behaviour is sensible, and we should just update the documentation.

**Comment by ilyamandel** [comment]
[The documentation *is* correct in that the default random seed is zero if the user specifies that a fixed random seed should be used; but the default is also not to use a fixed random seed -- and if the seed is chosen randomly, it will, of course, over-write the choice of the default random seed.]

**Comment by ilyamandel** [comment]
As described above, the documentation is correct in this case.  There is a related issue, #239 , to record the chosen random seed.  But here the behaviour matches expectation, so I am closing this issue.
