### ISSUE TITLE
calculate_gamma differs between COMPAS legacy and Hurley SSE

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#20]
Coen reports:

"I am for weird reasons trying to code up some tracks in python, and by accident fuond a statement in the SSE that we do not have in COMPAS sse code.
Function calculate_gamma() in Star.cpp. SSE in fortran has an additional check (translated to COMPAS legacy language)
if(Mass > an_coefficients[81-1]+0.1){
    gamma = 0.0

original fortran snipped
if(m.gt.(a(88)+0.1d0))then
         rgammf = 0.d0
where you have to subtract 7 from the index to recover paper coefficient
Not sure if @Simon Stevenson recalls any specific on this.
Nor how important it is
Maybe this relates to a radius problem we had with calculating gamma errors of the past and possibly stripping of low mass stars.
Partially related to this issue from the past (http://gitlab.sr.bham.ac.uk/COMPAS/COMPAS/issues/12) but that is more about tides.

It furthermore has an absolute statement in the SSE code.
         if(m.le.m1)then
            rgammf = a(83) + a(84)*ABS(m-a(85))**a(86)
which COMPAS legacy does not have
Summary: I accidentally found slight differences in the calculate_gamma functions between COMPAS legacy
and SSE hurley code. It seems to cover the calculation of radii for low mass stars, and therefore could possibly be responsible for very old bugs we had.

The if statements are in the text above equation (23) in the hurley 2000 paper, and it appears there are more differences between the fortran code and equation(23)

**Comment by jeffriley** [comment]
@cneijssel Any update on this?  Is this something we need to address, or do we just need to understand it?

**Comment by ilyamandel** [comment]
I can look at this during today's code hack time.

**Comment by ilyamandel** [comment]
As far as I can tell, we have correctly implemented Hurley's eq. (23) in MainSequence::CalculateGamma().  

I am therefore closing this issue.  If there are specific instances of unreasonable behaviour that we encounter, we should raise a separate issue.
