### ISSUE TITLE
Initialise variables

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#200]
Initialise the following variables where they are declared as noted below.  They are all actually initialised where they need to be, but the compiler throws a warning with the new makefile - this is just to suppress the compiler warning.

1. addAssign to false in Log::UpdateAllLogfileRecordSpecs()

2. massAfterMassLoss to 0.0 in BaseBinaryStar::CalculateAdaptiveRocheLobeOverFlow() and in BaseBinaryStar::CalculateMassTransferFastPhaseCaseA()

3. radiusAfterMassLossto 0.0 in BaseBinaryStar::CalculateAdaptiveRocheLobeOverFlow() and in BaseBinaryStar::CalculateMassTransferFastPhaseCaseA()

4. lineNo in EvolveSingleStars() and in EvolveBinaryStars() in main.cpp

**Comment by ilyamandel** [comment]
@jeffriley -- I think you already addressed this because I don't see any compiler warnings, right?

**Comment by jeffriley** [comment]
No, not that I recall.  It only happens with the new makefile which you may not be using

**Comment by SimonStevenson** [comment]
I think maybe it's compiler dependent? (Because I also don't see any)

**Comment by jeffriley** [comment]
I surrender.  I don't see any errors anymore...  Closing this - I'll re-open it if they ever resurface.
