### ISSUE TITLE
Rand::Random(const double p_Lower, const double p_Upper) returns values greater than expected when p_Lower > 0

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#201]
Rand::Random(const double p_Lower, const double p_Upper) returns values greater than expected when p_Lower > 0. 
 The return statement in Rand::Random(const double p_Lower, const double p_Upper) needs to change from

    return (gsl_rng_uniform(m_Rng) + lower) * (upper - lower);

to

    return (gsl_rng_uniform(m_Rng) * (upper - lower)) + lower;

**Comment by SimonStevenson** [comment]
I confirm this is indeed an issue, and the correct solution

**Comment by SimonStevenson** [comment]
@jeffriley Similarly, in 
Rand::RandomInt(const int p_Lower, const int p_Upper)
should
`gsl_rng_uniform_int(m_Rng, upper) + lower;`
which would generate an integer in the range [lower, upper+lower)
be
`gsl_rng_uniform_int(m_Rng, (upper-lower)) + lower;`
which would generate an integer in the range [lower, upper]

Do we ever actually use this function?

**Comment by jeffriley** [comment]
Fix for Rand::RandomInt(const int p_Lower, const int p_Upper) is to return:

    return gsl_rng_uniform_int(m_Rng, (upper - lower)) + lower;

No, not used currently (so no harm done with that one) - there in case anyone wants it.
