### ISSUE TITLE
Links to test runs

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#211]
Don't close this issue.  It is here to record links to output files for test runs.

Put each new test run in a new comment.  Leave details so people can identify what's at the link.

**Comment by jeffriley** [comment]
Test run of 1080000 binaries at Z=0.0142 using pythonSubmitDefault and COMPAS v02.09.06.

h5 file is available at:

[ https://drive.google.com/file/d/1G19qpcqYJRmu4jDs8oxHHVgS-0lB_YK7/view?usp=sharing](url)
[Run_Details.txt](https://github.com/TeamCOMPAS/COMPAS/files/4447352/Run_Details.txt)


Run_Details file attached - ignore random-seed and number-of-binaries - this was run in 36 batches of 30000 binaries and combined after the run.

**Comment by jeffriley** [comment]
Test run of 1,000,008 binaries using pythonSubmitDefault and COMPAS v02.13.01

2 runs: 1 at  Z = 0.0142, one at Z = 0.00142, h5 files and tarballs with raw (.csv) logfiles available at:

https://drive.google.com/drive/folders/1Yl68wr8YF7cSdrAdtdAhPfI3NTLnYX8J?usp=sharing

Run_details for one of the batches attached - ignore random-seed and number-of-binaries - this was run in multiple batches.  Note that this is a Run_Details file a batch from the Z = 0.0142 run.  Substitute Z = 0.00142 for the other run.

[Run_Details.txt](https://github.com/TeamCOMPAS/COMPAS/files/5040732/Run_Details.txt)

**Comment by reinhold-willcox** [comment]
@jeffriley we should set up a CI scheme to run 1mil binaries every time we update dev, and create the appropriate link. Not sure how to do that, but it saves you having to run it yourself each time.

**Comment by jeffriley** [comment]
The problem we have at the moment is that we don't have a backend system to run 1M binaries on each update to dev.  I'm not sure whether our compile and docker build is done on a github server or whether Tim does it on his server for us - he was talking about the latter.

We might be able to provision an AWS instance through CI and do it that way - better (imo) to have our own server somewhere.  I'll talk to Tim and see what he recommends.

**Comment by jeffriley** [comment]
Test run of 3,000,000 binaries using COMPAS v02.11.01a (v02.11.01 plus fix for issue #260).  

https://drive.google.com/file/d/1Sv5UhPxdQvOIMhbWvpLFp6zXu0ZigqPE/view?usp=sharing

CHE was not enabled for this test.

Attached is the Run_Details file which shows the parameter setting used
[Run_Details.txt](https://github.com/TeamCOMPAS/COMPAS/files/5134588/Run_Details.txt)

A grid file was used that specified:

. initial masses for both stars
. separation
. eccentricity
. metallicity of both stars

so those values should be ignored in the Run_Details file (the Run_Details file reflects the program options supplied either directly on the commandline or indirectly via a pythonSubmit file).

For the parameters specified in the grid file were constructed as follows:

. for the initial masses, the KROUPA distribution was used, with  primary min = 5.0 Msol, max = 150.0 Msol, secondary min = 0.1 Msol
. for separation, the FLATINLOG distribution was used, with min = 0.01 AU and max = 1000.0 AU
. eccentricity was 0.0 for all binaries
. 30 different metallicities were assigned, evenly spread over the range 10^(-4) to 10^(-1.825) (the metallicity was the same for each star)

**Comment by jeffriley** [comment]
Test run of 3,000,000 binaries using COMPAS v02.11.01a (v02.11.01 plus fix for issue #260).

https://drive.google.com/file/d/1gqEpV8B_JSQ30K1_aNb4B23csdgQEpfc/view?usp=sharing

CHE PESSIMISTIC was enabled for this test.

Attached is a sample Run_Details file which shows the parameter setting used (the run was done across a number of AWS instances and the outputs consolidated later, so ignore the number of binaries in the Run_Details file - as well as the parameters specified in the grid file - see below).

[Run_Details.txt](https://github.com/TeamCOMPAS/COMPAS/files/5134642/Run_Details.txt)

A grid file was used that specified:

. initial masses for both stars
. separation
. eccentricity
. metallicity of both stars

so those values should be ignored in the Run_Details file (the Run_Details file reflects the program options supplied either directly on the commandline or indirectly via a pythonSubmit file).

For the parameters specified in the grid file were constructed as follows:

. for the initial masses, the KROUPA distribution was used, with primary min = 5.0 Msol, max = 150.0 Msol, secondary min = 3.0 Msol
. for separation, the FLATINLOG distribution was used, with min = 0.01 AU and max = 1000.0 AU
. eccentricity was 0.0 for all binaries
. 30 different metallicities were assigned, evenly spread over the range 10^(-4) to 10^(-1.825) (the metallicity was the same for each star)

**Comment by jeffriley** [comment]
Test run: v02.17.13, 100,000 binaries with metallicity sampled over range [0.0001, 0.03]

https://drive.google.com/file/d/1_0SCNbLUVnNvWEtSBvCaLkWiDxh6wsoW/view?usp=sharing

[Run_Details.txt](https://github.com/TeamCOMPAS/COMPAS/files/5698964/Run_Details.txt)

**Comment by reinhold-willcox** [comment]
@jeffriley Are you still using this? It would be useful (IMO) to have a 10M run of the latest version with default values ready to download, but perhaps it's easier to just run it independently.

**Comment by jeffriley** [comment]
I don't use these files anymore - they were put there as reference file for anybody to use.  If they're not useful then I'm happy for them to be removed - and new ones made.
