### ISSUE TITLE
RLOF and MT Output

### ISSUE THREAD

**Issue by themikelau** [TeamCOMPAS/COMPAS#212]
We should re-implement RLOF output (as in LegacyCOMPAS, but perhaps with improvements). More detailed discussion about how to implement this can occur below.

**Comment by ilyamandel** [comment]
Now that we are bringing RLOF printing back (thanks, @themikelau ! ), there’s an important question about how we should deal with mass transfer from envelope-less donors (e.g., MS stars) that can happen over many timesteps.  Here are a couple of thoughts, but I am eager to hear other ideas:

1. The simplest option is to record an entry in the RLOF file whenever there is a mass transfer happening during that time step.  It’s simple, it provides all the necessary information, and it leaves for the user to figure out how to handle it.  The downside is that the RLOF tracker files will get quite large (and the execution will be slowed down by all the extra I/O). 

2. Another option is to provide an entry in the RLOF file on the first and last time step of mass transfer (two identical entries for MT that only took one timestep).  Here, first and last are defined as bracketing a sequential set of timesteps during each of which at least one star is in RLOF, with neither star being in RLOF before the first and after the last step.  Note that this will hide some information (e.g., mass transfer rates may change between time steps, and even which star is the donor and which is the accretor may potentially change).  But it will produce more modest outputs and cost less I/O time.

We could do something else — but anything else is likely to require more complex logic that will be appropriate for one project but not another.  A possibility is to have an extra user-provided flag for the kind of RLOF printing the user wants.  E.g., we could implement at least option 1 (and maybe 2, if I have time :slightly_smiling_face: ) now, and leave open the possibility to define a different style of output by a user who finds that the above options are insufficient.

What do people think?

**Comment by ilyamandel** [comment]
P.S. I decided to go with option 1 for now, in the interests of time, and because the number of output lines is not excessive (at most around 50 lines per case A MT, and an average of 5 lines per binary in the RLOF file, with the current time step cadence).

**Comment by ilyamandel** [comment]
Resolved with PR #349 , closing this issue.
