### ISSUE TITLE
Initial conditions: Mind your p's and q's

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#213]
Include the option of sampling from the correlated initial distribution in mass, mass ratio, separation and binarity proposed by Moe and Di Stefano rather than our current uncorrelated initial condition distribution.

**Comment by SimonStevenson** [comment]
I agree. I think this will be much easier using the grid infrastructure. I think this would be a good thing to have in the python pre-processing scripts to generate initial conditions which we are hoping to put together (see issue #71).

**Comment by ilyamandel** [comment]
Assigning to @Thillai96 -- but we agreed this is best handled through a grid file, outside the C++ code.

**Comment by ilyamandel** [comment]
Implemented in #798 , to be closed once that's pulled.
