### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#214]
There doesn't seem to be a link anywhere to dev-git-workflow.md any more -- unless one knows to look for it in docs, it's quite a challenge to find.  I think we should add a small section "For developers" to the main README.md file, with a single sentence including a link to this document.

**Comment by SimonStevenson** [comment]
Duplicate of #207

**Comment by ilyamandel** [comment]
So it is -- sorry, didn't spot #207 , closing this one.
