### ISSUE TITLE
When are options required in pythonSubmit?

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#217]
AttributeError: 'pythonProgramOptions' object has no attribute 'kick_velocity_sigma_CCSN_NS'

I removed this option from pythonSubmit for a run which is using a kick prescription that does not use this parameter.   I think it's already not used for some of our existing kick options.  Presumably, the options that are needed only for specific prescriptions should only be required if those prescriptions are being used.

**Comment by ilyamandel** [comment]
Ditto for, e.g., 'fryer_supernova_engine' [raises an error even if the FRYER prescription is not being used].  Note this is a pythonSubmit issue, not a core COMPAS code issue.

**Comment by jeffriley** [comment]
@ilyamandel When you removed these options from pythonSubmit, did you just remove the declaration of the variables, or the entries in the Choices/Commands lists?

For example, in the case of 'kick_velocity_sigma_CCSN_NS', as well as removing the declaration:

    kick_velocity_sigma_CCSN_NS = 265.0

you also need to remove the associated entries from numericalChoices:

    self.kick_velocity_sigma_CCSN_NS,

and numericalCommands:

    '--kick-velocity-sigma-CCSN-NS',

If I do that I don't see any errors - the run completes ok.

**Comment by ilyamandel** [comment]
No, I have not tried removing it from those lists.  I can confirm that removing them solves the problem.  I like your second option better -- but it doesn't seem to always work.  E.g., when I change 

fryer_supernova_engine = None

I get

$ python3 pythonSubmitMullerMandel.py 
python_version = 3
Traceback (most recent call last):
  File "pythonSubmitMullerMandel.py", line 716, in <module>
    runCompas(programOptions)
  File "pythonSubmitMullerMandel.py", line 700, in runCompas
    commands = specifyCommandLineOptions(programOptions)
  File "pythonSubmitMullerMandel.py", line 521, in specifyCommandLineOptions
    command = [generateCommandLineOptions(programOptions.compas_executable,booleanChoices,booleanCommands,numericalChoices,numericalCommands,stringChoices,stringCommands,listChoices,listCommands)]
  File "pythonSubmitMullerMandel.py", line 533, in generateCommandLineOptions
    assert len(numericalCommands) == nNumerical
AssertionError

**Comment by jeffriley** [comment]
I should have mentioned to use "False" instead of "None" for booleans.  

In the case of fryer_supernova_engine, this works for me:

    fryer_supernova_engine = None

The error you are getting sounds like you may have deleted an option from the numericalChoices, but not from numericalCommands (or vice versa).  Maybe start with a clean pythonSubmit file.

**Comment by ilyamandel** [comment]
I stupidly forgot that fryer_supernova_engine was a stringChoice, not a numericalChoice, so all is well.  

Good to know for the future that None and False are valid options, thank you!
