### ISSUE TITLE
Possible issue with LBV winds

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#223]
There may be an issue with LBV implementation: there does no appear to be a flattening of the remnant masses due to LBV winds at high ZAMS masses that is described, e.g., in the appendix to Neijssel+, 2019.  

Running single stellar evolution, COMPAS v02.09.08

Relevant settings:
metallicity = 0.0142 
    mass_loss_prescription = 'VINK'
    luminous_blue_variable_multiplier = 1.5
    wolf_rayet_multiplier = 1.0

Plot attached.

![noLBV](https://user-images.githubusercontent.com/512213/79039447-abba4680-7c24-11ea-89f9-89befc2edfd7.png)

**Comment by SimonStevenson** [comment]
Indeed I see Type 4 (CHeB) stars not losing any mass at all.
(example attached generated with same default input as Ilya above)
[SSE_Parameters_90.txt](https://github.com/TeamCOMPAS/COMPAS/files/4479220/SSE_Parameters_90.txt)

**Comment by SimonStevenson** [comment]
![mass_v_timestep](https://user-images.githubusercontent.com/6952112/79301221-5afc6380-7f2c-11ea-9de5-f0e3baa9cec8.png)

**Comment by SimonStevenson** [comment]
The orange dashed is the CHeB, so it seems mass loss completely switches off towards the end of the HG

**Comment by SimonStevenson** [comment]
This seems to be because m_LBVfactor = 0 despite the fact that in the pythonSubmit luminous_blue_variable_multiplier = 1.5

possibly because this seems to be set in ./BaseBinaryStar.cpp:    m_LBVfactor       = OPTIONS->LuminousBlueVariableFactor(); rather than in BaseStar

The same also seems to be true for the WR factor. (edited) 

So I think that we need to pull them out and make them be part of BaseStar rather than BaseBinaryStar . As far as I can tell, this means this issue will only affect single stars, and binaries should be doing the correct thing.

**Comment by SimonStevenson** [comment]
Or at least make sure the pythonSubmit values of  luminous_blue_variable_multiplier and wolf_rayet_multiplier get passed to the Star constructor when using single stars

**Comment by jeffriley** [comment]
I believe the LBV factor and WR factor are passed as parameters to the BasStar() constructor...

**Comment by jeffriley** [comment]
At least they are for BSE...  It seems they are not passed for SSE so both default to 0.0.  So yes, probably need to pick up the option values in main() and pass them there

**Comment by SimonStevenson** [comment]
Yeah sorry, that's what I meant :)

**Comment by ilyamandel** [comment]
@jeffriley -- I am confused. :) 

Main.cpp creates a new single Star with 
new Star(randomSeed, gV.mass, gV.metallicity);  
[line 374]

and a new BinaryStar with 
                    binary = new BinaryStar(ais,
                                            gV.mass1, gV.mass2, gV.metallicity1, gV.metallicity2, gV.separation, gV.eccentricity,
                                            gV.star1KickParameters,
                                            gV.star2KickParameters,
                                            index);
[line 1068]

Neither seems to be getting the WR and LBV parameters passed in, right?  In fact, the constructor for Star at least has them as optional inputs, though they are set to zero by default in Star.h, but the constructor for BinaryStar does not...

**Comment by jeffriley** [comment]
Look for this in BaseBinaryStar.cpp:

        // binary star contains two instances of star to hold masses, radii and luminosities.
        // star 1 initially more massive
        m_Star1 = new BinaryConstituentStar(m_RandomSeed, mass1, metallicity1, {}, m_LBVfactor, m_WolfRayetFactor);
        m_Star2 = new BinaryConstituentStar(m_RandomSeed, mass2, metallicity2, {}, m_LBVfactor, m_WolfRayetFactor);

**Comment by ilyamandel** [comment]
That was nicely hidden. :-)  OK, we should make an exact parallel for single stars.

**Comment by jeffriley** [comment]
Yeah, I think we should clean it up and make it consistent.

**Comment by ilyamandel** [comment]
Testing Jeff's branch, winds appear fixed, continuing to test.

![LBVwindfix](https://user-images.githubusercontent.com/512213/79524140-13e4ae80-80a3-11ea-8caf-9d701090d69a.png)

**Comment by ilyamandel** [comment]
Spot checking against wide binaries evolved with our BSE implementation indicates good agreement, so we Jeff's fix works:

![LBVwidebinaries](https://user-images.githubusercontent.com/512213/79526961-c91a6500-80a9-11ea-89d4-041a573df3d6.png)

**Comment by ilyamandel** [comment]
Fixed in PR 235, closing.
