### ISSUE TITLE
Profiling and object creation

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#227]
I find it astounding that we can sometimes create several hundred thousand objects to evolve an individual binary.  This is probably not good for computational cost. :)  Profiling would help...

**Comment by jeffriley** [comment]
@ilyamandel didn't you say you would lead the profiling effort?

**Comment by ilyamandel** [comment]
You have already done the heavy lifting by writing the profiler -- thank you, @jeffriley !

**Comment by ilyamandel** [comment]
@jeffriley -- interesting that in single stellar evolution, we call BaseStar::DrawSNKickVelocity a total of 13 times for the same star that goes SN.  Just an indication that we probably have a fair bit of repetitive execution. :)

**Comment by jeffriley** [comment]
I am certain of it.  I thought I reduced as much as I could (or at least as much as I had time for without in-depth profiling) when I refactored, but there are still plenty of avenues for improvement.

**Comment by ilyamandel** [comment]
Closing the issue, since it's too non-specific and partially addressed with the latest code changes (though, of course, further optimisation is possible).
