### ISSUE TITLE
Runaway flag -- does not seem to have a consistent meaning

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#228]
The Runaway flag (RUNAWAY_CP in BSE_Supernovae.csv) does not seem to have a consistent meaning.  It appears to be set to 1 if star 1 explodes in a SN that unbinds the binary, but to 0 if star 2 explodes in a SN that unbinds the binary.  [Not sure whether this is strictly necessary since we already have an unbound flag -- but if we use it, it should be symmetric.]

**Comment by reinhold-willcox** [comment]
I thought runaway was supposed to refer only to non-compact object companion stars.

**Comment by ilyamandel** [comment]
@reinhold-willcox: sure, my point is that this flag is not set consistently -- it appears to depend on which star exploded in a SN, not on the stellar type of the companion.  @jeffriley -- seed 13 from the test file you ran for me is an example.

**Comment by jeffriley** [comment]
@ilyamandel Seed 13 from the test file I gave you has:

Stellar_Type_SN = 13 (NS)
Supernova_State = 2 (Secondary went SN)
Stellar_Type_Prev_SN = 8 (HeHG)
Stellar_Type_Prev_CP = 11 (COWD)
Unbound = 1 (TRUE)
Runaway_CP = 0 (FALSE - Companion star not runaway)

Runaway_CP is only set if the binary is unbound and if the companion is, as @reinhold-willcox mentioned, not a compact object.  Should it not be 0 (FALSE) for seed 13, or is the criteria described in the previous sentence not correct (or am I misreading/misunderstanding something - always a good possibility)?

**Comment by ilyamandel** [comment]
@jeffriley , @reinhold-willcox -- apologies to both of you, I misread the definition of RUNAWAY in the documentation.  I agree that the behaviour is consistent.  Closing this issue.
