### ISSUE TITLE
Incorrect circularisation formula used in BaseBinaryStar constructors

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#233]
The circularisation formala used in both BaseBinaryStar constructors is incorrect in that it does not take mass change into account.

The formula currently used is

    m_SemiMajorAxis *= (1.0 - (m_Eccentricity * m_Eccentricity));

It should be as used in BaseBinaryStar::InitialiseMassTransfer()

    double M = m_Star1->Mass() + m_Star2->Mass();
    double m1m2 = m_Star1->Mass() * m_Star2->Mass();
    m_SemiMajorAxisPrime *= 16.0 * m1m2 * m1m2 / (M * M * M * M) * (1.0 - (m_Eccentricity * m_Eccentricity));

**Comment by jeffriley** [comment]
Corrected calculations in both BaseBinaryStar constructors

**Comment by ilyamandel** [comment]
Addressed in PR #249 .
