### ISSUE TITLE
2nd supernova not printed in disrupted systems

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#236]
In systems which are disrupted in the first supernova, the second supernova is not printed. The evolve_unbound_systems flag is True (and these systems all exist in the DCOs output) so these disrupted systems are being evolved, but the second supernova specifically is not included in the output.

**To Reproduce**
pythonSubmit with evolve_unbound_systems = True, and number_of_binaries = 1000 (to compare with intact DCO systems). All of the seeds in the Double_Compact_Objects should exist twice in Supernovae, but there are many that do not. To see all of the ones repeated twice, run the following bash command in your COMPAS_Output:
`tail -n+4 BSE_Supernovae.csv | awk '{print $2}' | uniq -d`
(You can verify that these are the systems which either disrupt at the 2nd SN or survive both). But the list is only 14 systems long, while DCOs is 131. 

**Expected behavior**
There should be the same number of repeated systems in Supernovae as in Double_Compact_Objects.

**Versioning (please complete the following information):**
 - OS: Ubuntu 18.04
 - COMPAS v02.10.03

**Comment by jeffriley** [comment]
Do we know if this was a problem in the legacy code?  If it also didn't print in legacy then I don't need to go and look for a defect - the functionality doesn't exist.  If it did print in legacy then I must have lost the functionality in the refactor.  I ask because I didn't think we thought evolving unbound systems worked properly in legacy - maybe this was one of the things that didn't work.

**Comment by reinhold-willcox** [comment]
I'm not sure about legacy, but I'm fairly certain that previous versions of new Compas printed the supernovae correctly.

**Comment by jeffriley** [comment]
Oh?  So we broke working functionality?  I don't suppose you can figure out what version broke the functionality?

**Comment by reinhold-willcox** [comment]
I'll take a look, might be a while though.

**Comment by reinhold-willcox** [comment]
Going back to v1.0.0, the behavior is different, but still very weird. 

With evolve_unbound=True, and nBinaries=1000, I find that if a binary is disrupted at the first supernova, it only prints the second supernova if the first supernova resulted in a BH, not a NS. Turning on evolvePulsars does not affect this. 

To summarize between versions w/ tag `beta` and `v1.0.0`: 
- DCOs works properly always. First SN is always printed, and if the First SN leaves the binary intact, the 2nd SN is always printed.
- In `beta`, if the first SN is disruptive, the 2nd SN will not print.
- In `v1.0.0`, systems disrupted at first SN print 2nd SN only if SN1 -> BH. 

So my hunch is that we never properly printed the 2nd SN, but I didn't look closely enough in the past to find this weird defect.

**Comment by ilyamandel** [comment]
@reinhold-willcox -- can this one be closed now following your latest PR?

**Comment by ilyamandel** [comment]
Reopening temporarily since we rolled back PR #336 .

**Comment by reinhold-willcox** [comment]
@ilyamandel I think this problem was solved by the move from two supernova calls to one (which changed the evolution of some systems because it changed when the SN was called). 

So I'll leave this out of the nskicks PR, but I think this counts as a valid bug that will need to be changed in the future, with the expectation that some systems will evolve differently.

**Comment by ilyamandel** [comment]
Turns out there were a lot more systems that we weren't printing in the SN output file than just the ones unbound by the first SN. :)

**Comment by ilyamandel** [comment]
Fixed with PR #404.

**Comment by reinhold-willcox** [comment]
@ilyamandel which other systems did you notice?

**Comment by ilyamandel** [comment]
I think there were some issues with printing systems that went through the second EvaluateSupernovae() call.  That's no longer an issue because printing is now handled in the same way for both EvaluateSupernovae() calls.
