### ISSUE TITLE
SSE code samples kicks (since v02.10.01) - add kicks to SSE grid file

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#238]
**Is your feature request related to a problem? Please describe.**

No.  @ilyamandel moved the sampling of kicks into the SSE code path so that SSE would sample kicks - previously kicks were only sampled in the BSE code path.  The SSE grid file does not allow kick values to be supplied (c.f. the BSE grid file).

**Describe the solution you'd like**

Add ability for users to supply kick values via the SSE grid file

**Describe alternatives you've considered**

None (other than no action).

**Additional context**

**Comment by jeffriley** [comment]
Added kick functionality to SSE Grid file.  Updated docs.

**Comment by SimonStevenson** [comment]
The associated pull request has now been merged, so closing this issue
