### ISSUE TITLE
Add actual random seed used to Run_Details file

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#239]
**Is your feature request related to a problem? Please describe.**

No.  The Run_Details file records option values applied, so records any value the user supplied for --random-seed, however, if COMPAS is run without using a pythonSubmit file, the random seed is determined based on the time-of-day, and is not shown in the Run_Details file (though it is recorded in all of the output files).

**Describe the solution you'd like**

Record the actual random seed used in the Run_Details file.

**Describe alternatives you've considered**

None (other than no action).

**Additional context**

**Comment by jeffriley** [comment]
Added actual random seed to Run_Details file.

Note that COMPAS will check the environment variable GSL_RNG_SEED is fixedRandomSeed = false (i.e. the user did not supply a random seed via the command line options) and if GSL_RNG_SEED is set COMPAS will use that value as the default random seed.  If GSL_RNG_SEED is not set then COMPAS will use the system time to generate a random seed.

So if the user does:

export GSL_RNG_SEED 0 

immediately prior to running COMPAS and does not supply a random seed via --random-seed, then COMPAS will read the environment variable and use 0 as the random seed rather than generate a random seed using the system time.

(Reading the environment variable is existing functionality)

**Comment by ilyamandel** [comment]
Resolved in PR #247
