### ISSUE TITLE
COMPAS complains if --single-star-mass-max <= --single-star-mass-min even when --single-star-mass-steps = 1

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#246]
**Describe the bug**
COMPAS complains if --single-star-mass-max <= --single-star-mass-min even when --single-star-mass-steps = 1, which doesn't make a lot of sense - if the user just wants to evolve 1 star then we should just use one of the values (I suggest --single-star-mass-min) and ignore the other

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
run COMPAS as follows:

./COMPAS --single-star --single-star-mass-steps 1 --single-star-mass-min 10 --single-star-mass-max 10

**Expected behavior**
use --single-star-mass-min and ignore --single-star-mass-max if --single-star-mass-steps = 1

**Versioning (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - COMPAS [e.g. v02.10.04]

**Comment by jeffriley** [comment]
Changed Options.cpp to ignore --single-star-mass-max if --single-star-mass-steps = 1 (main.cpp already does this)

**Comment by ilyamandel** [comment]
Resolved in PR #247.
