### ISSUE TITLE
Convert COMPAS docs to latex for easier version control

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#252]
**Is your feature request related to a problem? Please describe.**
The COMPAS docs are currently in docx format, which github treats as a binary format. This makes version control difficult (can't easily see changes, doesn't deal with conflicts nicely etc).

**Describe the solution you'd like**
We should convert the docs document into a file format that is easier to version control. I suggest latex. 

**Describe alternatives you've considered**
Could keep as a docx file, but has issues described above.

**Additional context**
This issue was noticed in issue #237

**Comment by jeffriley** [comment]
@SimonStevenson I've pushed the LaTex documentation to dev - ok if we close this?  (I just realised that the 'X' should be upper case - I guess my memory is not so good.  Maybe one day we should rename the directory in the repo...)

**Comment by SimonStevenson** [comment]
Sure thanks for doing this. Closed.
