### ISSUE TITLE
Remove ID from output files

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#254]
**Is your feature request related to a problem? Please describe.**
The ID column in the output files seems to be redundant and/or misleading. It uniquely identifies binaries only on a given core, so IDs are repeated when using multi-core compas. The Seeds already provide the functionality of uniquely identifying systems (as well as providing random seeds).

**Describe the solution you'd like**
My understanding is that IDs are useful for internal COMPAS calculations, so we should not get rid of them completely, but just not include them in the output files. 

**Describe alternatives you've considered**
I don't actually know where IDs are used internally - if they are not, we could scrap them.

**Comment by jeffriley** [comment]
Good idea to remove ID from output file.  The ID is a debugging tool (Seed does not offer sufficient granularity to differentiate between objects).  The ID can always be added via the Output_definitions file if debugging.  ID should not be removed from the code.

Unassigned myself - anybody can remove ID from the default logfile specifications in constants.h

**Comment by ilyamandel** [comment]
@reinhold-willcox addressed this in PR #328 , closing.
