### ISSUE TITLE
Update meaning of SN_STATE

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#255]
**Is your feature request related to a problem? Please describe.**
Currently, the SN_STATE parameter (in the code and output) is initialized to 0 (for no SNs), set to 1 after star1 supernovas, set to 2 after star2 supernovas, or set to 3 if both are simultaneous. In the output, there is no way to tell which system went first by looking at a single line of output (one would need to look at the times of both systems, or e.g the stellar types). 

**Describe the solution you'd like**
This is the optimal place to describe how many SNe happened and the order they occurred in. These features have been requested as other columns, but I believe that fix is not necessary. This parameter is already an integer, so I propose we expand it's possible values and their meanings. Below I've created a dictionary of useful values -> meanings. Please let me know if you think there should be changes.

| Integer Value | Meaning |
|-----|-----|
| 10 | Star 1 went SN, second has not occured |
| 20 | Star 2 went SN, second has not occured |
| 12 | Star 1 went SN first, Star 2 second |
| 21 | Star 2 went SN first, Star 2 second |
| 3  | Both stars went SN simultaneously |

The value of this is that, given 2 SNe lines in Supernovae.csv for a given system, it is immediately clear in each individual line which Star went SN in the current line and whether there was a previous SN. 

**Describe alternatives you've considered**
A new column could be created with information on whether there was a previous SN, but that requires more overhead and makes searching for this information slightly more cumbersome.

**Additional context**
Related to Issue #183

**Comment by reinhold-willcox** [comment]
@jeffriley tagging you to double check that this won't screw up any other dependencies in the code

**Comment by jeffriley** [comment]
> @jeffriley tagging you to double check that this won't screw up any other dependencies in the code

There are a few place is the code that SN_STATE is checked and some action taken based on the value of SN_STATE - you just need to account for the changes in those places.

**Comment by ilyamandel** [comment]
Reopening temporarily since we rolled back PR #336 .

**Comment by reinhold-willcox** [comment]
Closing. The same information can be garnered by considering the companion stellar type, so this parameter would be redundant.
