### ISSUE TITLE
Allow user to easily vary assumed mass transfer efficiency

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#259]
**Is your feature request related to a problem? Please describe.**

  --mass-transfer-accretion-efficiency-prescription arg (=THERMAL)
                                                                Mass Transfer Accretion Efficiency prescription (options:
                                                                THERMAL, FIXED, CENTRIFUGAL), default = ISOTROPIC)

(note a small bug, it says default = ISOTROPIC, which I think is a copy-paste error from   --mass-transfer-angular-momentum-loss-prescription arg (=ISOTROPIC). It should say default = THERMAL

By default, COMPAS uses the THERMAL prescription. An option is to use the FIXED prescription, where the user fixes the value of beta. However, there is currently no easy way to specify the value you wish to fix it to.

**Describe the solution you'd like**
 I think we should add an extra command line option to allow for this functionality.

**Describe alternatives you've considered**
How did you deal with this @serenavinciguerra89 ? I guess the easy work around would be to edit the constants file and recompile.  

**Additional context**
Noticed when considering using for NSBH project

**Comment by ilyamandel** [comment]
@SimonStevenson -- I fixed the bug in the help output, to appear in latest commit, will look at your other point in a moment.

**Comment by ilyamandel** [comment]
The existence of CENTRIFUGAL was a lie -- it was not properly implemented and is now removed.

**Comment by ilyamandel** [comment]
Actually, fixed MT was mostly implemented -- the input you want to set is  mass_transfer_fa = 0.5 -- it just wasn't quite correctly implemented. :)

**Comment by ilyamandel** [comment]
OK, should be fully implemented in PR #312 , closing now.
