### ISSUE TITLE
misnamed m_OrbitalVelocity

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#261]
**Describe the bug**
Some of the variables and functions with names which include *OrbitalVelocity* actually refer to OrbitalAngularVelocity. These include: m_OrbitalVelocity,m_OrbitalVelocityPrev, m_OrbitalVelocityPrime, OrbitalVelocity(). However, m_OrbitalVelocityPreSN and OrbitalVelocityPreSN() are set and used independently, and are implemented correctly.

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
N/A - it's just names of variables, does not affect results.

**Expected behavior**
These should be renamed to OrbitalAngularVelocity. 

**Screenshots**
N/A

**Versioning (please complete the following information):**
 - COMPAS v02.11.00

**Comment by avigna** [comment]
This should be closed once the NSKicks pull request is approved, right?

**Comment by reinhold-willcox** [comment]
I haven't actually added this into the PR, I can do that now.

**Comment by reinhold-willcox** [comment]
Created a new branch in `origin` with a PR into `reinhold-fork:ns_kicks`, but because ns_kicks is in a different repo, I can't link the issue. It's mentioned though (see above)

**Comment by ilyamandel** [comment]
@reinhold-willcox addressed this in PR #328  , closing.
