### ISSUE TITLE
Add variable of maximum separation during life as a bound binary

### ISSUE THREAD

**Issue by avigna** [TeamCOMPAS/COMPAS#265]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I want to add two variables that keep track of the maximum separation and maximum size of L2 of a binary through it's history. Add it to printed quantities (not sure which file).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ilyamandel** [comment]
@avigna -- if you are going to do this, please make tracking such a variable optional (with default of not tracking) -- we do not want to track extra internal states unnecessarily.

**Comment by ilyamandel** [comment]
@avigna -- should this still be an open issue?

**Comment by avigna** [comment]
I still think it is relevant and useful for, e.g., determining stability of triples/quadruples, but haven't developed it. If there is some urgency to close this issue, go ahead, and I will re-open if/when needed.

**Comment by jeffriley** [comment]
> if you are going to do this, please make tracking such a variable optional (with default of not tracking)
> -- we do not want to track extra internal states unnecessarily.

This could be done by checking (at the start of the run) whether the variables are in list of variable to be output to the log files - so no need to add an extra option.

**Comment by ilyamandel** [comment]
Closing since nobody objected to the wontfix status.

**Comment by avigna** [comment]
(Still think this could be useful, but we can re-open once/if someone actually works on it)
