### ISSUE TITLE
Resolve supernovae sequentially

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#271]
When two supernovae happen simultaneously, the instantaneous mass loss is unrealistically too large.  In practice, we do not expect the evolution of two stellar companions to be so similar that supernovae ever happen within an orbital period of each other.  

We should instead always resolve two supernovae sequentially, adjusting the orbital parameters in between and picking a random location along the eccentric orbit for the second SN if appropriate.

**Comment by reinhold-willcox** [comment]
@ilyamandel I'm wondering about the best way to approach this. A potentially simple way to do this is to evaluate the SNe in the same timestep but update the orbital parameters in between the two and randomly sample in the anomaly. But more generally, the problem arises when two stars have exactly equal mass, which is also unrealistic. 

Is it worth it to add in a check for precisely equal mass stars, and if true, to perturb one slightly? The benefit to varying the mass is that the SNe will naturally happen in different timesteps, which is more realistic and would make the detailed plots clearer.

If equal masses only come from initial conditions, we could demand that q is strictly < 1. But maybe @jeffriley can remind me if there's a condition anywhere that sets the two masses equal (e.g for contact, non-merging binaries).

**Comment by jeffriley** [comment]
> @jeffriley can remind me if there's a condition anywhere that sets the two masses equal

We equilibrate the masses of the constituent stars (and circularise the orbit of the binary) in the following circumstances:

(a) At birth, if OPTIONS->AllowRLOFAtBirth() is TRUE and either of the constituent stars is overflowing its Roche lobe.  

If after equilibrating and circularising either of the stars is overflowing its Roche lobe:

If OPTIONS->AllowTouchingAtBirth() is FALSE we declare a merger and discard the binary.  
If OPTIONS->AllowTouchingAtBirth() is TRUE we allow the binary to survive, but it will merge at the first timestep (so will be in the results).

(b) During evolution (in BaseBinaryStar::InitialiseMassTransfer()), if CHE is enabled and both stars are CHE, and either of the stars is overflowing its Roche lobe (and masses are not already equal).


> Is it worth it to add in a check for precisely equal mass stars, and if true, to perturb one slightly?

From a programming perspective, special cases are often a code smell (there are, of course, cases that are indeed special).  I think it is probably true that realistically stars won't equilibrate exactly to a mass ratio of precisely 1, but for the same reason that won't happen is there a case for putting the perturbation of a star's mass at the time of mass calculation?  What I mean is, don't just perturb if the masses of the stars in a binary are equal, but perturb the mass of all stars whenever their mass is calculated (or adjusted for mass loss/transfer)? The perturbation amount/factor would be a global - could be a function of mass (and maybe other) attributes of the star. That way you don't have to pick one of the stars in a binary to perturb when the masses are equal, and maybe it is actually more realistic than assuming the equations we use to calculate/adjust mass are precise (our prescriptions are presumably just fits to a series of points that aren't all on the line anyway).  Just a thought.

**Comment by reinhold-willcox** [comment]
@jeffriley thanks for clarifying. I'm on board, happy to hear arguments from others though.

**Comment by ilyamandel** [comment]
@reinhold-willcox , @jeffriley -- this is a very nice suggestion.  I rather like keeping the masses equal as a simple indicator that they went through mass sharing.  So I would vote for just resolving the two SNe sequentially in this case (say, always start with mass1).  This also matches my general intuition that we should avoid doing too many things during one time step.

**Comment by ilyamandel** [comment]
Should be addressed by PR #373.
