### ISSUE TITLE
Inconsistent He core mass values

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#277]
The He core mass value appears to be greater than the overall core mass or even the total mass in some cases.

I was checking the BSE_Supernovae.csv file.  First, the things which do make sense:
- the total pre SN mass, Mass_Total@CO_SN,  is always greater than or equal to the core pre SN mass, Mass_Core@CO_SN
- the core pre SN mass, Mass_Core@CO_SN, is always greater than or equal to the CO core pre SN mass, Mass_CO_Core@CO_SN

Now, the things which do not make sense:
- the pre SN He core mass, Mass_He_Core@CO_SN, sometimes exceeds the total pre SN core mass, Mass_Core@CO_SN.  In fact, the pre SN He core mass sometimes exceeds the total pre SN mass, Mass_Total@CO_SN!  This is particularly true for ultra-stripped SN leading to NS formation: for these, the total pre-SN mass always equals the pre-SN CO core mass, indicating ultra-stripping, yet the He core mass is 1 to 3 solar masses larger than these.
- the remnant mass, Mass_SN, is sometimes larger than the total pre SN mass, Mass_Total@CO_SN.  

The last bullet point may be at least partly tied to the penultimate one, because I use the He core mass in GiantBranch::CalculateRemnantMassByMullerMandel() to calculate the remnant mass.  We need to make sure all internal mass variables are self-consistent. 

This bug has a potentially significant impact on remnant mass and kick calculations, at least for the Mandel & Mueller prescription.

COMPAS v02.11.03

**Comment by reinhold-willcox** [comment]
To add, Jeff and I looked into this and (P)PISN are also dependent on the HeCore mass.

**Comment by ilyamandel** [comment]
This issue is fixed through PR #313 , closing.
