### ISSUE TITLE
Change default units for output effective temperature to Kelvin (and not solar temperature )

### ISSUE THREAD

**Issue by demink** [TeamCOMPAS/COMPAS#278]
My suggestion is to change the default unit for outputting  effective temperatures  in Kelvin: Teff (K) or possibly log10(Teff/K) following standard conventions in stellar astrophysics.   It currently is given in units of `Tsol`.  This is highly unconventional and will likely introduce confusion. 
 
**Example**: `Teff_1` and `Teff_2` that are written to `COMPAS_Output/Detailed_Output/BSE_Detailed_Output_X.csv`

**Context**: Using solar units is indeed common practice for Luminosity, Radius and Mass, probably mostly because standard units require very large numbers of 1e30 kg etc. . This is not the case for the (effective) temperature. Most stellar astronomers know reasonable temperature ranges by heart in units of T(k) or log_10 T (K).

**Comment by ilyamandel** [comment]
Fixed while I was in the middle of doing something else, will include in next PR.

**Comment by ilyamandel** [comment]
Fixed in PR #297 .  Closing issue.  Thank you for raising it, @demink !
