### ISSUE TITLE
USSNe (and some ECSNe) have a He shell at the moment of explosion

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#289]
Ultra-stripped supernovae (type 16) leading to NS formation should be stripped down to the CO core by the time the SN happens.  However, the He shell has a median mass of >1.3 solar masses according to the BSE_Supernovae output file (Mass_He_Core@CO_SN-Mass_CO_Core@CO_SN, the latter is equal to Mass_Core@CO_SN, as expected).  

ECSNe (type 2) generally do not have a He shell, as expected, but a small fraction do, up to ~0.86 solar masses. 

From a run of a million binaries with the Mandel-Mueller prescription, v. 2.12.0.

![Heshell](https://user-images.githubusercontent.com/512213/86526811-e78b4200-bedb-11ea-91de-a5051cdffdf2.png)

**Comment by avigna** [comment]
1) What does "type 16" means or comes from? New stellar type?
2) How do you determine if the star you report has been ultra-stripped?

**Comment by jeffriley** [comment]
In this context, "type 16" is the SN event type - look for "enum class
SN_EVENT" and the preceding explanation in constants.h

**Comment by ilyamandel** [comment]
Fixed for USSN by PR #313 .  ECSNe may happen in stars with He envelopes, so not necessarily a problem.  (Should return to ECSNe elsewhere, but not in this issue).  Closing.
