### ISSUE TITLE
Post-February bug-fix legacy: Pass correct core mass for zeta calculation

### ISSUE THREAD

**Issue by cneijssel** [TeamCOMPAS/COMPAS#29]
Git commit in Legacy: Gitlab   Commit 36afabce
File     BinaryStar.cpp
Function MassTransfer()  at the time from line 2885
Note: this does not address the issue with infinity values

The incorrect core mass was passed for determining zetaAdiabatic.
Some stars need to have the helium core and others need the general core,
which could be the Co-Core. This is not the cleanest solution, since at the time
we did not correctly update the helium-core masses at every time step.
The reason was that we could still recover the initial helium core mass parameter
despite it no longer being applicable (i.e. convoluted method of tracking).

In short we need better track of what is the real core mass, 
for the condensed polytrope (a core in a convective shell)
As afar as I understand
MS<07 | MS   =No core exists
HG - CHeB    = only a HeCoreMass exists coreMass = HeCoreMass
EAGB - TPAGB = have both a HeCoreMass and a COcoremass. 
               The coreMass relates to the up to date value of the HeCore.
               Except for TPAGB when the HeCore is depleted and 
               COCore + dredge up have taken over. 
               Indeed not nicest behaviour in naming.
HeMS         = Is an exposed HeCore, no COcore exists
HeHG |HeGB   = EAGB equivalent of HeMS now there is a 
               COcore and coreMass = COCore

To force stability for HeMS stars we put the core same as 
the total mass (in our old way it the core=HeCore)
This forces an infinite solution and might not be the best fudge

The if statement

if((stellarTypeDonor >= HERTZSPRUNG_GAP and stellarTypeDonor <= NAKED_HELIUM_STAR_MS) 
        or stellarTypeDonor == NAKED_HELIUM_STAR_GIANT_BRANCH 
        or stellarTypeDonor == NAKED_HELIUM_STAR_HETZSPRUNG_GAP){

        //added the following  to input which core we want
        //dummy value for coreMass:
        double coreMass;
        //Decision to make HeMS star zeta for soberman infinite (always stable)
        if(stellarTypeDonor ==NAKED_HELIUM_STAR_MS){

            coreMass = mdHeCore;

            }

        else{

            coreMass = mdCore;

            }

        //for these if statements we then pass coreMass, instead of mdHeCore
        else if(options.commonEnvelopeZetaPrescription == ZETA_SOBERMAN){
                    zetaAdiabatic = ZadiabaticSPH(md, coreMass);
                    zetaThermal   = 0.0;
					zetaCompare = zetaAdiabatic;
                }
                else if(options.commonEnvelopeZetaPrescription == ZETA_HURLEY){
                    zetaAdiabatic = ZadiabaticHurley2002(md, coreMass);
                    zetaThermal   = zetaAdiabatic;
                }

**Comment by ilyamandel** [comment]
@cneijssel -- is there any evidence that this bug exists in the new COMPAS?  If not, we should close this issue.

**Comment by ilyamandel** [comment]
In the absence of any evidence that this bug exists in the new COMPAS code, I am closing this issue.
