### ISSUE TITLE
Logs.txt Wall Time formatting

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#293]
**Describe the bug**
In the output log_N.txt files, the last line is `Wall time = XX:XX:XX (hh:mm:ss)`. If either the minutes or seconds is < 10, then it is not printed with a leading 0. For example,

`Wall time = 0:2:3`, for 2min,3sec. It should be `Wall time = 0:02:03`

**Label the issue**

`urgency_low`      - This issue is not urgent

`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
Any run should produce a log_N.txt file, but I was using ozstar for this.

**Versioning (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - COMPAS [e.g. v02.13.00]

**Comment by ilyamandel** [comment]
Fixed in PR #405 , closing.
