### ISSUE TITLE
Binaries experiencing post-unbound interactions

### ISSUE THREAD

**Issue by avigna** [TeamCOMPAS/COMPAS#295]
**Describe the bug**
When activating the `evolve_unbound_systems = False` flag, I noticed that some systems entering the CEE function had negative separations. My guess is that a check for RLOF in the form `is R_star>R_RL' keeps happening and will be true if semi-major axis < 0. Regardless, there were unbound systems engaging getting all over the CEE funtion.

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
1. Set `evolve_unbound_systems = True` in the pythonSubmit.
2. Suggestion: Add a print statement at the beginning of the CEE function (this is how I found the bug, but there are many ways to do it). Alternatively, play with a very wide binary and see if it happens after the first supernova.
3. If you followed the suggestion, run _N_ number of different binaries until you see a negative number.

**Expected behavior**
Unbound systems shouldn't interact with their companions. The only thing they should experience is a supernova (I think).

**Screenshots**
NA

**Versioning (please complete the following information):**
 - OS: MacOS Catalina
 - COMPAS v02.12.00

**Additional context**
NA

**Comment by ilyamandel** [comment]
Fixed in PR #301 , closing.
