### ISSUE TITLE
Post-February bug-fix legacy: Use correct value of Envelope mass

### ISSUE THREAD

**Issue by cneijssel** [TeamCOMPAS/COMPAS#30]
Git issue Legacy: Commit     0524773a
File       BinaryStar.cpp
Function   MassTransfer() around line 2790 back in the day

ain point, we had two envelope masses that we used, 1=mdEnv
which is set in the star.cpp, 2=EnvelopeD which we calculate in massTransfer() itself.
When calculating the different thermalRates some functions used mdEnv others EnvelopeD
and after some debugging I spotted slight numerical differences which should have been the same.
Therefore I realised mdEnv is not the same as EnvelopeD, hence I switched to have all equations
use EnvelopeD instead. This is the most updated value and then self-consistent.

The statement that was changed and here shown correct (apologies for the long logic statement)

// ALEJANDRO - 19/01/2017 - Quick fix for re-defining thermal rate for a star with clear core-envelope separation. This should be re-written at the begginng of the function.
		if(stellarTypeDonor == HERTZSPRUNG_GAP or stellarTypeDonor == FIRST_GIANT_BRANCH or stellarTypeDonor == CORE_HELIUM_BURNING or stellarTypeDonor == EARLY_ASYMPTOTIC_GIANT_BRANCH or stellarTypeDonor == THERMALLY_PULSING_ASYMPTOTIC_GIANT_BRANCH or stellarTypeDonor ==NAKED_HELIUM_STAR_HETZSPRUNG_GAP or stellarTypeDonor == NAKED_HELIUM_STAR_GIANT_BRANCH){
			thermalRateDonor    	= envelopeD/tauThermalDonor;
		}
		
		if(stellarTypeAccretor == HERTZSPRUNG_GAP or stellarTypeAccretor == FIRST_GIANT_BRANCH or stellarTypeAccretor == CORE_HELIUM_BURNING or stellarTypeAccretor == EARLY_ASYMPTOTIC_GIANT_BRANCH or stellarTypeAccretor == THERMALLY_PULSING_ASYMPTOTIC_GIANT_BRANCH or stellarTypeAccretor ==NAKED_HELIUM_STAR_HETZSPRUNG_GAP or stellarTypeAccretor == NAKED_HELIUM_STAR_GIANT_BRANCH){
			thermalRateAccretor 	= envelopeA/tauThermalAccretor;
		}

where envelopeD and envelopeA previously and incorrectly were mdEnv, maEnv

**Comment by SimonStevenson** [comment]
If this is already in new COMPAS, can we close this issue?

**Comment by ilyamandel** [comment]
@cneijssel -- is there any evidence that this bug exists in the new COMPAS?  If not, we should close this issue.

**Comment by ilyamandel** [comment]
In the absence of any evidence that this bug exists in the new COMPAS code, I am closing this issue.
