### ISSUE TITLE
Fryer fallback-reduced kicks are not really Fryer fallback

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#311]
As far as I can tell, our fallback-reduced kicks do not quite match Fryer.  Fryer says in section 4.5:
“Additionally, compact objects formed with small amounts of fall back (Mfb<Mfb,small) receive full kicks (this includes some low mass BHs).”
In his case, Mfb,small is set to 0.2 solar masses; that means that typical NSs formed from progenitors with a CO core mass <2.5 M_\odot get the full kicks.  Not so in COMPAS, where even such objects have reduced kicks, because they have a non-zero fallback fraction.  [Note that BaseStar::ApplyBlackHoleKicks() is misnamed, since it’s applied to both NSs and BHs.]  
Is this an intentional feature or a bug?  

@SimonStevenson , @avigna -- I am assigning this to you not because I need help fixing it (I can do so), but because I want your input on whether this is a bug or an intentional feature.

**Comment by ilyamandel** [comment]
@avigna , @SimonStevenson -- would be great to get your thoughts on my question above.

**Comment by avigna** [comment]
From what you describe, it seems that COMPAS doesn't exactly follows Fryer. Not sure if it was actually intended or not when coded, but I am happy with the way it works (i.e. kick always using the fallback factor). 

If you want to be precise/thorough, maybe worth fixing and adding a feature where it is neglected; then allow the user to specify.

In practice, I prefer the way it is currently working. My 2 cents.

**Comment by SimonStevenson** [comment]
Yeah so I don't know if this was intended or not (I'd guess not given that the Mfb,small parameter doesn't exist in COMPAS). I suggest we add this parameter. We can decide if we want to set the default/fiducial value to 0 (to match previous COMPAS results) or to 0.2 (to match Fryer+ 2012), I can see arguments for both.

**Comment by ilyamandel** [comment]
Well, if everyone is happy using the slightly modified version of Fryer, let's just explain the modification in the methods paper and be done with it -- why add code that nobody will use?

**Comment by ilyamandel** [comment]
OK, so it seems that there is no use case for now for changing the current behaviour, and we'll document it in the methods paper -- so I am closing this issue.
