### ISSUE TITLE
ResolveSupernova() can leave higher remnant masses than initial pre-SN masses for SSE

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#315]
At the end of GiantBranch::ResolveSupernova(), m_Mass can be larger than m_SupernovaDetails.totalMassAtCOFormation, despite the latest code fixes.  This leads to nonsensical negative ejecta masses being passed along.  This only seems to be an issue for SSE, not BSE.

**Comment by ilyamandel** [comment]
(Note to self: confirmed this is not an issue for BSE, so need to understand why/where SSE and BSE paths diverge.)

**Comment by jeffriley** [comment]
Do you have a pythonSubmit file and seed to duplicate?

**Comment by ilyamandel** [comment]
Add the following at line 1733 of GiantBranch.cpp and run with the attached pythonSubmit file.

        if(m_Mass>m_SupernovaDetails.totalMassAtCOFormation){
            std::cout<<"SNERROR: "<< m_Mass<<" "<<m_SupernovaDetails.totalMassAtCOFormation<<std::endl;
        }

[pythonSubmitMandelMuller.py.txt](https://github.com/TeamCOMPAS/COMPAS/files/5047141/pythonSubmitMandelMuller.py.txt)

**Comment by ilyamandel** [comment]
[I suspect there's just one extra step of evolution happening -- the remnant mass grows between the start and end of ResolveSupernova; if so, it may be easy enough to fix, but I want to actually use this as an excuse to better align SSE and BSE rather than putting a patch on SSE.]

**Comment by jeffriley** [comment]
@ilyamandel I have not done anything with this yet, but @reinhold-willcox is making changes to SN handling - his nskicks branch makes some fairly significant changes to the BSE SN code flow (I don't remember is it touches the SSE code flow) - so you and he might want to discuss before you embark on your cleanup.

**Comment by reinhold-willcox** [comment]
My PR doesn't touch the Giantbranch::ResolveSupernova function, just the BaseBinaryStar::ResolveSupernova.

That said, if Ilya is correct that some mass quantity is changing mid-timestep, then the changes I'm proposing to the structure of a full timestep would fix that. I haven't coded these up though, I'm still in the early stages of that.

**Comment by ilyamandel** [comment]
Fixed in PR #322 , closing.
