### ISSUE TITLE
Enhancement: Make USSN independent of accretor

### ISSUE THREAD

**Issue by cneijssel** [TeamCOMPAS/COMPAS#32]
File BinaryStar.cpp
Function massTransfer() around line 3099 in my Legacy version

SSE/Binary feature

Add in possibility to have USSN be independent of accretor type.
Instead if a HeHG star is stripped and leaves a COcore which go supernova
it should be classified as USSN regardless of the accretor.

In Legacy it looked like this if statement that we set the flag and dependency of USSN

// ALEJANDRO - 24/08/2017 - Check for case BB or BC mass transfer; particularly for BNS project
				if(stellarTypeDonor == NAKED_HELIUM_STAR_HETZSPRUNG_GAP or 
                    stellarTypeDonor == NAKED_HELIUM_STAR_GIANT_BRANCH){
//						
//						if(stellarTypeAccretor == NEUTRON_STAR or stellarTypeAccretor == BLACK_HOLE){
					if(stellarTypeAccretor == NEUTRON_STAR){
						if(primaryDonor){
							star1.flagUSSN = true;
						}
						else{
							star2.flagUSSN = true;
						}
					}

**Comment by jeffriley** [comment]
@ilyamandel Did you do anything to affect this issue when you fixed USSN in new COMPAS?

**Comment by ilyamandel** [comment]
Not yet, but I have a plan for how to do this.  Will have to wait until I'm done with commenting on your paper, though, @jeffriley . :-)

**Comment by ilyamandel** [comment]
Resolved in PR #329 , closing this issue.
