### ISSUE TITLE
Remove variable m_SecondaryTooSmallForDCO from BaseBinaryStar class

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#337]
**Describe the bug**
@avigna removed the 'only-double-compact-objects' program option in and associated code in v02.08.00.  The BaseBinaryStar class variable m_SecondaryTooSmallForDCO is not used now that the option no longer exists, and should be removed.

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
Code inspection

**Expected behavior**
The BaseBinaryStar class variable m_SecondaryTooSmallForDCO and associated code (declaration, initialisation, getter) should be removed.

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Ubuntu 18.04
 - COMPAS v02.1313

**Additional context**

**Comment by ilyamandel** [comment]
Included in #407 , closing.
