### ISSUE TITLE
Remove PopulationDataPrinting program option

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#338]
**Describe the bug**
The PopulationDataPrinting program option seems to be superfluous - does anybody actually use it?  I don't see a good reason to keep it - it may have served a purpose once but I think it has been superseded by newer functionality.

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
Code inspection

**Expected behavior**
Remove the PopulationDataPrinting program option and associated code (a few print statements)

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Ubuntu 18.04
 - COMPAS v02.13.13

**Additional context**

**Comment by ilyamandel** [comment]
I use this, and since it's easy to turn this off in the pythonSubmitFile, @jeffriley agreed to allow me to continue using it -- so no need to remove the code, closing this issue. :)
