### ISSUE TITLE
Remove RLOF_ONTO_NS and RECYCLED_NS from SN_EVENT enum

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#351]
**Is your feature request related to a problem? Please describe.**
The SN_EVENT enum is an enumerated type that provides a limited set of type names for events related to supernovae.  The events RLOF_ONTO_NS and RECYCLED_NS crept into the SN_EVENT enum during refactoring of the code, but should not be grouped with supernovae events.

**Describe the solution you'd like**
The RLOF_ONTO_NS and RECYCLED_NS evenst, currently defined in the SN_EVENTS enum, should be moved to a separate miscellaneous events/flags enum.

**Describe alternatives you've considered**
We could just store RLOF_ONTO_NS and RECYCLED_NS as individual boolean variables.  For now, I think we should create a "FLAGS" enum that lets us record and report miscellaneous flags as a single entity (an output file can then have a "FLAGS" column that lists all flags as a single bitmap).

**Additional context**

**Comment by ilyamandel** [comment]
Thank you for the fix, @jeffriley !  Closing.
