### ISSUE TITLE
Add record type to BSE detailed output file

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#353]
**Is your feature request related to a problem? Please describe.**

Records written to the BSE detailed output file are, or should be, written to the file as close as possible to the end of the timestep so that the data contained in the record represents the binary in a self-consistent state.  This precludes writing intra-timestep records to the file than might contain interesting data (temporarily for a specific study, for example, so taking advantage of existing infrastructure rather than issuing ad hoc prints to std::cout, or permanently for intra-timestep values that might generally be useful).

**Describe the solution you'd like**

Add a "record type" output variable that identifies the type of record being written to the file - record types could be:

     "end-of-timestep", or "self-consistent", or some other indication that the binary is in a self-consistent state.
     "intra-timestep", or perhaps a user-defined string to label the record and indicate the binary is not guaranteed to be self-consistent.

Post-processing scripts could allow filtering by record type in the detailed output file - and if the user wants intra-timestep type records they would be aware that they are do not necessarily represent the binary in a self-consistent state.

We could add a program option to include/exclude intra-timestep records, with the default to exclude them (so default behaviour is unchanged, and including intra-timestep records requires a deliberate request).

We could apply the concept of record type to any file, not just the detailed output file.

**Describe alternatives you've considered**

**Additional context**

**Comment by reinhold-willcox** [comment]
I don't think we should be including outputs with the warning that they might be inconsistent. If they are (potentially) inconsistent, we probably should not be printing them. That just causes confusion. 

I advocate only printing at the end of a timestep, when we can be sure that everything is consistent again.

**Comment by jeffriley** [comment]
But you don't have to print the intra-timestep records if you don't want them - and if you want them you probably know they are not consistent.  The benefit is that it allows users flexibility - they can print intra-timestep values of variables to see what they are.

As long as it is disabled by default, and users have to turn it on (so presumably know that by doing that the values they get for those record types may not be for a binary in a self-consistent state - but the intra-timestep values are useful to whatever it is they are studying), I don't see a downside.

**Comment by jeffriley** [comment]
Revisit this another time
