### ISSUE TITLE
Implement a '--detailedOutput' program option for SSE_Parameters files

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#361]
**Is your feature request related to a problem? Please describe.**

The SSE_Parameters file is the SSE equivalent of the BSE_Detailed_Output file.  Prior to the implementation of the SSE Supernova file in v02.15.00, the SSE_Parameters files (1 for each star evolved) were the only artefacts of an SSE run, and it didn't make sense then to have the ability to disable/enable the output of the SSE_Parameters files.  Now though, the SSE_Supernova file will always be created, and the SSE_Switch_Log files is also an option.

**Describe the solution you'd like**

I propose we implement a program option analogous to the '--detailedOutput' program option for BSE_Detailed_Output files.  We would probably need to rename the current '--detailedOutput' option to '--BSEdetailedOutput', and implement a new '--SSEdetailedOutput' option.  Both would be FALSE by default.

I also propose we rename the SSE_Parameters file to 'SSE_Detailed_Output' to make it consistent with BSE.

**Describe alternatives you've considered**
Status quo.

**Additional context**

**Comment by jeffriley** [comment]
Actually, rather than over-think and over-complicate it, I'll just overload the current 'detailedOutput' option to do both - whichever mode is being run (SSE or BSE), the 'detailedOutput' option will mean enable the detailed output.

**Comment by ilyamandel** [comment]
Sounds like the right solution, @jeffriley !

**Comment by SimonStevenson** [comment]
Agreed

**Comment by jeffriley** [comment]
This was implemented in v02.16.00
