### ISSUE TITLE
Make column headers consistent for MZAMS and RZAMS

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#362]
**Is your feature request related to a problem? Please describe.**

The column header string for the stellar property MZAMS is 'Mass@ZAMS'.  Originally the header string for the stellar property RZAMS was 'Radius@ZAMS', but at some stage it was changed to 'R@ZAMS'.

**Describe the solution you'd like**

I propose we make the header strings for these quantities consistent.  My preference would be 'Mass@ZAMS' and 'Radius@ZAMS', but 'M@ZAMS' and 'R@ZAMS' work too.

**Describe alternatives you've considered**

There are any number of possible header strings...

**Additional context**

**Comment by reinhold-willcox** [comment]
I concur, and also prefer Mass@ZAMS and Radius@ZAMS.

**Comment by ilyamandel** [comment]
Thank you for the fix, @jeffriley !  Closing.
