### ISSUE TITLE
Make the column header strings for stellar properties LAMBDA_* consistent

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#363]
**Is your feature request related to a problem? Please describe.**

The stellar properties LAMBDA_* have the following column header strings:

    LAMBDA_DEWI              "Dewi"
    LAMBDA_FIXED             "Lambda_Fixed"
    LAMBDA_KRUCKOW           "Kruckow"
    LAMBDA_KRUCKOW_BOTTOM    "Kruckow_Bottom"
    LAMBDA_KRUCKOW_MIDDLE    "Kruckow_Middle"
    LAMBDA_KRUCKOW_TOP       "Kruckow_Top"
    LAMBDA_LOVERIDGE         "Loveridge"
    LAMBDA_LOVERIDGE_WINDS   "Loveridge_Winds"
    LAMBDA_NANJING           "Lambda_Nanjing"

These are not consistent (consider LAMBDA_FIXED and LAMBDA_NANJING cf. the others)

**Describe the solution you'd like**

I propose we make the header strings consistent, and change them to:

    LAMBDA_DEWI              "Lambda_Dewi"
    LAMBDA_FIXED             "Lambda_Fixed"
    LAMBDA_KRUCKOW           "Lambda_Kruckow"
    LAMBDA_KRUCKOW_BOTTOM    "Lambda_Kruckow_Bottom"
    LAMBDA_KRUCKOW_MIDDLE    "Lambda_Kruckow_Middle"
    LAMBDA_KRUCKOW_TOP       "Lambda_Kruckow_Top"
    LAMBDA_LOVERIDGE         "Lambda_Loveridge"
    LAMBDA_LOVERIDGE_WINDS   "Lambda_Loveridge_Winds"
    LAMBDA_NANJING           "Lambda_Nanjing"

**Describe alternatives you've considered**

We could just drop the "Lambda_" prefix for them all, but that would leave "LAMBDA_FIXED" as just "FIXED" which, without context, is likely to be confusing.

**Additional context**

**Comment by ilyamandel** [comment]
Thank you for the fix, @jeffriley !  Closing.
