### ISSUE TITLE
Error in Hurley remnant mass calculation

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#375]
**Describe the bug**
I think there are errors in how we calculate the remnant masses (and types) using the Hurley prescription. 

According to Hurley 2000, Eq. 92, 
`M_NS = 1.17 + 0.09*M_core`
and M_core > 7.0 should lead directly to a BH (with a minimum mass of 1.8 M_sun).

Using the Hurley remnant mass prescription, I find many NS remnants formed with mCO > 7, which should be BHs. I also find that the remnant mass itself is sometimes incorrect. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
Running an otherwise default pythonSubmit with `remnant_mass_prescription = 'HURLEY2000'`, the following seeds give the incorrect type:
[3, 7, 12, 21, 25]

And the seed 5 is an example of an incorrect remnant mass. It has a mCO = 6.598641, which should give a mNS = 1.763878, but compas calculates mNS = 1.915639.

**Expected behavior**
Any systems with mCO > 7 (or equivalently mNS > 1.8) should be a BH, and the masses should follow directly from the simple equation above. There is no fallback in this prescription (which agrees with the COMPAS output), so this cannot explain the extra mass.

**Screenshots**

**Versioning (please complete the following information):**
 - COMPAS [e.g. v02.15.01]

**Additional context**

**Comment by ilyamandel** [comment]
GiantBranch::ResolveCoreCollapseSN():

        case REMNANT_MASS_PRESCRIPTION::HURLEY2000:                                                         // Hurley 2000
            m_Mass                              = NS::CalculateRemnantMass_Static(m_CoreMass);

where
NS::CalculateRemnantMass_Static(const double p_CoreMass)    { return 1.17 + (0.09 * p_CoreMass); }

so this uses the total core mass, not the CO core mass.  

I agree that Hurley+ calls for the CO core mass to be used in Eq. (92), so this is just a mistake in the code.

Will fix.

**Comment by ilyamandel** [comment]
Should be fixed in issue in #376.

**Comment by reinhold-willcox** [comment]
thanks @ilyamandel
