### ISSUE TITLE
Layout issue in Readme.md (when viewing with MacDown.app)

### ISSUE THREAD

**Issue by demink** [TeamCOMPAS/COMPAS#379]
**Describe the bug**
Missing newline in Readme.md gives unintended layout in markdown, at least in a standard Markdownviewer for Mac.  Easy fix by placing a new line after "Furthermore,".

**Label the issue**
Very low urgency. Zero impact.  
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
1. View Readme.md in MacDown.app v 0.7.3 (=latest) on Mac OSX Cataline. 

**Expected behavior**
The layout of the papers to cite should be consistent and currently is not.  

**Screenshots**

- Before as shown by MacDown.app. Note how the Broekgaarden paper is shown with an inconsistent layout.

![image](https://user-images.githubusercontent.com/12985691/94498531-697fc400-01c8-11eb-8f64-7cf2dff3f3e3.png)

- After fixing:

![image](https://user-images.githubusercontent.com/12985691/94498551-74d2ef80-01c8-11eb-8dc5-01da5f3e25b6.png)

**Comment by reinhold-willcox** [comment]
@demink You are not listed as an available PR reviewer - would you like to be added?

**Comment by ilyamandel** [comment]
Resolved by @reinhold-willcox with PR #380 , closing.
