### ISSUE TITLE
Minor typos in alphaR and betaR for main sequence radius evolution

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#381]
**Describe the bug**
Some minor typos in the calculations of alphaR and betaR for calculating the main sequence radius changes.

**Label the issue**
`urgency_low`, `severity_minor`

**To Reproduce**
Two small typos:
1. File [MainSequence.cpp](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/MainSequence.cpp), [line 295](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/MainSequence.cpp#L295)
        - I believe the `a[68 - 1]` should be `a[68]`. @jeffriley pointed out in Slack that this is left over from when the arrays were indexed differently.
2. File [MainSequence.cpp](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/MainSequence.cpp), [line 324](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/MainSequence.cpp#L324)
        - I think some parentheses got mixed up in transcribing this...the line currently reads
`else if (utils::Compare(p_Mass, 2.0)   <  0) betaRPrime = a[72] + m_RConstants[static_cast<int>(R_CONSTANTS::B_BETA_R)] - (a[72] * (p_Mass - a[74]) / (2.0 - a[74]));`
I think this should be changed to
`else if (utils::Compare(p_Mass, 2.0)   <  0) betaRPrime = a[72] + (m_RConstants[static_cast<int>(R_CONSTANTS::B_BETA_R)] - a[72]) * (p_Mass - a[74]) / (2.0 - a[74]);`

**Expected behavior**
N/A

**Screenshots**
N/A

**Versioning (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - COMPAS: v02.14.00

**Additional context**
See Hurley+2000 Eq 21ab and 22ab for alphaR and betaR

**Comment by ilyamandel** [comment]
Should be fixed by #389, closing.
