### ISSUE TITLE
Typo in B constant for deltaR parameter for main sequence radius evolution

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#382]
**Describe the bug**
Missing -1 in calculation of B constant

**Label the issue**
`urgency_low`,`severity_moderate`

**To Reproduce**
Problem is with [BaseStar.cpp:547](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/BaseStar.cpp#L547). The constant B should be calculated as deltaR(M=2.0) but this is deltaR(M=2.0) + 1, there is a missing -1 at the end of the line. (See Hurley+2000 Eq.17)

**Expected behavior**
N/A

**Screenshots**
More detail in Slack but here is a comparison of how it affects things
![image](https://user-images.githubusercontent.com/21990332/94507933-d736ea80-01de-11eb-82e3-8d158822c85c.png)

**Versioning (please complete the following information):**
  - OS: macOS Catalina 10.15.7
  - COMPAS: v02.14.00

**Additional context**
N/A

**Comment by ilyamandel** [comment]
Should be fixed by #389, closing.
