### ISSUE TITLE
Typo in coefficient for final MS radius of stars with masses between 1.4 and 1.5 Msun

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#383]
**Describe the bug**
Typo in a coefficient for calculating the radius at the end of the main sequence. Affects stars with masses between 1.4 and 1.5 Msun.

**Label the issue**
`urgency_low`, `severity_minor`

**To Reproduce**
See file [MainSequence.cpp:line 407](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/MainSequence.cpp#L407). For the calculation of `y[1]`, the `a[2]` is used at the end of the line instead of `a[22]`. See Hurley+2000 Eq 9a+b for comparison (this is the interpolation region).

**Expected behavior**
N/A

**Screenshots**
N/A

**Versioning (please complete the following information):**
 -   OS: macOS Catalina 10.15.7
 -   COMPAS: v02.14.00

**Additional context**
N/A

**Comment by ilyamandel** [comment]
Should be fixed by #389, closing.
