### ISSUE TITLE
Mistake in calculation of the helium burning timescale for stars with M < M_HeF

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#384]
**Describe the bug**
alpha4 is missing some factors which leads to an incorrect calculation of the helium burning timescale.

**Label the issue**
`urgency_low`,`severity_minor`

**To Reproduce**
The timescale is calculated in [CHeB.cpp: line 932](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/CHeB.cpp#L932). It uses alpha4.
Alpha4 is calculated in [BaseStar.cpp:line 787](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/BaseStar.cpp#L787).
The text below Eq. 57 in Hurley shows that alpha4 should be `[tHe(M_HeF) - b39] / b39`. However, the code misses these b39 factors and just sets `alpha4=tHe(M_HeF)`

If you subtract b[39] and divide the result by b[39] you'll be all set.

*Side Note:* Not sure how things are usually done, but it is okay that m_alpha4 isn't defined at all in the function for calculating the timescale?

**Screenshots**
Coloured dots are COMPAS, grey is SSE. Colour is a measure of the difference between the two.
![image](https://user-images.githubusercontent.com/21990332/94964650-15c2f280-04c8-11eb-8d5a-6fda79d5ef13.png)

**Comment by ilyamandel** [comment]
@TomWagg :

_Side Note: Not sure how things are usually done, but it is okay that m_alpha4 isn't defined at all in the function for calculating the timescale?_

m_Alpha4 is a class variable in the BaseStar class (see BaseStar.h) from which CHeB inherits.

**Comment by ilyamandel** [comment]
Should be fixed by #389, closing.
