### ISSUE TITLE
Mistake in radius evolution on AGB for stars with masses M_HeF - 0.2 < M < M_HeF

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#385]
**Describe the bug**
Mistake in radius evolution on AGB for stars with masses M_HeF - 0.2 < M < M_HeF. Stars end up too cold (and so too large) during the AGB phase.

**Label the issue**
`urgency_low`, `severity_minor`

**To Reproduce**
See file [EAGB.cpp:line 491](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/EAGB.cpp#L481). For stars with masses in M_HeF - 0.2 < M < M_HeF, the values of A and b50 are interpolated between the values at the endpoints of this range. Therefore, y2 for the calculate of A should be the same at A(M_HeF), but this is not the case. The minimum function is neglected (perhaps because at solar metallicity the left side is always smaller?) and this causes the issue.

Essentially just need to replace
`double y2        = b[51] * pow(x2, -b[52]);`
with
`double y2        = std::min((b[51] * pow(x2, -b[52])), (b[53] * pow(x2, -b[54])));`

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/21990332/94966964-2aa18500-04cc-11eb-9961-bb8af9dc12ed.png)
Affer
![image](https://user-images.githubusercontent.com/21990332/94967306-cdf29a00-04cc-11eb-9a77-b482e0ef2989.png)

**Comment by ilyamandel** [comment]
Should be fixed by #389, closing.
