### ISSUE TITLE
COMPAS hangs while evolving a ~0.79 solar mass single star at solar metallicity

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#394]
**Describe the bug**
COMPAS hangs while evolving a ~0.79 solar mass single star at solar metallicity using default settings.

**Label the issue**
Please label the 'severity' and 'urgency' of this issue. You can choose:
`urgency_low`      - This issue is not urgent
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Run COMPAS to evolve low mass single stars in the mass range 0.7-0.9 solar masses using default settings. An example pythonSubmit is attached, or you can run:
`$COMPAS_ROOT_DIR/src/COMPAS --single-star  --use-mass-loss  --massTransfer  --RLOFPrinting  --pair-instability-supernovae  --pulsational-pair-instability  --common-envelope-allow-main-sequence-survive  --number-of-binaries 10 --metallicity 0.0142 --common-envelope-alpha 1.0 --common-envelope-lambda 0.1 --common-envelope-slope-Kruckow -0.8333333333333334 --common-envelope-alpha-thermal 1.0 --common-envelope-lambda-multiplier 1.0 --luminous-blue-variable-multiplier 1.5 --wolf-rayet-multiplier 1.0 --mass-transfer-fa 0.5 --mass-transfer-jloss 1.0 --maximum-evolution-time 13700.0 --maximum-number-timestep-iterations 99999 --initial-mass-min 5.0 --initial-mass-max 150.0 --initial-mass-power 0.0 --semi-major-axis-min 0.01 --semi-major-axis-max 1000.0 --mass-ratio-min 0.0 --mass-ratio-max 1.0 --minimum-secondary-mass 0.1 --eccentricity-min 0.0 --eccentricity-max 1.0 --pulsar-birth-magnetic-field-distribution-min 11.0 --pulsar-birth-magnetic-field-distribution-max 13.0 --pulsar-birth-spin-period-distribution-min 10.0 --pulsar-birth-spin-period-distribution-max 100.0 --pulsar-magnetic-field-decay-timescale 1000.0 --pulsar-magnetic-field-decay-massscale 0.025 --pulsar-minimum-magnetic-field 8.0 --orbital-period-min 1.1 --orbital-period-max 1000 --kick-magnitude-sigma-CCSN-NS 265.0 --kick-magnitude-sigma-CCSN-BH 265.0 --fix-dimensionless-kick-magnitude -1 --kick-direction-power 0.0 --random-seed 0 --mass-transfer-thermal-limit-C 10.0 --eddington-accretion-factor 1 --PISN-lower-limit 60.0 --PISN-upper-limit 135.0 --PPI-lower-limit 35.0 --PPI-upper-limit 60.0 --maximum-neutron-star-mass 2.5 --kick-magnitude-sigma-ECSN 30.0 --kick-magnitude-sigma-USSN 30.0 --kick-scaling-factor 1.0 --maximum-mass-donor-Nandez-Ivanova 2.0 --common-envelope-recombination-energy-density 15000000000000.0 --common-envelope-mass-accretion-max 0.1 --common-envelope-mass-accretion-min 0.04 --zeta-main-sequence 2.0 --zeta-radiative-envelope-giant 6.5 --kick-magnitude-max -1.0 --log-level 0 --debug-level 0 --single-star-mass-steps 10 --single-star-mass-min 0.75 --single-star-mass-max 0.85 --case-bb-stability-prescription ALWAYS_STABLE --chemically-homogeneous-evolution NONE --mass-loss-prescription VINK --mass-transfer-angular-momentum-loss-prescription ISOTROPIC --mass-transfer-accretion-efficiency-prescription THERMAL --mass-transfer-rejuvenation-prescription STARTRACK --initial-mass-function KROUPA --semi-major-axis-distribution FLATINLOG --mass-ratio-distribution FLAT --eccentricity-distribution ZERO --rotational-velocity-distribution ZERO --remnant-mass-prescription FRYER2012 --fryer-supernova-engine DELAYED --black-hole-kicks FALLBACK --kick-magnitude-distribution MAXWELLIAN --kick-direction ISOTROPIC --outputPath $COMPAS_ROOT_DIR/defaults --common-envelope-lambda-prescription LAMBDA_NANJING --stellar-zeta-prescription SOBERMAN --mass-transfer-thermal-limit-accretor CFACTOR --pulsational-pair-instability-prescription MARCHANT --neutron-star-equation-of-state SSE --pulsar-birth-magnetic-field-distribution ZERO --pulsar-birth-spin-period-distribution ZERO --common-envelope-mass-accretion-prescription ZERO --envelope-state-prescription LEGACY --logfile-delimiter COMMA`

[pythonSubmit.txt](https://github.com/TeamCOMPAS/COMPAS/files/5344331/pythonSubmit.txt)

The 0.79 solar mass star causes COMPAS to hang.

**Expected behavior**
COMPAS would complete the evolution, or throw an error, not hang.

**Screenshots**
NA

**Versioning (please complete the following information):**
 - COMPAS v02.15.11

**Additional context**
NA

**Comment by jeffriley** [comment]
The problem is that low mass stars live for a very long time...  In this case they are all evolving for > 14Gyr - the detailed output files show that the age grows, then wraps back to 0 - at which time (!) bad things happen.  Some stars eventually switch stellar types if they are evolved for long enough (several time the age of the universe), but others just keep on evolving...

**Comment by ilyamandel** [comment]
Resolved through PRs #395 , #396 , and #397 .  Someone who understands what's expected for low-mass stars better than I do may still want to check the radial evolution during the "CHeB" phase -- it seems somewhat surprising to me -- but that's a separate issue, if any.
