### ISSUE TITLE
Add SEED to grid files

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#401]
SEED should be added as an (optional) entry to the list of input parameters in a grid file. The seed of a system is the best way to identify it when chasing down bugs or trying to reproduce a given system. However, since the seed is not included in a grid file, finding the correct grid line to associate to a specific seed involves a rather tedious dig through various output files to match line numbers and compare initial conditions against each other. 

**Describe the solution you'd like**
SEED should be a parameter like all the other initial inputs in a grid file, and the stroopwafel sampler should supply this into the Grid file. This will ensure that the same grid line, run on identical versions of COMPAS, will always produce the same output, and will make reproducing specific systems much easier. 

Edit: adding this into the stroopwafel sampler is a good first issue, after the fix has been made in compas.

**Comment by jeffriley** [comment]
Implemented in v02.16.00 ( PR #423 )

@reinhold-willcox Can this be closed now, or is there work to do in stroopwafel?
