### ISSUE TITLE
Remove SN_Theta and SN_Phi from SSE Supernova file

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#409]
**Describe the bug**

The SSE Supernova file was implemented as a result of Issue #253.  SN_Theta and SN_Phi were included in the SSE Supernova file, but are meaningless for SSE - they are never initialised or used in the SSE code.

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**

Run COMPAS in SSE mode and look at the supernova file produced

**Expected behavior**

SN_Theta and SN_Phi columns not printed in SSE Supernova file

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Ubuntu 18.04
 - COMPAS v02.15.19

**Additional context**

**Comment by ilyamandel** [comment]
Thank you for the fix, @jeffriley !  Closing.
