### ISSUE TITLE
Remove AIS from the COMPAS code

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#411]
Since adaptive importance sampling is now happening externally to the COMPAS C++ code, we should remove all AIS-specific code from the C++ code.  This should not impact performance, but will keep the code streamlined and easy to maintain.

**Comment by jeffriley** [comment]
If there is no finesse required here (i.e. all AIS-related code to be removed rather than a surgical removal of just some that requires knowledge of what should be removed), I'm happy to do that the next time I push modified code.

**Comment by jeffriley** [comment]
Done in v02.17.03
