### ISSUE TITLE
Baryon number for HeWD incorrect in COMPASUnorderedMap<STELLAR_TYPE, double> WD_Baryon_Number in constants.h

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#416]
**Describe the bug**

Baryon number for HeWD incorrect in COMPASUnorderedMap<STELLAR_TYPE, double> WD_Baryon_Number in constants.h.
Is 0.4, should be 4.0 (See Hurley et al., 2000, just after eq 90)

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**

**Expected behavior**

Baryon number for HeWD in COMPASUnorderedMap<STELLAR_TYPE, double> WD_Baryon_Number in constants.h changed to 4.0

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Ubuntu 18.04
 - COMPAS v02.15.19

**Additional context**

**Comment by ilyamandel** [comment]
Fixed in PR #429, closing.
