### ISSUE TITLE
Lambda Nanjing values

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#418]
Although our Lambda Nanjing appears to be a faithful copy of StarTrack, there are unintended features in the StarTrack lambdas for some stellar types which lead to discontinuous lambda (and, if it weren't for bracketing, could lead to unphysical or even negative lambdas).  When this is the case (e.g., CHeB), we should follow the example of other stellar types (e.g., EAGB) and interpolate lambda in order to generate smooth behaviour.

Example: 
Currently implemented Nanjing lambda for CHeB donor as a function of radius for Z<0.5 Zsol and Mdonor between 18 and 35 solar masses

<img width="538" alt="image" src="https://user-images.githubusercontent.com/512213/97772014-d2c37000-1b96-11eb-858e-2f8892fb6c0f.png">

**Comment by avigna** [comment]
Thanks for these checks. I don't feel like this is an issue in itself, but more a general problem trascend Nanjing or StarTrack. In summary, it would be good to have a better and/or self consistent calculation of lambda. Here an example of Kruckow+2016 where you can see that lambda is a bit of a mess.

<img width="459" alt="Screenshot 2020-10-31 at 10 31 14" src="https://user-images.githubusercontent.com/22151352/97775888-865f3c80-1b64-11eb-908c-94b8033354a7.png">

**Comment by themikelau** [comment]
Just a reminder to myself to clean up several instances of this sort of thing along the way, e.g., in CHeB.cpp,
```
 else if (utils::Compare(m_MZAMS, 4.5) < 0) {
            maxBG = { 1000.0, 8.0 };
            if (utils::Compare(m_Radius, 410.0) > 0) lambdaBG = { 52.980056, 1.109736 };
            else {
                maxBG = { 2.5, 1.5 };
                a     = { -7.3098 , 0.56647, -0.01176, 7.90112E-05, 0.0, 0.0 };
                b     = { -3.80455, 0.29308, -0.00603, 4.00471E-05, 0.0, 0.0 };
            }
        }
```
From what I can tell, `maxBG = { 1000.0, 8.0 }` is actually not used. It seems to an artifact created by copying over from StarTrack.
