### ISSUE TITLE
Core mass after 2nd dredge-up calculated before core at BAGB

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#419]
**Describe the bug**
The core mass of a star after the second dredge up is calculated before the core mass at BAGB

**Label the issue**
`urgency_low`,`severity_minor`

**To Fix**
See [GiantBranch.cpp:271](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/GiantBranch.cpp#L271), I think lines 271 and 272 should be swapped.

Otherwise I think the final core mass could be slightly off depending on the timesteps.

**Comment by ilyamandel** [comment]
Fixed in PR #429, closing.
