### ISSUE TITLE
Wrong mass used in calculating minimum raduis on CHeB

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#420]
**Describe the bug**
Affects stars with mass < MHeF, wrong mass is used. p_Mass is used in place of p_MHeF

**Label the issue**
`urgency_low`, `severity_minor`

**To Reproduce**
See [CHeB.cpp:688](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/CHeB.cpp#L688), particularly `b[25] * p_Mass` should instead be `b[25] * p_MHeF` (see Hurley+2000, Eq. 55).

**Comment by ilyamandel** [comment]
Fixed in PR #429, closing.
