### ISSUE TITLE
Inconsistent parameter headers

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#455]
**Describe the bug**
A recent fix to the parameter headers changed the _1, _2, _SN, and _CP identifier suffixes to (1), etc. However, this was not applied consistently to all parameters.

In the CEs output, I see the following parameters:

['BE_Fixed(1)', 'BE_Fixed(2)', 'BE_Kruckow(1)', 'BE_Kruckow(2)', 'BE_Loveridge(1)', 'BE_Loveridge(2)', 'BE_Loveridge_Winds(1)', 'BE_Loveridge_Winds(2)', 'BE_Nanjing(1)', 'BE_Nanjing(2)', 'Binding_Energy<CE(1)', 'Binding_Energy<CE(2)', 'CE_Event_Count', 'Core_Mass_1', 'Core_Mass_2', 'Double_Core_CE', 'Eccentricity<CE', 'Eccentricity>CE', 'Immediate_RLOF>CE', 'Lambda@CE(1)', 'Lambda@CE(2)', 'Lambda_Fixed(1)', 'Lambda_Fixed(2)', 'Lambda_Kruckow(1)', 'Lambda_Kruckow(2)', 'Lambda_Lambda_Nanjing(1)', 'Lambda_Lambda_Nanjing(2)', 'Lambda_Loveridge(1)', 'Lambda_Loveridge(2)', 'Lambda_Loveridge_Winds(1)', 'Lambda_Loveridge_Winds(2)', 'Luminosity<CE(1)', 'Luminosity<CE(2)', 'MT_History', 'Mass_1<CE', 'Mass_2<CE', 'Mass_Env_1', 'Mass_Env_2', 'Merger', 'Optimistic_CE', 'RLOF(1)', 'RLOF(2)', 'Radius_1<CE', 'Radius_1>CE', 'Radius_2<CE', 'Radius_2>CE', 'RocheLobe_1<CE', 'RocheLobe_1>CE', 'RocheLobe_2<CE', 'RocheLobe_2>CE', 'SEED', 'SemiMajorAxis<CE', 'SemiMajorAxis>CE', 'Simultaneous_RLOF', 'Stellar_Type(1)', 'Stellar_Type(2)', 'Stellar_Type_1<CE', 'Stellar_Type_2<CE', 'Tau_Circ', 'Tau_Dynamical<CE(1)', 'Tau_Dynamical<CE(2)', 'Tau_Nuclear<CE(1)', 'Tau_Nuclear<CE(2)', 'Tau_Radial<CE(1)', 'Tau_Radial<CE(2)', 'Tau_Sync', 'Tau_Thermal<CE(1)', 'Tau_Thermal<CE(2)', 'Teff<CE(1)', 'Teff<CE(2)', 'Time', 'Zeta_Lobe', 'Zeta_Star']

Some of the parameters have the new suffix style, but some keep the old version. I thought this might have to do with whether the _X characters were at the end of the parameter name, but there are some which do not follow that rule either, e.g Core_Mass_1.

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
Run Compas with default settings, look at CEs output header.

**Expected behavior**
Parameter names should be consistent.

**Versioning (please complete the following information):**
 - COMPAS [e.g. v02.17.03]

**Comment by jeffriley** [comment]
I've fixed this already - just haven't pushed the fix yet (I thought I had, but no...).  I'll push the fix soon (one of the macros wasn't updated from the "_" to "()" notation)
