### ISSUE TITLE
Something may be off with SSE timesteps

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#470]
**Describe the bug**
If I create an HRD with exactly the same input for SSE stars but change the timestep to 10x lower then the result for massive stars changes dramatically. This seems to imply to me that the default timestep is not small enough perhaps?

However, I also note that when running these grids I get a lot of warnings saying `WARNING: Timestep below minimum - timestep taken!` and after printing out `m_Dt` during these warnings I note that it is exactly 0.0. So that seems iffy too

**This problem does not occur if I do the same thing but change to BSE and use very wide binaries -- it is SSE specific**

**Label the issue**
`urgency_low`,`severity_minor`

**To Reproduce**
Run COMPAS on a grid of SSE stars with default pythonSubmit.py. Then re-run with `timestep_multiplier = 0.1` and compare results.

**Expected behavior**
I expect more scatter points but in roughly the same shape.

**Screenshots**
<div>
<img src="https://user-images.githubusercontent.com/21990332/100008163-0ca12400-2d9b-11eb-8881-ffd2daf31c79.png" width="45%">
<img src="https://user-images.githubusercontent.com/21990332/100008181-1165d800-2d9b-11eb-8b1e-006a504ec4c4.png" width="45%">
</div>

**Versioning (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - COMPAS: v02.17.10

**Comment by ilyamandel** [comment]
This is actually an urgent issue, despite languishing for years.  I will elevate it to bug status.  See also #24 .

**Comment by jeffriley** [comment]
> This problem does not occur if I do the same thing but change to BSE and use very wide binaries -- it is SSE specific

We know that SSE code limits radial expansion to 1%, but BSE does not (something that might need to be addressed).

See also issue #855 - might be related (does this problem happen if run with **--luminous-blue-variable-prescription BELCZYNSKI** ?)

**Comment by jeffriley** [comment]
Revisiting this after recent changes to COMPAS, particularly the work to ensure:

    1. COMPAS SSE and BSE modes are consistent (i.e. a wide binary in BSE mode now produces the same result as a single star in SSE mode (wrt the primary)).
    2. COMPAS and Hurley's sse are consistent (i.e. the evolution of single stars in COMPAS SSE mode now matches Hurley's sse)

I ran a series of tests using COMPAS v02.45.00.  The results are shown below.

The first test was to reproduce @TomWagg's plot (shown above) using SSE mode and the default timestep.  The command I used to run the test was:

    ./compas --random-seed 0 --mode sse --initial-mass s[0.5,0.7,0.8,1.0,1.3,1.6,2.0,2.5,3.2,4.0,5.2,6.5,8.2,10.3,13.0,16.5,21.0,26.0,33.0,45.0,65.0,90.0,115.0,150.0] --detailed-output

This produced the following plot:

![HRD_COMPARISON_SSE_1 0-annotated](https://github.com/TeamCOMPAS/COMPAS/assets/26860470/d7cb38ac-d172-451d-b1bc-c483c3d2ccc7)

This plot shows that our method for calculating the timestep (for SSE mode) is probably not optimal and, especially in the area I've circled in red, produces sub-optimal (and even a little odd-looking) results.

Following @TomWagg's plots above, I re-ran that test using a timestep multiplier of 0.1 (so we take 10 times the number of steps, each of which is 1/10th the size of the default).  The commad used was:

     ./compas --random-seed 0 --mode sse --initial-mass s[0.5,0.7,0.8,1.0,1.3,1.6,2.0,2.5,3.2,4.0,5.2,6.5,8.2,10.3,13.0,16.5,21.0,26.0,33.0,45.0,65.0,90.0,115.0,150.0] --timestep-multiplier 0.1 --detailed-output

This produced the following plot (which looks much better):

![HRD_COMPARISON_SSE_0 1](https://github.com/TeamCOMPAS/COMPAS/assets/26860470/c7a5044f-a429-45bd-a83b-9ebddbe11ce0)

@TomWagg stated that

> This problem does not occur if I do the same thing but change to BSE and use very wide binaries -- it is SSE specific

I think that has been resolved by the work described in (a) above (making COMPAS SSE and BSE consistent).  To test that, I ran two more tests, similar to those above but using wide binaries in BSE mode:

    ./compas --random-seed 0 --mode bse --initial-mass-1 s[0.5,0.7,0.8,1.0,1.3,1.6,2.0,2.5,3.2,4.0,5.2,6.5,8.2,10.3,13.0,16.5,21.0,26.0,33.0,45.0,65.0,90.0,115.0,150.0] --initial-mass-2 0.1 --semi-major-axis 1e20 --detailed-output

which produced this plot:

![HRD_COMPARISON_BSE_1 0-annotated](https://github.com/TeamCOMPAS/COMPAS/assets/26860470/cd905d1d-6f97-4c87-9940-a3faf8767aa0)

which is very similar to the SSE version - the most visible differences are again in the area circled in red.  BSE mode generally uses the same timesteps as SSE mode in this configuration (very wide binaries with a very small secondary) - the only difference (I think) is that in SSE mode we limit radial expansion to 1% of the current radius, and if the timestep chosen would result in the radius expanding above that limit the timestep is discarded and a shorter timestep tried instead.  This radial expansion check is not performed in BSE mode.  That difference could account for the minor differences in the red-circled area.  Should we discard the radial expansion check in SSE mode, or add it to BSE mode - or just leave it as is?

Checking wide binaries in BSE mode with more, shorter, timesteps:

    ./compas --random-seed 0 --mode bse --initial-mass-1 s[0.5,0.7,0.8,1.0,1.3,1.6,2.0,2.5,3.2,4.0,5.2,6.5,8.2,10.3,13.0,16.5,21.0,26.0,33.0,45.0,65.0,90.0,115.0,150.0] --initial-mass-2 0.1 --semi-major-axis 1e20 --timestep-multiplier 0.1 --detailed-output

we get:

![HRD_COMPARISON_BSE_0 1](https://github.com/TeamCOMPAS/COMPAS/assets/26860470/e437c619-9e14-4b68-82e7-b87687ebd33e)

Overall I think these plots show that we're in a good place, but that our timestep calculations could be better.  @ilyamandel has advocated trying to make the timestep calculations more adaptive to the evolution of the current star/binary, and hopefully that can be implemented at some stage.  In the meantime, @ilyamandel may look at some improvements in the short-term.

**Comment by ilyamandel** [comment]
As @jeffriley mentioned above, I've been working on picking timesteps adaptively rather than ad hoc.  The pull request will be submitted once I've cleaned up the code a bit (and maybe addressed another issue or two while I am at it :) ), but you can see that it solves the remaining issues with timesteps that are too large.  This shows it for SSE, but it should also work for BSE once tested. [Warning: there is a computational cost to accuracy, and we'll have to decide on the appropriate choices...]  In any case, I think we'll be able to close this PR soon, and hopefully a few other related ones, too.

![image](https://github.com/TeamCOMPAS/COMPAS/assets/512213/6f7bfb91-666b-46a3-8410-13c66b0cff60)

**Comment by ilyamandel** [comment]
As @jeffriley wrote, SSE and BSE are now doing the same thing.  Furthermore, arbitrarily smooth HR diagrams can now be produced with #1123 .  The issue with adaptive time stepping and convergence checking still exists in principle (#24 ), but that is separate from this one.  Closing.
