### ISSUE TITLE
Anomaly: primary mass can be < specified minimum

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#475]
**Describe the bug**

Bug or feature that should be documented?

In the BaseBinaryStar constructor, if we are sampling the masses of the component stars, we do the following:

1. Sample the primary mass, m1, using the specified min and max values (say, e.g., 5.0 and 150.0)
2. Sample the mass ratio, q (or use supplied)
3. Calculate secondary mass, m2 = m1 * q
4. Check for rlof/touching - equilibrate masses and circularise if required
5. Check that m2 >= minimum secondary mass (say, 0.01) - if not, loop back to (1)

With the values specified above, if we equilibrate, we could get m1 = m2 = (5.0 + 0.01) / 2.0 = 2.505

If minimum secondary mass = 3.0, we could still get m1 = m2 = (5.0 + 3.0) / 2.0 = 4.0

Should we just document this anomaly (m1 can be less than specified value when masses are equilibrated), or should we explicitly check (at, say, (5) above) that m1 > minimum specified (which would mean that m2 is constrained by the minimum primary mass when masses are equilibrated (rather than by the specified minimum secondary mass)).

Thoughts?

**Label the issue**
Please label the 'severity' and 'urgency' of this issue. You can choose:

`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**

See above

**Expected behavior**

Pending input/decision

**Screenshots**

n/a/

**Versioning (please complete the following information):**
 - OS: Ubuntu 18.04
 - COMPAS v02.17.10

**Additional context**

**Comment by ilyamandel** [comment]
@jeffriley -- I think it is best to keep the current behaviour for sampling purposes.  The downside is that we waste a tiny fraction of time evolving systems that won't be of interest.  The upside is that it's far easier to calculate normalisations.  So I don't think we need to do anything (except, perhaps, add a comment in the documentation).

**Comment by jeffriley** [comment]
Ok, thanks.  I'll update the documentation next time I push a change.
