### ISSUE TITLE
Include Triple Letter in the COMPAS publication list

### ISSUE THREAD

**Issue by avigna** [TeamCOMPAS/COMPAS#485]
The Triple Letter (https://arxiv.org/abs/2010.13669) submitted to Apj Letter and currently under review, uses the data from Riley+2020 to highlight, arguably for the first time, the role of compact stars in massive systems, particularly binary black hole mergers. 

Under the premisse that the results and data from Riley+2020 were paramount for this Letter, I consider it should be included in the COMPAS publication list. I leave that to the discretion of the reviewers.

**Comment by SimonStevenson** [comment]
Are you asking for this to be added to https://compas.science/science.html#papers ? I think the relevant issue tracker is https://github.com/TeamCOMPAS/TeamCOMPAS.github.io/issues

**Comment by avigna** [comment]
Gotcha! I think you are right Simon. I will close this and copy the exact same thing to the link you posted.
