### ISSUE TITLE
(Giant) Core He Burning stars have WR winds at low Z

### ISSUE THREAD

**Issue by LiekeVanSon** [TeamCOMPAS/COMPAS#502]
**Describe the bug**
At Z = 0.001, for fiducial pythonSubmit, stars with MZAMS [15-30] have WR winds as their dominant Mass loss rate when they pass the VINK_MASS_LOSS_MINIMUM_TEMP  on their way to becoming red giants (and still have an envelope). 

This only seems to occur for low metallicities (at least, it doesn't happen for Z = Zsun or Z = 0.01)

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Run the attached pythonSubmit.txt (changed to .txt so I could upload it to this bug report). Also attached are required COMPAS_Output_Definitions and a grid (SingleStar_grid) to reproduce attached plots (coloured by Dominant_Mass_Loss_Rate)

This pythonSubmit is basically the  Fiducial one exccept for: luminous_blue_variable_prescription = 'HURLEY_ADD'
But the same behaviour occurs when setting luminous_blue_variable_prescription = 'BELCZYNSKI'

[COMPAS_Output_Definitions.txt](https://github.com/TeamCOMPAS/COMPAS/files/5782645/COMPAS_Output_Definitions.txt)
[SingleStar_grid.txt](https://github.com/TeamCOMPAS/COMPAS/files/5782648/SingleStar_grid.txt)
[pythonSubmit.txt](https://github.com/TeamCOMPAS/COMPAS/files/5782664/pythonSubmit.txt)

![HR_Z0 001](https://user-images.githubusercontent.com/57514659/103914769-9ff3a600-510a-11eb-84a7-eac1ed4308f9.png)

**Expected behaviour**
These are massive stars with an envelope so I think they should have NieuwenHuijzen & de Jager as dominant mass loss.

**Screenshots**
Detailed evolution for a 15 and 30 Msun example are attached:

_30 Msun_
![30Msun_envelopeCcore](https://user-images.githubusercontent.com/57514659/103914887-bf8ace80-510a-11eb-8a66-97f351bd6e2d.png)
![30MsunWinds](https://user-images.githubusercontent.com/57514659/103914882-be59a180-510a-11eb-94f1-184056d3fa5b.png)

_15 Msun_
![15MsunWinds](https://user-images.githubusercontent.com/57514659/103914877-bbf74780-510a-11eb-94d2-eb0c46b53785.png)

**Versioning (please complete the following information):**
 - OS: [macOS Big Sur]
 - COMPAS [COMPAS v02.17.18]

**Additional context**
Happy New Year to whomever is reading this! :)

**Comment by TomWagg** [comment]
I created a similar issue (#465)  a couple of weeks ago (Great minds think alike I've heard @LiekeVanSon) ;)

This problem here is that COMPAS uses a **metallicity independent** WR prescription for stars below 12500K whilst using the VINK mass loss option (COMPAS _does_ have a metallicity dependent prescription for stars above 12500K so you see normal things in the helium stars).

See the discussion at the end of PR #467 with @ilyamandel for why we're not fixing this immediately. Although we could change this to the metallicity dependent version, Ilya is planning to change how the winds work completely anyway so the plan was just to wait to do that I think.

**Comment by LiekeVanSon** [comment]
Thanks @TomWagg :D! Sorry I should've checked closed issues before creating a new one. 
Interested in hearing the new plans for wind prescriptions...!

However, I would still argue for a quick fix of this particular problem, either by making the WR winds metallicity dependent as Tom suggests, or by excluding WR winds from the "HURLEY" prescription if the "VINK" scheme is used. 
@ilyamandel I think having WR winds for the majority of BH-progenitors at low Z could have a quite severe influence on the mass distribution, right?

**Comment by ilyamandel** [comment]
Sorry for the silence, @LiekeVanSon and @TomWagg !  

I believe that, at the moment, we are allowing for WR winds for small-envelope (but not completely stripped) stars in agreement with Hurley+, 2000 (see section 7.1, relevant screenshot attached).  

It's clear that we need a coherent plan for handling winds that accounts for all of the updates since Hurley+.  Alas, I haven't had a chance to catch up on the relevant literature.  If someone is ahead of me, could you perhaps write up a one-page suggestion for a sensible replacement to section 7.1 of Hurley+?

<img width="479" alt="image" src="https://user-images.githubusercontent.com/512213/105296312-f0d8c380-5c0d-11eb-80e5-e8b85a7feefb.png">

**Comment by LiekeVanSon** [comment]
Hey Ilya, no problem, no hurry with this!

I understand that Hurley is using WR winds for low envelope masses, but the thing that troubles me here is that the Hurley-WR winds become dominant for a short period of time _while there is still a significant envelope present_ (see pink line in 30 Msun plot above). 
Moreover while the envelope decreases, (so while we're getting closer to something WR-like) we switch back to RSG winds...? This is all caused by the WR winds not being metallicity dependend, hence WR winds dominate in weird places.

Personally I think it would be a safe update to just add the Z dependence (Z/Zsun)^0.86  from Vink & de Koter (2005)  to the Hurley WR rate. But I understand how you also want to have a coherent plan for all of Hurley's section 7.1!

**Comment by ilyamandel** [comment]
@jmerritt1 , @SimonStevenson -- do you think there is value in providing an option to adjust the winds as in @LiekeVanSon 's last suggestion, or will this be supplanted by the new wind models, anyway?

**Comment by ilyamandel** [comment]
@SimonStevenson , @jmerritt1, @LiekeVanSon  -- is this moot after the wind model update, or is it still relevant?

**Comment by ilyamandel** [comment]
Another ping for @SimonStevenson , @jmerritt1, @LiekeVanSon  -- is this still an issue after the wind model update, or is it resolved?

**Comment by LiekeVanSon** [comment]
Hi Ilya, sorry for the delay, I thought this issue was solved in the previous COMPAS version by adopting metallicity dependent WR winds (CalculateMassLossRateWolfRayetZDependent) as the default option. 

I think this issue might be back in the new wind prescription, in particular because the Beasor RSG winds are much weaker than old RSG winds. see orange before the lemon green appearing in the gifs below:

![HR_v02_46_01__M30_Dominant_Wind](https://github.com/TeamCOMPAS/COMPAS/assets/57514659/5a5f772f-b7d7-48b0-8491-6c820e1fd1eb)
![HR_v02_46_01__M40_Dominant_Wind](https://github.com/TeamCOMPAS/COMPAS/assets/57514659/d5257aa8-9a98-4762-b977-0b79342ba290)

But also Fig. 1 in JD's overleaf draft seems to show that WR winds dominate before RSG winds? 

@jmerritt1 and @SimonStevenson, maybe a check for envelope mass in the dominant wind prescription would be the best solution? I.e. don't allow WR wind to be the dominant wind mass loss prescription if the star still has a significant envelope on top.

**Comment by ilyamandel** [comment]
@LiekeVanSon , @jmerritt1 , @SimonStevenson -- just a reminder that it would be great to address this as part of the wind prescription changes.

**Comment by LiekeVanSon** [comment]
Copying over some of the discussion related to this: 

**JD Merritt**
I absolutely agree that we should fix a few outstanding issues:
-Regarding WR winds being applied at CHeB, Reminder that this is happening at low Z, in the Teff range of 8-12.5kK, just after HG crossing. Here are some solutions I'm recalling now, let me know if you think of better ones:
1. We could just force the CHeB stars in this Teff range to use GB winds. This seems like the simplest solution, and I can't think of any issues it would cause. For some reason I don't see a mass loss calculation in CHeB.cpp(edit: it inherits), whereas the mass loss in GiantBranch.cpp takes the greatest of NJ, KR, and WR winds.
2. We can add an envelope check to the logic applying WR winds, or just a stellar type check (could this be a problem for WNh type stars or anything like this?).
3. We could interpolate between OB and RSG winds somehow. (Matteo Cantiello suggested this).


**Lieke van Son**
Re the WR winds: I think a temperature cut would make sense! :slightly_smiling_face: I believe observational WR stars are supposed to be hotter than ~20000K =4.3 in log10 (but @Andreas Sander might know their expected temperatures better). Why don't you add such a temperature check in the WR-wind prescriptions (i.e. if cooler than T_minWR wind Mdor WR = 0. This should hopefully introduce minimal changes while still having 'some' physical basics?
 
 
**Andreas Sander**
 A temperature cut is rather common in selecting the wind regimes in evolution models with T~20kK being indeed a typical value for which below there are no WR stars, if you take their "Tstar" temperatures (T23 can be lower). However, the question is whether this is really what you want. There are objects such as PCyg or to some extreme even etaCar that essentially have WR-like winds, but are not formally classified as WR because their winds are too cool (albeit being optically thick). If I understand the problem correctly, the issue is that you get WR winds when expanding towards the RSG, which is indeed odd. Yet, I see no problem applying the WR winds for post-RSG stars as long as there is no better description. Consequently, a simple temperature cut might not be ideal here as it would catch pre- and post-RSG cases. For the pre-RSG regime, you seem to apply the "Giant Branch" recipe at high Z, but not at low Z. Since this looks like the recipe designed for AGBs, the problem seems to be broader than just triggering the WR recipe, but in general there is a span between the OB and RSG regime where you do not switch to a recipe designed for this regime. Indeed the best way would propably be to just extend the OB or interpolate between OB and RSG. If you need a temperature switch, you can increase the OB-star regime down to 8000K, which is reasonable for line-driven winds, and then use RSG from there.
 
 
 **Lieke van Son**
Thanks for the additional context Andreas!
Looking at the left hand panel of JD's Fig. 1 exdending OB down to 8000 (=3.9) would switch a lot of stars from GB winds to OB winds at high metallicities, which might actually be an additional good thing?  : )


**Andreas Sander**
Yeah, I think this would be good.


@jmerritt1 I believe you then lowered VINK_MASS_LOSS_MINIMUM_TEMP to 8000. Can you confirm whether this solved the issue? (and if this is implemented in dev?)

**Comment by jmerritt1** [comment]
> @jmerritt1 I believe you then lowered VINK_MASS_LOSS_MINIMUM_TEMP to 8000.

Yes, this did fix the issue, and has been implemented, however we are seeing GB winds in parts of the Teff range in question at higher Z. Will comment when we know the cause.

**Comment by jmerritt1** [comment]
![HRD_DMLR](https://github.com/user-attachments/assets/3541bcb5-2f7e-42d7-8fb3-80a6b7626315)
Okay so specifically at Zsolar (left panel), with M_ZAMS of 21-45, we now have a short period during HG where GB winds are applied (Hurley, or the greatest of NJ, KR, WR). This is because Teff is below 8kK, and HG is not one of the types in our logic applying RSG winds (includes FGB, CHeB, EAGB, TPAGB). We could add it, if this seems appropriate. By the end of HG the radius and temperature are typical of a RSG. This is usually a very small number of timesteps and the total mass lost is probably not significant.
