### ISSUE TITLE
merge RLOF and CE output files into one "MassTransfer" file 

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#51]
see also https://docs.google.com/document/d/1FBBcce2medqnAO7PM13O2tKuhvt6lAKfjbnccB8Njas/edit

**Comment by jeffriley** [comment]
@FloorBroekgaarden @themikelau just re-implemented RLOF printing.  Should we revisit this issue - is merging the RLOF and CE files still something we might want to do?

**Comment by ilyamandel** [comment]
At the moment, we have all of the necessary information available, and it's not clear to me that there is much benefit to combining it into one file.  If there's some info that's desired in the RLOF file which is not currently available, it can be requested at runtime through the logging specification.  I am closing this issue.
