### ISSUE TITLE
Implement stable mass transfer rates onto WDs - important for AIC

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#512]
**Is your feature request related to a problem? Please describe.**
Many aspects of white dwarf evolution are currently unimplemented in COMPAS, such as novae. 

I am currently interested in the formation of pulsars through accretion induced collapse (AIC). 

I suggest that we implement a model of AIC. 

This should also remove the possibility of forming WDs more massive than the Chandrasekhar mass.

**Describe the solution you'd like**
To start with I suggest implementing the prescription from BSE (Hurley et al. 2002, 2010). 

Basically, for mass transfer rates in a suitable range, the mass of an ONeWD can grow steadily until it reaches the Chandrasekhar mass, upon which the WD may collapse to a NS (though other outcomes may also be possible). I believe that we already have accretion onto WDs, limited to the Eddington rate.

It would be useful to flag NSs formed in this way (in the same way we flag what kind of supernova a NS formed in) to quantify their importance in various settings (as pulsars, in NSWD binaries, in DNSs etc). 

NSs formed through AIC may also receive different kicks to those born in CCSNe. We should therefore implement an option for this. 

See also detailed models e.g. https://arxiv.org/abs/1706.03843

**Describe alternatives you've considered**
AIC have thus far been unimportant for many of the science cases COMPAS has been used for. We could continue to not have a model for these, but this will limit the use of COMPAS for fields where they may be important. 

**Additional context**
NA

**Comment by SimonStevenson** [comment]
Message on slack from Ilya:

Interesting: it seems that we may have unintentionally implemented accretion induced collapse in COMPAS!  :wink:
I noticed that, in a long run, there was a supernova happening 13 Gyr after star formation, so I looked at it more closely.  It seems that the progenitor is a ONe WD, which has a mass of 1.31 solar masses, but then accretes some mass from a Roche lobe overflowing companion (a 0.9 solar mass giant) … and forms a neutron star through an electron capture supernova.

**Comment by SimonStevenson** [comment]
Indeed AIC is already implemented. One thing that is not currently implemented is the range of stable burning rates see e.g. Nomoto 1982 . Issue title updated accordingly. See attached figure

![stableMdotNomoto](https://user-images.githubusercontent.com/6952112/105104529-87ba5880-5b06-11eb-9598-47afc368bac7.png)

**Comment by reinhold-willcox** [comment]
This also assumes standard ECSN remnant mass and kick, which may not match models for AIC (I haven't looked closely at those). This is an interesting project though, let me know if you would like help implementing this @SimonStevenson.

**Comment by ilyamandel** [comment]
@SimonStevenson, @reinhold-willcox -- I agree with the proposal to relabel these as a different SN type (AIC instead of ECSN), providing the flexibility for alternative remnant prescriptions and better tracking.  I also agree with modifying mass transfer onto WDs to differentiate between regimes leading to novae, stable MT, or Type IA -- but I think the latter is, technically, a separate (though related) issue.

**Comment by ilyamandel** [comment]
Open the latter issue as #638 .

**Comment by ilyamandel** [comment]
OK, I think with @solfreludio 's work, the thing that actually needs to be done on AICs is fairly minor -- relabel them as a different SN type.  @solfreludio -- is that something you are already doing, or should we do this as a follow-up, after your PR is pulled in?

**Comment by reinhold-willcox** [comment]
@ilyamandel This is included as part of @solfreludio 's PR, and should be merged in in the next month.

**Comment by ilyamandel** [comment]
This was addressed by @nrsegovia , closing.
