### ISSUE TITLE
Duplicate values in SystemParams and Supernovae

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#536]
This is a very small change, but some of the data columns in the BSE_System_Parameters file are redundant. 

Some of the kick parameters, specifically 'SN_Kick_Magnitude_Random_Number', 'SN_Kick_Mean_Anomaly', 'SN_Kick_Phi', and 'SN_Kick_Theta' are all present (and more applicable) in the BSE_Supernovae data file. The kick sigma values however are fine.

Also, 'Stellar_Type' is redundant with 'Stellar_Type@ZAMS' which also exists in the SysParams file. I propose to remove the kick parameters and stellar type from BSE_System_Parameters.

**Comment by jeffriley** [comment]
Stellar_Type shouldn't be redundant with Stellar_Type@ZAMS - Stellar_Type is the stellar type of the star when the file entry is printed, so for BSE_System_Parameters  it will be the final stellar type. Stellar_Type@ZAMS is the initial stellar type.

I'd prefer both stay in BSE_System_Parameters - I don't always generate a BSE_Supernovae file (and what if the star I'm interested in doesn't have a SN event?).  The initial and final stellar type of the stars are system attributes, not specific to SNe.

(I could add/delete columns I want at runtime, but it seems t o me the initial and final stellar types are columns that should be in the system parameters output file...)

**Comment by reinhold-willcox** [comment]
Touche, I hadn't realized the suffix-less one was the final stellar type. It makes sense to keep it then.

**Comment by ilyamandel** [comment]
@reinhold-willcox -- is this still an issue?

**Comment by reinhold-willcox** [comment]
No, I'll go ahead and close it.

**Comment by reinhold-willcox** [comment]
Oh wait no, it is! Sorry I skimmed the last two comments too quickly.

**Comment by reinhold-willcox** [comment]
@jeffriley Are you ok with removing the kick parameters from system_parameters, or is there a compelling reason to leave them both there and in the SN output?

**Comment by jeffriley** [comment]
@reinhold-willcox I have no issue with removing them, with the caveat that (as we saw a couple of days ago), the mean anomaly is not in the SN file (the true anomaly is), so maybe we need to add it to the SN file (I think I'm remembering correctly)

**Comment by reinhold-willcox** [comment]
I agree, and I'm happy to do both.

**Comment by reinhold-willcox** [comment]
The above changes have just been pushed to PR #622, so I'll close this now.
