### ISSUE TITLE
Simplify and clean `CalculateTimeToCoalescence` function

### ISSUE THREAD

**Issue by avigna** [TeamCOMPAS/COMPAS#538]
**Describe the bug**
The `CalculateTimeToCoalescence` currently handles exceptions individually; however, there is no need for this following Peters 1964. We need to remove the if statements and leave an unique integral. Moreover, we need to use an integrator to solve for that integral instead of an ad-hoc Rieman sum solver.

**Label the issue**
`urgency_low`
`severity_minor`

**Versioning (please complete the following information):**
 - COMPAS v02.18.09

**Comment by ilyamandel** [comment]
Splitting up the integral into three cases is warranted because at e->0 and e->1, there are nominal singularities and the expression is prone to numerical errors.  I agree with either using a Riemann solver... or using my analytical fit.  Any objection to the latter, @avigna ?

**Comment by avigna** [comment]
Good with the analytical fit!
