### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#543]
At the moment, we have COMPAS_Doc.pdf, COMPAS_CHE.docx, COMPAS_CHE.pdf, and a latex directory which does not automatically produce PDF outputs. The instructions in getting_started.md point to COMPAS_Doc.pdf, which is out of date relative to the latex files.  A non-expert user may not know where to look.  

I propose we delete COMPAS_Doc.pdf, COMPAS_CHE.docx, COMPAS_CHE.pdf (any information contained there should be available via the latex documentation) to avoid confusion, and update the getting_started.md documentation to point to it.   It would be great if we could set up an automatic re-compilation of a pdf from the .tex files, but that's less urgent as long as we have clear instructions.

**Comment by jeffriley** [comment]
I did (briefly) look into creating the pdf file from the LaTex source using github CI/CD last time we taked about this.  I'm confident it can be done.  I'll take some more time and see if I can get it working,

**Comment by ilyamandel** [comment]
So what about the short-term solution of just removing COMPAS_Doc.pdf, COMPAS_CHE.docx, COMPAS_CHE.pdf and updating the getting_started.md documentation to point to the latex documentation, telling the user to compile it?  
Alternatively, we can check in a compiled version and remember that a new .pdf needs to be checked in whenever the latex files change (just like we remember that a new changelog.h needs to be checked in whenever the C++code changes).
