### ISSUE TITLE
Documentation minor issues

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#556]
I can't search the PDF compiled from latex documentation for entries with an underscore -- the PDF file seems to think it's a space.

There is something funny in the DOMINANT MASS LOSS RATE definition:
"Note that this property has the same header string as
. It is expected that one or the other is printed in any file, but not both. If both are printed then the file will
contain two columns with the same header string."

I could not find where the meanings of (SN), (CP), etc. were defined.  We do say the following at the top of Log File Record Specification: Stellar Properties, but I am not sure I would be able to guess that (CP) stands for companion, for example.
 STAR PROPERTY for SSE
 STAR 1 PROPERTY for the primary star of a binary for BSE
 STAR 2 PROPERTY for the secondary star of a binary for BSE
 SUPERNOVA PROPERTY for the exploding star in a supernova event for BSE
 COMPANION PROPERTY for the companion star in a supernova event for BSE

The documentation does not seem to say that Mass(SN) is the mass after the SN.

**Comment by jeffriley** [comment]
> I could not find where the meanings of (SN), (CP), etc. were defined. 

Bottom of page 18 on my copy of the PDF (Section titled "Standard Log File Format)  (Search for 'CP')

I'll take a look at the description of "DOMINANT MASS LOSS RATE"

**Comment by ilyamandel** [comment]
Thanks for the quick fix, @jeffriley , and for the pointer to the definition if (CP) and (SN).  What about
> The documentation does not seem to say that Mass(SN) is the mass after the SN. 
?

**Comment by jeffriley** [comment]
> What about
> The documentation does not seem to say that Mass(SN) is the mass after the SN.

Well, it says (SN) indicates that the property is a property of the supernova - presumably that can only be after the SN event.  We could be more explicit I suppose.

**Comment by ilyamandel** [comment]
Yes, I'd like it to say explicitly that Mass (SN) is the mass of the remnant after the SN (just like TOTAL MASS AT COMPACT OBJECT FORMATION says explicitly that this is the mass at the beginning of (should be "just prior to"?) the SN event).

**Comment by ilyamandel** [comment]
P.S. I'll reopen this issue -- happy to do the above myself (unless someone gets to it first), just not right now.

**Comment by jeffriley** [comment]
Hmmm.  The suffix "(SN)" is added at run-time to any stellar property that is printed for a star that has undergone a SN event.  So we don't just want to say "Mass(SN)" is the mass of the remnant (why would we call out mass specifically and not any other attribute?) - we should expand the description of the suffixes (that any column with a header with a "(SN)" suffix represents an attribute of the the remnant after the SN (and similar statement for the "(CP)" suffix.

The difference with (e.g.) TOTAL MASS AT COMPACT OBJECT FORMATION is that the value for that is actually stored just prior  to the SN event, whereas attributes printed with the "(SN)" suffix (e.g. Mass(SN)) are not stored immediately following the SN event - they are just whatever the value happens to be at the time of printing.  (I know we've talked about this before).

**Comment by ilyamandel** [comment]
Sorry, @jeffriley , I think I missed your comment.  I am happy with the clarification you propose -- should we go ahead with that?

**Comment by jeffriley** [comment]
Sure.  Do you want to update the latex files, or me?  (I don't mind either way)

(edit) Oh - the issue is assigned to me, so I guess I should update the latex files :-)  I'll do it.

**Comment by ilyamandel** [comment]
@jeffriley -- I am not sure this one is fully addressed [see https://compas-docs-readthedocs.readthedocs.io/en/latest/standard-logfile-format.html?highlight=(SN)#standard-log-file-format ] -- but just a tiny tweak to add "any column with a header with a "(SN)" suffix represents an attribute of the the remnant after the SN (and similar statement for the "(CP)" suffix)" as you propose above would do the trick. :)

**Comment by jeffriley** [comment]
@ilyamandel Fixed online (you may need to reload the page).  Let me know if this wasn't what you were thinking.

**Comment by ilyamandel** [comment]
Thanks, @jeffriley !  One more doc update request (aside -- can I update the docs directly?):
at https://compas-docs-readthedocs.readthedocs.io/en/latest/example-compas-run-detailed-output.html,
python3 single_sys_plotter.py
should read
python3 detailed_evol_plotter.py

**Comment by ilyamandel** [comment]
All good (and I now know how to edit the docs myself :) ) -- closing issue, thank you, @jeffriley !
