### ISSUE TITLE
Jupyter notebook to use latest FastCosmicIntegration

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#559]
The relevant Jupyter notebook should be switched to use the now standard FastCosmicIntegration code; once that is done, we can then phase out the no longer maintained (?) older cosmic integration code.

**Comment by themikelau** [comment]
Just labelled this as moderately urgent, as we wish to use this notebook to create the chirp mass distribution plot in the COMPAS methods paper.

**Comment by FloorBroekgaarden** [comment]
Jeff also has the data ready (it seems) we will try to eventually upload this on  the COMPAS Zenodo to go with the data.
