### ISSUE TITLE
in systemParameters merge outcome columns (e.g. "merger") into one OUTCOME column

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#57]
In `constants.h` we define what gets printed in the systemParameters.csv output file: 

In `const ANY_PROPERTY_VECTOR BSE_SYSTEM_PARAMETERS_REC = ` 
the following variables are printed: 

`    BINARY_PROPERTY::UNBOUND,
    BINARY_PROPERTY::STELLAR_MERGER,
    BINARY_PROPERTY::STELLAR_MERGER_AT_BIRTH,
`

make this into one variable: `OUTCOME` which can have the options/outcomes: 
unbound, stellar_merger, stellar_merger_at_birth, DCO, 

and thus contains a quick look-up table for all outcomes of the systemParameters.

**Comment by TomWagg** [comment]
@FloorBroekgaarden do you still want this implemented? It would be good practice for me with learning how to do pull requests and whatnot :)

**Comment by avivajpeyi** [comment]
Hey -- i might take this on today (we are having a COMPAS hackday today) :D

**Comment by ilyamandel** [comment]
Not clear if this is still relevant.  Adding "Won't fix" label -- @FloorBroekgaarden , feel free to remove the label if it's in error.

**Comment by yuzhesong** [comment]
@ilyamandel I'll take a look at this issue as an exercise.

**Comment by ilyamandel** [comment]
Keeping this alive for @yuzhesong . :)

**Comment by ilyamandel** [comment]
I haven't seen any action on this, and it doesn't seem relevant any more since we don't use CSV files, so closing.
