### ISSUE TITLE
If grid file is in a folder that has spaces in the name it breaks

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#573]
**Describe the bug**
If the name of the folder has spaces in the name (for example if someone was in a rush and wrote "helium stars" as the name of the directory instead of "helium_star") then you get an error that says

```
Commandline Options error: option is ambiguous and matches 'PISN-lower-limit', 'PISN-upper-limit', 'PPI-lower-limit', 'PPI-upper-limit', 'add-options-to-sysparms', 'allow-rlof-at-birth', 'allow-touching-at-birth', 'angular-momentum-conservation-during-circularisation', 'black-hole-kicks', 'case-BB-stability-prescription', 'check-photon-tiring-limit', 'chemically-homogeneous-evolution', 'circularise-binary-during-mass-transfer', 'common-envelope-allow-main-sequence-survive', 'common-envelope-alpha', 'common-envelope-alpha-thermal', 'common-envelope-lambda', 'common-envelope-lambda-multiplier', 'common-envelope-lambda-prescription', 'common-envelope-mass-accretion-constant', 'common-envelope-mass-accretion-max', 'common-envelope-mass-accretion-min', 'common-envelope-mass-accretion-prescription', 'common-envelope-recombination-energy-density', 'common-envelope-slope-kruckow', 'cool-wind-mass-loss-multiplier', 'debug-classes', 'debug-level', 'debug-to-file', 'detailed-output', 'eccentricity-distribution', 'eccentricity-max', 'eccentricity-min', 'eddington-accretion-factor', 'enable-warnings', 'envelope-state-prescription', 'errors-to-file', 'evolve-pulsars', 'evolve-unbound-systems', 'fix-dimensionless-kick-magnitude', 'fryer-supernova-engine', 'grid', 'hdf5-buffer-size', 'hdf5-chunk-size', 'initial-mass', 'initial-mass-1', 'initial-mass-2', 'initial-mass-max', 'initial-mass-min', 'initial-mass-power', 'kick-direction', 'kick-direction-power', 'kick-magnitude', 'kick-magnitude-1', 'kick-magnitude-2', 'kick-magnitude-distribution', 'kick-magnitude-max', 'kick-magnitude-random', 'kick-magnitude-random-1', 'kick-magnitude-random-2', 'kick-magnitude-sigma-CCSN-BH', 'kick-magnitude-sigma-CCSN-NS', 'kick-magnitude-sigma-ECSN', 'kick-magnitude-sigma-USSN', 'kick-mean-anomaly-1', 'kick-mean-anomaly-2', 'kick-phi-1', 'kick-phi-2', 'kick-scaling-factor', 'kick-theta-1', 'kick-theta-2', 'log-classes', 'log-level', 'logfile-common-envelopes', 'logfile-definitions', 'logfile-detailed-output', 'logfile-double-compact-objects', 'logfile-name-prefix', 'logfile-pulsar-evolution', 'logfile-rlof-parameters', 'logfile-supernovae', 'logfile-switch-log', 'logfile-system-parameters', 'logfile-type', 'luminous-blue-variable-multiplier', 'luminous-blue-variable-prescription', 'mass-loss-prescription', 'mass-ratio-distribution', 'mass-ratio-max', 'mass-ratio-min', 'mass-transfer', 'mass-transfer-accretion-efficiency-prescription', 'mass-transfer-angular-momentum-loss-prescription', 'mass-transfer-fa', 'mass-transfer-jloss', 'mass-transfer-rejuvenation-prescription', 'mass-transfer-thermal-limit-C', 'mass-transfer-thermal-limit-accretor', 'maximum-evolution-time', 'maximum-mass-donor-nandez-ivanova', 'maximum-neutron-star-mass', 'maximum-number-timestep-iterations', 'mcbur1', 'metallicity-distribution', 'metallicity-max', 'metallicity-min', 'minimum-secondary-mass', 'mode', 'muller-mandel-kick-multiplier-BH', 'muller-mandel-kick-multiplier-NS', 'neutrino-mass-loss-BH-formation', 'neutrino-mass-loss-BH-formation-value', 'neutron-star-equation-of-state', 'orbital-period', 'orbital-period-distribution', 'orbital-period-max', 'orbital-period-min', 'overall-wind-mass-loss-multiplier', 'pair-instability-supernovae', 'population-data-printing', 'print-bool-as-string', 'pulsar-birth-magnetic-field-distribution', 'pulsar-birth-magnetic-field-distribution-max', 'pulsar-birth-magnetic-field-distribution-min', 'pulsar-birth-spin-period-distribution', 'pulsar-birth-spin-period-distribution-max', 'pulsar-birth-spin-period-distribution-min', 'pulsar-magnetic-field-decay-massscale', 'pulsar-magnetic-field-decay-timescale', 'pulsar-minimum-magnetic-field', 'pulsational-pair-instability', 'pulsational-pair-instability-prescription', 'quiet', 'random-seed', 'remnant-mass-prescription', 'revised-energy-formalism-nandez-ivanova', 'rlof-printing', 'rotational-frequency', 'rotational-frequency-1', 'rotational-frequency-2', 'rotational-velocity-distribution', 'semi-major-axis-distribution', 'semi-major-axis-max', 'semi-major-axis-min', 'stellar-zeta-prescription', 'switch-log', 'timestep-multiplier', 'use-mass-loss', 'wolf-rayet-multiplier', 'zeta-adiabatic-arbitrary', 'zeta-main-sequence', and 'zeta-radiative-envelope-giant'`
```

which seems very difficult for people to find.

(Disclaimer: I realise it is crazy to be putting spaces in directory names, but I figured since the error message seems to be completely unrelated it might be good to document this somewhere/throw a better error)

**Label the issue**
`urgency_low`, `severity_minor`

**To Reproduce**
1. Use usual pythonSubmit in `preProcessing`
2. Change directory name to be "pre Processing"
3. Run python submit

**Expected behavior**
Usual run occurs.

**Versioning (please complete the following information):**
 - OS: MacOS 10.15.7 Catalina
 - COMPAS v.02.19.04

**Comment by jeffriley** [comment]
COMPAS code can't fix this - the shell commandline parser uses space as a delimiter, so passes the "broken" parameter to COMPAS - COMPAS has no way of knowing it should "reassemble" the parameter.  The workaround is to put the directory name inside quotes (should work - I haven't tried it, but the commandline parser should pass anything in quotes directly through to COMPAS)

**Comment by jeffriley** [comment]
p.s. The reason for the seemingly strange error message is that because the commandline parse breaks the parameter, it passes "pre" through to COMPAS as the value for the "--grid" option, and then passes "Processing" through as the next option name - the error message comes from the Boost parser, and is trying to indicate that the supplied option name "Processing" is not an exact match for any option name that it knows about, but is ambiguous with the other option names it lists.

**Comment by ilyamandel** [comment]
I suppose a solution to the unclear error message could be to check whether the path or filename, as given in the pythonSubmit file, can be found -- before calling ./COMPAS with the long command line.  This would enable raising a more informative error.

**Comment by jeffriley** [comment]
The bottom line is that this is not a defect - it's just the way the shell parser works, and the way the Boost parser responds.

Wrt the obscure error message (it's actually not so obscure once you know what's happening - an improvement would be to identify the parameter that causes Boost to respond this way), as @ilyamandel suggests, we could put code in the pythonSubmit file to try to catch the problem before it gets to the COMPAS executable.  Boost will emit that message (or one similar) whenever it encounters a parameter it doesn't recognise, so this problem could occur for any parameter that is badly formed (e.g. a stray space, a spelling mistake, etc.).  Checking all parameters in pythonSubmit is not reasonable, but we could (as Ilya suggests) at least check the parameters most likely to have a stray space (the director/file names).  We don't really need to check that the directory/file exists - COMPAS will handle that circumstance ok and emit an error message that is less obscure - we just need to ensure that either there are no spaces in the directory/file name or, if there are, the entire name is enclosed in quotes. (And actually, it may be that the directory/file with a space in the name actually does exist, and I suspect Python will correctly use the full name (with the space(s)) to check if the directory/file exists and determine that it does).

I've changed the label to "enhancement" (and added "good first issue")
