### ISSUE TITLE
Change LBV default wind prescription to HURLEY_ADD

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#580]
In https://github.com/TeamCOMPAS/COMPAS/pull/458, @TomWagg implemented the HURLEY_ADD LBV wind prescription to avoid stars becoming super-Eddington.  We kept the default as BELCZYNSKI for testing / backward compatibility.  Assuming we are OK with keeping defaults for the methods paper, I am putting this down as a future PR *after* the methods paper to change the defaults to HURLEY_ADD.

**Comment by TomWagg** [comment]
Hey @ilyamandel, didn't we do this already in #566?

**Comment by ilyamandel** [comment]
Issue already resolved as pointed out by @TomWagg .  I was confused by the difference between preProcessing/pythonSubmit.py and examples/methods_paper_plots/detailed_evolution/pythonSubmitDemo.py, which I will fix in the next PR.  Closing.
