### ISSUE TITLE
Document code defaults more clearly

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#582]
We have a few cases where pythonSubmit specifies multiple options in which one over-rides the other, e.g., for metallicity vs. metallicity distribution.  Meanwhile, there are a few places in Options.cpp where defaults appear only as defensive programming and will never be used, e.g., m_metallicity is always over-ridden either by a user-specified metallicity on the command line, or by the (default or user specified) metallicity distribution.

In the future, we could improve code documentation to clarify which options will be used and which get over-ridden in the C++ code.  Meanwhile, in pythonSubmit, we could comment out unused options, with a comment that this option exists (and can be modified), but will not be used unless another option is commented out.

**Comment by avigna** [comment]
(Would need to check if the current yaml file implementation of the options partially help with this issue)

**Comment by ilyamandel** [comment]
I think this has mostly been addressed by other changes in the meantime, so labelling "won't fix".

**Comment by ilyamandel** [comment]
Closing since nobody objected to the "won't fix" status. :)
