### ISSUE TITLE
Inconsistent columns/headers in SSE_Supernova

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#585]
**Describe the bug**
When running COMPAS in SSE mode, I find a mismatch between the headers and the values listed in SSE_Supernova (command line to reproduce below).

The output header has 15 columns, but there are only 14 values.  This leads to some variables being matched to the wrong header. For example, I have Stellar_Type_Prev = 7.11 (stellar type should be an integer, I believe this is a core mass).

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Using the latest COMPAS version

Run:
./COMPAS --initial-mass 20.0 --mode SSE -z 0.01 -n 1 --logfile-type CSV

and then inspect

COMPAS_Output/SSE_Supernovae.csv 

**Expected behavior**
The number of columns and headers should match, values should match their header.

**Versioning (please complete the following information):**
 - OSX 10.14.6
- COMPAS v02.20.00

**Additional context**

**Comment by jeffriley** [comment]
I've identified the problem - I'll push a fix later tonight or tomorrow.

**Comment by jeffriley** [comment]
Defect introduced in v02.18.00 - seems I may have been a little over-zealous with some code-cleanup...  Problem only affected SSE_Supernovae logfile.

Fixed in PR #587, COMPAS v02.20.21
