### ISSUE TITLE
Strange behavior in BSE_RLOF and BSE_Common_Envelopes

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#593]
**Describe the bug**
In the BSE_RLOF output file, the parameter 'CEE' appears to not be working correctly. From the documentation, CEE is a  "Flag to indicate if the RLOF leads to a common-envelope event". This also agrees with what I would expect. However, it is sometimes incorrectly set to false when there is a CEE event, identified by an entry in the BSE_Common_Envelopes output. After further digging, the issue might be larger than a mislabeled 'CEE' output param, and could be that we are incorrectly flagging RLOF and CEE events. 

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
The following system, run in the command line on COMPAS v02.20.01, should correctly reproduced the buggy behavior.

`COMPAS  --initial-mass-1 23.693497 --initial-mass-2 1.531993 -a 0.146744 --random-seed 5000014`

You can then see that there is an entry in the Common_Envelopes output, and one in the RLOF output. They occur at the same time, but the RLOF param 'CEE' is set to 0. However, I'm looking through the rest of the output, and I don't understand why output was recorded at all. None of the parameters change before and after the event (masses, rochelobe radii). The stellar radii grow in the RLOF file, but then the final radii are used as the before and after radii in the Common_Envelope file. 

**Expected behavior**
I'm not entirely sure. If this is a false MT/CE event, it should not be in the output. If it is, it should be recorded consistently, but there should also be more changes in the stellar parameters before and after the event. 

**Versioning (please complete the following information):**
 - COMPAS v02.20.01

**Comment by jeffriley** [comment]
@themikelau

**Comment by reinhold-willcox** [comment]
[COMPAS_Output.h5.txt](https://github.com/TeamCOMPAS/COMPAS/files/6812688/COMPAS_Output.h5.txt)

@themikelau Github says it doesn't accept h5 file uploads, so I've added a txt extension, but you should be able to just rename it after downloading. Let me know if that doesn't work. There's just a single system in it, so it's pretty small.

**Comment by reinhold-willcox** [comment]
@themikelau @jeffriley All good, I've sorted this out.

If the RLOF results in a merger, an entry is always made in the CE output. However, for CE entries resulting in mergers, sometimes the stellar parameters are unchanged in the CE file (hence my confusion above), but this is probably because a lot of these parameters won't have sensible values post merger. 

Note that even though the RLOF resulting in merger produced an entry in the CE file, the CEE parameter in BSE_RLOF is not always flagged. I believe if the RLOF was stable, it is not considered to be a formal CE event, though perhaps conceptually this is wrong and a merger should always be considered a CE? 

At any rate, for my purposes (i.e ignoring merger products), the CEE boolean is sufficient.
