### ISSUE TITLE
Minor fixes to the RLOF output

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#594]
In the BSE_RLOF output, the parameters for stellar type are named "Type(1)", "Type(1)_Prev", etc. They appear to function correctly, but in other outputs, this parameter is "Stellar_Type(SN)" etc. My understanding of these parameters is that if they represent the same thing, they derive from the same quantity and should be named using the same roots. This suggests to me that the BSE_RLOF parameters may derive from a different quantity. 

@jeffriley Could you check this? It's probably inconsequential, but it would be better to maintain consistency.

**Comment by jeffriley** [comment]
"Type(1)", "Type(1)_Prev", etc. are strings in the BINARY_PROPERTY_DETAIL map defined in constants.h.  The maps

ANY_STAR_PROPERTY_DETAIL
BINARY_PROPERTY_DETAIL
PROGRAM_OPTION_DETAIL

define the header string, units string, and field width, for the properties being printed (for single stars, binary stars, and program options, respectively).

> My understanding of these parameters is that if they represent the same thing, they derive from the same quantity and 
> should be named using the same roots. This suggests to me that the BSE_RLOF parameters may derive from a different 
> quantity.

Whoever writes code and adds variables exposed for selection for printing puts the variable and details in the appropriate map (from the list above), so the names are not automatic (the only automatic part is the addition of the suffix for each variable as the suffix relates to the primary or secondary star (i.e suffix (1) or (2)), or supernova or companion star (i.e. suffix (SN) or (CP)).

You're right - in this case the BSE_RLOF parameters are not the same variables as the individual stars' stellar type variables.  (It kind-of is the same variable, but it's a stored copy of the same variable...).

Even though it makes sense for all variables that allow users to print (e.g.) the stellar type to have the same header string (so in this case, the variable BINARY_PROPERTY::RLOF_CURRENT_STAR1_STELLAR_TYPE currently has the header string "Type(1)" in the BINARY_PROPERTY_DETAIL map, but maybe we should change it to "Stellar_Type(1)"), there's a problem (that is evident with some variables already - I've tried to flag all of those affected in the documentation).

In this case, there is nothing preventing users from printing (say) ANY_STAR_PROPERTY::STELLAR_TYPE and BINARY_PROPERTY::RLOF_CURRENT_STAR1_STELLAR_TYPE in the same output file - if they do that, and the single star is the primary of the binary, then both those columns would have the same header string ("Stellar_Type(1)"), and not only would that confound the HDF5 code, it would also confound any human looking at the output file if a human-readable output file was produced (.csv, .tsv, etc.).

So we could change the header string to something that includes "Stellar", but we have to be careful that variables (and so output file columns) don't have the same header strings.  Harking back to earlier discussions, we could define variables to have different header strings for different output files (not hard to do, but tedious (there are a lot of variables that can be selected for printing - we'd have to decide on output file-specific header strings for each of them, then type them into constants.h)).

**Comment by reinhold-willcox** [comment]
Thanks Jeff. Sounds like the solution is complicated enough, and the issue minor enough, that we should just leave this as is. If you agree, let's close this issue.

**Comment by jeffriley** [comment]
Agreed - let's close it
