### ISSUE TITLE
Implement ECSN fixes from my kicks paper

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#596]
**Is your feature request related to a problem? Please describe.**
We should implement the ECSN fixes proposed in my NS kicks paper (arxiv:2107.04251). 

**Describe the solution you'd like**
In the paper, we propose that the ZAMS mass range for ECSN progenitors should be reduced to below 0.2Msol, but this is not that practical to implement directly in COMPAS because we don't trigger ECSNe based on the ZAMS mass. The simplest reasonable solution is to adjust the trigger for ECSN to account for previous MT events (or simply H env mass). 

For stripped progenitors which _should_ go ECSN, we can play with the values of e.g Mcbur1,2 and see how that affects predictions for DNS merger rates. That aspect might be worth a follow up (mini) paper, perhaps around the time of the O3b data release to better compare with any updated rates from the LVK gang. 

**Describe alternatives you've considered**
Leave things as is, I guess?

**Comment by ilyamandel** [comment]
Suggestion:
add a new option (something like noECSNinSingleStars); if that option is set, check if a star that goes into the ECSN branch has a hydrogen envelope, and if it does, it stays a WD, avoiding an ECSN.

**Comment by ilyamandel** [comment]
Addressed in #795 , closing.
