### ISSUE TITLE
Documentation upgrade

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#614]
**Is your feature request related to a problem? Please describe.**
The documentation is a bit clunky in its current form, as a dry pdf document hidden away in an obscure git branch. It is difficult to navigate, especially for strings containing underscores (i.e most variable names). Many public codes use markdown-based websites which make navigating/reading/updating the documentation *much* easier. 

An example of this format done well is the OzStar User Guide: https://supercomputing.swin.edu.au/docs/

A caveat to this change is that we would like the documentation to be updated in parallel with the code changes, which is why it's useful to have the current Latex files in the broader Compas repo. Any solution using a markdown-based website should continue to store the markdown source code in the Compas repo.

This is not a high priority, but I think it would help a lot to increase the Compas user base.

**Comment by ilyamandel** [comment]
I think this is addressed with @jeffriley's readthedocs -- see compas.science/docs -- so closing this.
