### ISSUE TITLE
BSE_RLOF output SEED parameter name bug

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#621]
**Describe the bug**
Another really small, almost cosmetic bug (sorry for being so picky). In the BSE_RLOF output, the `SEED` parameter has recently been renamed to `SEED>MT`. Many of the other parameters have been renamed similarly to more clearly signify if they apply >MT or <MT, but the SEED parameter doesn't really fit into that mold, and should be renamed back to just `SEED`. 

Jeff, I'm happy to fix this, though I may ping you later if I need some guidance.

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**Versioning (please complete the following information):**
 - COMPAS v02.22.00

**Comment by jeffriley** [comment]
I think that's reasonable.  I suspect the '>MT' was meant to signify that the value comes from the post-MT RLOF props.  Even though we record the random seed in the pre-MT RLOF props, we don't expose it for printing (and even if we did it would be the same seed).

The only problem with changing the header to just "SEED", is that if someone decides they want to add the BINARY_PROPERTY::SEED to the RLOF file, then it already has the header "SEED", so you'd end up with two columns with the same header - and that would confused hdf5.  You might say "Don't do that", but if we can help people not shoot themselves in the foot, we should.  What about calling the seed from the post-MT RLOF props "RLOF-SEED" or something?

Whatever you decide, the change needs to be made to this entry in the 'BINARY_PROPERTY_DETAIL' map in constants.h:

    { BINARY_PROPERTY::RLOF_POST_MT_RANDOM_SEED,   { TYPENAME::ULONGINT,   "SEED>MT",   "",   12, 1 }},

**Comment by reinhold-willcox** [comment]
I just swapped out the MT specific parameter for BINARY_PROPERTY::SEED, and deleted the original. You are right, there are a few other parameters that seem to have been "pre or post Mass Transfer"-ized, without any real reason to do so - there was a star ID one as well - but I didn't change those in case there are other compelling reasons to keep them that I couldn't think of.

**Comment by jeffriley** [comment]
@reinhold-willcox Reviewed - suggested some changes.  Further to those suggestions, and pertaining to the star ID property you mention above, the 

OBJECT_ID id

variables in both the RLOFProperties and the BeBinaryProperties structs in typedefs.h were probably included for debugging (the object id is only ever used for debugging).  You can safely remove those - and the corresponding code that stashes them, and any code that refers to RLOF_POST_MT_ID, BINARY_PROPERTY::RLOF_POST_MT_ID,  BE_BINARY_CURRENT_ID, or BINARY_PROPERTY::BE_BINARY_CURRENT_ID (constants.h and BaseBinaryStar.cpp).

As for any other superfluous variables ("other parameters that seem to have been "pre or post Mass Transfer"-ized") in the RLOFProperties struct (and, for that matter, the BeBinaryProperties struct) - I don't know.  Coen wrote the RLOF file code originally I think (in the legacy code), and maybe @serenavinciguerra89 wrote the BeBinaries file code.  We did take the RLOF code out at one stage - @themikelau put it back in, but I think he pretty-much just reinstated what was removed.  So, as far as what's required and what's superfluous, I imagine your guess is as good as anybody's for the RLOF stuff, and maybe talk to Serena about the BeBinaries stuff.
