### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#626]
Update documentation links throughout to point to https://compas.science/docs, and update the blurb below to point to the methods paper:

Please also kindly include citations to the two following papers:
Stevenson S., Vigna-Gómez A., Mandel I., Barrett J. W., Neijssel C. J., Perkins D., de Mink S. E., 2017, Nature Communications, 8, 14906
Vigna-Gómez A., Neijssel C. J., Stevenson S., Barrett J. W., Belczynski K., Justham S., de Mink S., Müller B., Podsiadlowski Ph., Renzo M., Szécsi D., Mandel I., 2018, MNRAS, 481, 4009
We anticipate releasing a more detailed and comprehensive methods paper in the future.

**Comment by ilyamandel** [comment]
Partially addressed by @FloorBroekgaarden in #627 .

**Comment by themikelau** [comment]
Do we still wish to have separate links in the README to
* Getting started
* Specifications
* Post-processing
* Running COMPAS inside a Docker container
in readthedocs

Or a single "Documentation" link to https://compas.science/docs?

**Comment by ilyamandel** [comment]
@themikelau -- a single link is probably sufficient; what do you think?
