### ISSUE TITLE
Output parameter name / value consistency

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#631]
Some of the output parameter names could be improved, some for consistency with other parameter names, and some which are misleading to the point of being incorrect.

The following lists some of the improvements I've noticed, but it is not necessarily complete.
- We should decide on and stick to a convention for whether to put the the chronology indicator (e.g <MT, @CE) before or after the star indicator (e.g (1), (SN)). This is mostly adhered to, but e.g Mass(1)<CE and (2) do not align with the rest. 
- We should ensure that if a chronology indicator shows up for a parameter in one output file, it should be there in all the output files. So all Mass parameters should have chronology indicators. Probably the event counter parameters do not need them. 
- In the CE output, the parameter "CoreMass(1)" and (2) are incorrectly labelled. The underlying parameter is "Mass_1_Final", which is very ambiguous and should be renamed more carefully. Also, this value is incorrect when the star has no core - the CoreMass then takes on the full mass value, which is arguably incorrect. 
- RLOF has preMT time and postMT time, but they appear to always be the same (to within the precision of the output). We should probably scrap the preMT time, unless the duration of the MT is desired, in which case we should calculate that internally and output that (to avoid float precision issues).

**Comment by ilyamandel** [comment]
@reinhold-willcox : I think this has mostly been addressed.  I'd like to avoid further changes unless absolutely necessary, since they break post-processing codes (and once the codes are updated, they can't be used to parse older results unless multiple versions of post-processing codes are stored, which is a mess).  Can I close this issue?

**Comment by reinhold-willcox** [comment]
With exception of the RLOF time parameters, I think the rest of these are resolved. Happy to close.
