### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by ryosuke-hirai** [TeamCOMPAS/COMPAS#632]
In the "Getting Started" section of the documentation, there are several inconsistencies with what is provided.
1. In section 2.2, it says that a script called `single_sys_plotter.py` is provided. But what is provided is called `detailed_evol_plotter.py`
2. Same section, the default grid file provided in `examples/methods_paper_plots/detailed_evolution` does not reproduce the plot shown. Instead, it disrupts the binary upon the first BH formation. This may be a code bug instead of documentation issue.
3. I also suggest adding `h5py` as one of the required packages for plotting using the provided scripts.

This was observed in v 02.22.01

**Comment by ilyamandel** [comment]
Items 1 and 2 addressed in #633 ; I accidentally omitted 3 -- but it's now staged in PR #628 , so closing this issue.
