### ISSUE TITLE
Change default treatment of immediateRLOFPostCEE and optimisticCE

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#637]
At the moment, on immediateRLOFPostCEE (RLOF immediately after CE) and optimisticCE (CE from radiative-envelope donor), we just record the appropriate flags and continue with evolution as if the binary survived the CE.  However, this has two problems:

1. If we want to implement the treatment of mergers (see #209 ), this is no longer a flag issue, but an actual bifurcation in the binary's evolution, and we have to make a decision on whether to treat this as a merger event or a surviving binary event.  

2. Many beginning users or users of our zenodo outputs don't realise that they need to take out binaries with such flags (I've had to explain this to a number of people recently).

I therefore propose adding two additional flags to pythonSubmit / command-line calls, AllowImmediateRLOFPostCE and AllowRadiativeDonorsSurviveCE .  Both flags would be set to false by default, which would treat such systems as mergers and discontinue future evolution.  If the flags are set to true, we would follow the current behaviour (still recording the flags as now).  

Since this is a change in default behaviour, I'm opening a one-week comment period before implementing this.

**Comment by ashruiter** [comment]
This seems completely reasonable!

**Comment by ilyamandel** [comment]
Closed with PR #674 .
