### ISSUE TITLE
WD accretion prescription

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#638]
We do not currently have a sensible prescription for accretion onto WDs.  We could, of course, implement the prescription from Hurley+, 2002, section 2.6.6, steady accretion onto degenerate objects -- see below -- but now that we have experts @ashruiter and @solfreludio on board, let's do this right!  What should we do, in order to avoid 2+ solar mass HeWDs as in #605 :

> ./COMPAS --initial-mass-1 6.89589578359158 --initial-mass-2 2.01573020843856 --number-of-systems 1 --random-seed 3329 --semi-major-axis 1.10640324835946 --eccentricity 0  --detailed-output TRUE --timestep-multiplier 0.01

![image](https://user-images.githubusercontent.com/512213/135796921-f0a4b40d-f86d-4517-97a0-bbeccd842b95.png)

**Comment by ilyamandel** [comment]
(See related issue #512 )

**Comment by ashruiter** [comment]
@ilyamandel and @solfreludio - A more modern/better prescription should also take mass transfer rate (not just mass accreted) into account. I don't think I have anything exceptional to suggest at the moment but let me dig around a bit and I'll get back to you soon!

**Comment by ilyamandel** [comment]
Given the ongoing (and almost complete) work by @solfreludio , I am closing this issue.
