### ISSUE TITLE
MCBUR[12]

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#655]
The MCBUR1 and MCBUR2 parameters are ambiguous. It's not clear, from the code or from knowledge of the Hurley papers, why they are named this way. They correspond to the bounds on the AGB core mass between which the CO core is partially degenerate. It would be useful to come up with clearer names for these parameters.

Separately, only MCBUR1 is an input option, but MCBUR2 should be added as an option as well.

**Comment by ilyamandel** [comment]
While MCBUR1 and MCBUR2 are not explicitly defined in Hurley et al., 2000 (though see, e.g., second paragraph of section 6), but they are defined in Fryer+, 2011 (see section 4).  

We do have some comments on this -- e.g., 

Options.cpp:    m_mCBUR1                                                        = MCBUR1HURLEY;                                         // MHurley value, Fryer+ and Belczynski+ use 1.83

I agree that the comments need to be clarified (and the typo above should be fixed), and am fine with adding MCBUR2 as a command line option, but I don't think we need to come up with new names.

**Comment by reinhold-willcox** [comment]
I'm happy with that

**Comment by ilyamandel** [comment]
I fixed the comment typo, but it's not clear whether anyone is planning to use MCBUR2 as an option, so I am happy to leave that to whoever actually needs it.  Closing.
