### ISSUE TITLE
/bin/sh: 1: Permission denied | pythonSubmitDemo.py

### ISSUE THREAD

**Issue by HeloiseS** [TeamCOMPAS/COMPAS#665]
_This issue is submitted as part of the JOSS review [#3838](https://github.com/openjournals/joss-reviews/issues/3838)_

### :bug: Description and fix attempts
I don't seem to be able to run `pythonSubmitDemo.py` - I have now set my `$COMPAS_EXECUTABLE_PATH` (maybe i did it wrong?)

```
python_version = 3
compas_executable_override None
/home/fste075/COMPAS/src/COMPAS
[...]
/bin/sh: 1: /home/fste075/COMPAS/src/COMPAS: not found
```
I have tried setting my environement variable to `/home/fste075/` and removed the `src/` on line 39 of but i then get a `/bin/sh: 1: /home/fste075/COMPAS: Permission denied` error.  I performed an aggressive chmod 777 on the COMPAS directory, to no success.

**Label the issue**
`urgency_low`   
`severity_minor`  ?

**Versioning (please complete the following information):**
 - OS: Ubunutu 20.03
 - COMPAS v02.21

### Further comment / question
On inspecting the code to check where `compas_executable` was being used i realised that there is no `__init__` method for that class(which isn't  :sparkles: _stricktly_ :sparkles:  necessary but good form)  and I am a little confused about the overall construction. For example, why is the following method not a class attribute instead or an @property ? 
```
def stringCommands(self):
        stringCommands = [
            '--mode',
            '--case-BB-stability-prescription',
            '--chemically-homogeneous-evolution',
            '--luminous-blue-variable-prescription',
            '--mass-loss-prescription',
            '--mass-transfer-angular-momentum-loss-prescription',
            '--mass-transfer-accretion-efficiency-prescription',
            '--mass-transfer-rejuvenation-prescription',
            '--initial-mass-function',
            '--semi-major-axis-distribution',
            '--orbital-period-distribution',
            '--mass-ratio-distribution',
            '--eccentricity-distribution',
            '--metallicity-distribution',
            '--rotational-velocity-distribution',
            '--remnant-mass-prescription',
            '--fryer-supernova-engine',
            '--black-hole-kicks',
            '--kick-magnitude-distribution',
            '--kick-direction',
            '--output-path',
            '--output-container',
            '--common-envelope-lambda-prescription',
            '--stellar-zeta-prescription',
            '--mass-transfer-thermal-limit-accretor',
            '--pulsational-pair-instability-prescription',
            '--neutron-star-equation-of-state',
            '--pulsar-birth-magnetic-field-distribution',
            '--pulsar-birth-spin-period-distribution',
            '--common-envelope-mass-accretion-prescription',
            '--envelope-state-prescription',
            '--logfile-name-prefix',
            '--logfile-type',
            '--logfile-definitions',
            '--grid',
            '--logfile-common-envelopes',
            '--logfile-detailed-output',
            '--logfile-double-compact-objects',
            '--logfile-pulsar-evolution',
            '--logfile-rlof-parameters',
            '--logfile-supernovae',
            '--logfile-switch-log',
            '--logfile-system-parameters',
            '--neutrino-mass-loss-BH-formation'
        ]
   return stringCommands
```

**Comment by HeloiseS** [comment]
### UPDATE

I found the problem haza! - my initial env variable was correct but **I missed another step** - the Build COMPAS step to be precise, which indeed is rather essential. 

The demo runs great (haven't check outputs yet tho) - I have but one request based on this experience: 
**Could you put the steps to install + demo instructions on 1 single page?** If the install recipe was a top-to-bottom read it would harder to forget a step.

From looking at your menu, it all looks in the right order (and all the instructions are clearly there) but for some reason your subsections are 1) individual pages i need to click through and 2) some of them are hidden (I guess it's based on the number of levels you choose to display at once). The 'Build COMPAS' was hidden under dependencies - and naively i thought that referred to the packages needed for the code to work (e.g. numpy), not something I **had to do** to complete the install -- so i didn't click that link until much later in the debugging process. 

You could take all the "Getting started" material, stick the demo to end of it, and have it as one big Quick Start/Install recipe, at the end of which you can direct the n00bs to the User Guide once they've successfully run the default demo once (so they know the code works) to modify the demo and properly understand it :)

**Comment by jeffriley** [comment]
Thanks @HeloiseS.

> Could you put the steps to install + demo instructions on 1 single page?
> If the install recipe was a top-to-bottom read it would harder to forget a step.

We have different install instructions for different OSes, so putting the install instructions + demo on a single page would mean we either have install instructions for (say) Linux and MacOS on the same page, or we have different OS install pages and repeat the common content (e.g. the demo).  Not sure what's best there.  These online docs are fairly new, and we're still to go through them as a group and figure out the best presentation - but we will do that.

In the meantime I've brought the "Building COMPAS" page up a level - you're right, it shouldn't be buried in the dependencies - and I've added some text and links at the bottom of the "Getting started" page so users can jump straigh to the tutorial.

> On inspecting the code to check where compas_executable was being used i realised that there is no __init__ method 
> for that class(which isn't ✨ stricktly ✨ necessary but good form) and I am a little confused about the overall 
> construction. For example, why is the following method not a class attribute instead or an @Property ?

I don't know :-)  I don't actually use pythonSubmit.py very much - I usually run COMPAS from the command line.  pythonSubmit.py was written a long time ago (maybe by @SimonStevenson?), so someone more familiar with it might be able to tell you.

pythonSubmit.py could do with a tidy-up - I think it has grown over the years.  I could tidy-up the code, but I think it's better that someone who uses it more than I do should look at the structure - maybe we could reorder the variables/options so they're a bit easier to find.  I'll raise the issue with the group.

**Comment by ilyamandel** [comment]
The instructions at https://compas-docs-readthedocs.readthedocs.io/en/latest/example-compas-run.html have been clarified, with "This tutorial assumes that you have already built the COMPAS executable as described in [Building COMPAS](https://compas-docs-readthedocs.readthedocs.io/en/latest/building-COMPAS.html)." added as a first sentence.

**Comment by HeloiseS** [comment]
@jeffriley THANKS!

> pythonSubmit.py could do with a tidy-up - I think it has grown over the years. I could tidy-up the code, but I think it's better that someone who uses it more than I do should look at the structure - maybe we could reorder the variables/options so they're a bit easier to find. I'll raise the issue with the group.

I know @ilyamandel  is a little reluctant but i literally have it tidied up already so i can just send you my version and you can take a look - it would take you no time at all :)
