### ISSUE TITLE
Add detailed RLOF output

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#67]
Similar to what Coen worked on in legacy COMPAS; merge with CE

**Comment by jeffriley** [comment]
@ilyamandel @FloorBroekgaarden @themikelau @cneijssel @serenavinciguerra89 

Issue https://github.com/TeamCOMPAS/COMPAS/issues/212 was recently closed when @themikelau re-implemented RLOF printing.

We still have issue https://github.com/TeamCOMPAS/COMPAS/issues/51 open, and this issue.

What's the plan?

**Comment by ilyamandel** [comment]
This was an issue that was added when we were preparing for public release.  I agree that it duplicates #212 , which has now been closed, so I am also closing this one.
