### ISSUE TITLE
Check if sampling through grid.txt and through main pythonSubmit gives the same output

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#68]
for the same initial binaries that sampled. 

At least the binaries that are rejected in pythonSubmit sampling (e.g. because of RLOFonZAMS==1) should consistently being rejected in `Grid.txt`

**Comment by ilyamandel** [comment]
@FloorBroekgaarden -- is this an actual issue?  If not, suggest closing it.

**Comment by ilyamandel** [comment]
@FloorBroekgaarden -- since there have been no comments on this issue for a very long time, and no evidence of problems, I am closing it.
