### ISSUE TITLE
[DOCS] 1_Slicing_Data.ipynb  | KeyError: "Unable to open object 

### ISSUE THREAD

**Issue by HeloiseS** [TeamCOMPAS/COMPAS#682]
_This issue is submitted as part of the JOSS review [#3838](https://github.com/openjournals/joss-reviews/issues/3838)_

### :bug:  description
I got a `KeyError: "Unable to open object (object 'DoubleCompactObjects' doesn't exist)"` on cell 5, evidently because the COMPAS_Ouptut file i generated with one of my test runs does not have double compact objects. 

### Recommendation
This notebook has some untold expectations of the output to process - I recommend the developers choose one output example and provide a link to it for the user to run this notebook with. I did see the link to the general compas website to download data, but as a new user  (and not knowing what the notebook expects) I wouldn't know what to chose to ensure proper running. 

**Note**
@ilyamandel @jeffriley, If i encounter other issues in the jupyter notebooks/tutorials would you like me to collate them in this issue or make new ones for each?

**Comment by HeloiseS** [comment]
I looked a little further down the notebook and I don't think it'll run with outputs form COMPAS v2.25 
I'm seeing `Data['SystemParameters']['Mass@ZAMS_1'][()]` and I my output data has the key `Mass@ZAMS(1)`.

When did the keys changes? It's worth thinking about having a warning somewhere in the guide in case someone learns with new compas and then downloads and tries to use data generated a while back. 

----

**Wait a minute my jupyter notebooks don't match the read the docs!** - I think I have some old files. Looking [here](https://github.com/TeamCOMPAS/COMPAS/tree/dev/postProcessing/Folders/BasicsPython) I can see the ones i downloaded from the release branch were made 2 years ago! There it is ;) 

Please update the release branch with the up to date notebooks, adding a link to the data you want me to use :) I'll give them another try then.

**Comment by jeffriley** [comment]
I'll defer here to @reinhold-willcox, @themikelau, @cneijssel etc. (I don't know who else...).  I don't do Jupyter notebooks.  It could very well be my meddling trying to get them into the online docs that caused the problems Heloise is seeing...

**Comment by reinhold-willcox** [comment]
Thanks @HeloiseS for pointing this out. Updating the notebooks has been one of the "back-burner" priorities for a while now. As has adding them to a CI check to make sure we catch it sooner if they go out of date again.

I'll go through them now and try to clean them up.

**Comment by jeffriley** [comment]
> I'll go through them now and try to clean them up.

@reinhold-willcox I've copied the notebooks to the online documentation - so in docs/online-docs/notebooks

I tidied them up a little - mainly just rewording and/or reformatting some of the text(I tried to make headings uniform, etc.), but also some of the paths to files.  I'm not a notebooks user, so I might have inadvertently broken something (though they all seem to run if you go through the online docs versions).

**Comment by reinhold-willcox** [comment]
Thanks @jeffriley. I'm doing some other more involved changes to clean them up, but I'll remember add those to the website when they're done.

**Comment by ilyamandel** [comment]
@reinhold-willcox -- status ping :)

**Comment by reinhold-willcox** [comment]
@ilyamandel still working slowly through these, sorry for the delay
