### ISSUE TITLE
h5view.py -- Error accessing HDF5 file -- 'Resource temporarily unavailable'

### ISSUE THREAD

**Issue by HeloiseS** [TeamCOMPAS/COMPAS#683]
_This issue is submitted as part of the JOSS review [#3838](https://github.com/openjournals/joss-reviews/issues/3838)_

### :bug: description
I was trying to run the `h5view.py` utility on a test output and i got the following error. It happened both when i called the script from a separate directory and when after I copied the script to my working directory. 
 
```
Error accessing HDF5 file /home/fste075/Documents/reviews/COMPAS/COMPAS_Output/COMPAS_Output.h5 : Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```
**Versioning (please complete the following information):**
 - OS: [e.g. Ubuntu 20.02]
 - COMPAS [e.g. v02.25.03]

**Comment by jeffriley** [comment]
It could be that the file is currently open and being accessed by another process (even though you should be able to open it for read access, I think h5py complains about it). 

Can you access it with h5dump (comes with hdf5 if you have that installed)?

**Comment by HeloiseS** [comment]
oops yes - i had it open in jupyter, forgot about that. 

Changed the title of the issue so if someone gets the same error not knowing what it means they can find this :)
