### ISSUE TITLE
Check for merger during mass transfer episode

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#70]
From @serenavinciguerra89 

To check whether both stars fit within the binary at all 'timesteps' during a mass transfer episode.

Since these stars are not in equilibrium, we don't know their 'real' radii. But we can at least make some guess as to what their radii are. 

Options include:

1) check that both stars fit in the orbit at all times based on their initial radii
2) check that both stars fit in the orbit at all times based on their final radii
3) check that both stars fit in the orbit at all times assuming their largest radii (pessimistic)
4) check that both stars fit in the orbit at all times assuming their smallest radii (optimistic)

I favour 1) for simplicity.

**Comment by avigna** [comment]
I guess we could add a `contact_during_mass_transfer` flag and set it to true if it occurs.

**Comment by ilyamandel** [comment]
The trouble with option 1 is that a star may be stripped of its envelope during a MT episode.  We don't necessarily expect the entire initial star to fit in, just the final star, which would suggest using option 4 from @SimonStevenson 's list.  However, that radius is typically not available during MT itself, as the stars haven't yet been adjusted in the code, i.e., the check must happen later.

Another challenge is that we do allow for contact binaries at ZAMS now, as part of CHE modelling.  So it's not as simple as disallowing all binaries that overflow RLOF at the end of the MT episode, even if we do use final radii.

I am still looking for an elegant solution (this is also connected to Issue #306 ).

**Comment by ilyamandel** [comment]
As mentioned above, we do not keep track of the detailed stellar evolution during mass transfer.  Therefore, we can only require that stars do not overfill their Roche lobes immediately after a mass transfer episode.  However, even that is allowed: e.g., we do allow for stars to overfill Roche lobes after a common-envelope event, and we do allow stars to be long-term over-contact in the context of CHE evolution.  Therefore, the only requirement we can reasonably make is that stars should not be "touching" right after a mass transfer episode -- which is really a rough proxy for L2 overflow, which we assume leads to merger.  This is the check I've implemented in PR #343 .  I am therefore closing this issue.

[@serenavinciguerra89 and @SimonStevenson -- if you have specific proposals that can be realistically implemented within the context of COMPAS, please feel free to open a new issue with such a proposal.]
