### ISSUE TITLE
Timestep calculation in SSE code could result in timesteps smaller than expected

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#704]
**Describe the bug**
The BaseStar function CalculateTimestep() is used to calculate the duration of the timestep for stellar evolution:

    double BaseStar::CalculateTimestep() {
    
        // the GBParams and Timescale calculations need to be done
        // before the timestep calculation - since the binary code
        // calls this functiom, the GBParams and Timescale functions
        // are called here
    
        CalculateGBParams();                                                                // calculate giant branch parameters
        CalculateTimescales();                                                              // calculate timescales
    
        double dt = ChooseTimestep(m_Age);
    
        return LimitTimestep(dt);
    }

The virtual function ChooseTimestep() returns a timestep clamped to a minimum value of NUCLEAR_MINIMUM_TIMESTEP (currently set to 0.0001 in constants.h).

The BaseStar::LimitTimestep() function was added to limit the mass change in any single timestep to 1% of the star's mass:

    /*
     * Limit timestep to 1% mass change
     *
     *
     * double LimitTimestep()
     *
     * @return                                      Timestep
     */
    double BaseStar::LimitTimestep(const double p_Dt) {
    
        double dt = p_Dt;
    
        // cap timestep to maximum of MAXIMUM_MASS_LOSS_FRACTION change in mass star.
        if (OPTIONS->UseMassLoss()) {
            double mDot     = CalculateMassLossRate();                                          // First, calculate mass loss rate
            double massLoss = CalculateMassLoss_Static(m_Mass, mDot, dt);                       // Next, calculate mass loss - limited to (mass * MAXIMUM_MASS_LOSS_FRACTION)
    
            if (utils::Compare(massLoss, 0.0) > 0) {                                            // No change if no mass loss
                double dtWind = massLoss / (mDot * 1.0E6);                                      // Calculate timestep to match (possibly limited) mass loss
                       dt     = min(dt, dtWind);                                                // choose dt
            }
        }
    
        return dt;
    }

The issue is that LimitTimestep() is called after ChooseTimestep(), so the timestep returned by CalculateTimestep() could be lower than NUCLEAR_MINIMUM_TIMESTEP.

Is that correct behaviour, or should we clamp the value returned by BaseStar::CalculateTimestep() to a minimum NUCLEAR_MINIMUM_TIMESTEP by changing the return statement thus:

    return std::max(LimitTimestep(dt), NUCLEAR_MINIMUM_TIMESTEP);

And if we make that change, should we remove the clamps in the ChooseTimestep() functions, or leave them there for safety?  The only place in the code ChooseTimestep() is called is BaseStar::CalculateTimestep(), but I don't know that we can guarantee that will always be the case, so maybe leaving the clamps in ChooseTimestep() is prudent, though redundant as the code now stands.

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Run COMPAS in SSE mode and check timestep durations

**Expected behavior**
The SSE timestep calculation should be consistent with expectations (i.e if we are expecting the timestep duration to be clamped to some minimum value, it should be).

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Ubuntu 20.04
 - COMPAS v02.25.09

**Additional context**

**Comment by ilyamandel** [comment]
I agree with both suggestions, but would also change NUCLEAR_MINIMUM_TIMESTEP down to 1 yr (from current 100 yrs) for safety.

**Comment by jeffriley** [comment]
Fixed in PR#707
