### ISSUE TITLE
Timestep calculations in SSE and BSE code could produce inconsistent results when comparing BSE to SSE

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#705]
**Describe the bug**

In the SSE code, the first order timestep calculation is performed by BaseStar::CalculateTimestep().  The timestep calculated by BaseStar::CalculateTimestep() is multiplied by the timestep multiplier specified by the user (via the --timestep-multiplier program option), and clamped to a minimum value of NUCLEAR_MINIMUM_TIMESTEP (currently set to 0.0001 in constants.h) (or should be - see issue #704).

The SSE evolution driver code (the code that steps through the evolutionary process timestep-by-timestep to determine the attributes of the star as it ages) calls the function Star::EvolveOneTimestep() for each iteration of the loop (i.e. every timestep) until evolution stops.

Star::EvolveOneTimestep() calls Star::AgeOneTimestep() to age the star and update the star's attributes as a result of ageing a single timestep.  After the star's attributes have been changed (via Star::AgeOneTimestep()), Star::EvolveOneTimestep() checks how much the star changed over the timestep - specifically it checks the radial change of the star over the timestep.  If the radial change of the star over the timestep exceeds the threshold value of MAXIMUM_RADIAL_CHANGE (currently set to 0.01 in constants.h - 1% of the radius of the star), Star::EvolveOneTimestep() reverts the star to its state at the previous timestep, divides the timestep by 2, and tries the evolution again (by calling Star::AgeOneTimestep()).  This evolve->check->revert->evolve loop is performed repeatedly until either the radial change is below the MAXIMUM_RADIAL_CHANGE threshold, or the timestep reaches the minimum timestep threshold of the maximum of the dynamical timescale for the star (as calculated by BaseStar::CalculateDynamicalTimescale_Static()) and ABSOLUTE_MINIMUM_TIMESTEP (currently set to 100 seconds in constants.h (~3.1688x10^-12)), at which time the evolution of the star over the timestep is accepted and evolution continues with the next timestep.

In the BSE code, since each of the constituent stars needs to evolve over the same length of time, the first order timestep calculation for the binary is performed in BaseBinaryStar::Evolve() by calling BaseStar::CalculateTimestep() for each star, and using the minimum of those two values multiplied by the timestep multiplier specified by the user (via the --timestep-multiplier program option), and clamped to a minimum value of NUCLEAR_MINIMUM_TIMESTEP.  The BSE star then requests each star to evolve for a single timestep, with duration as just calculated by the BSE code (via BaseBinaryStar::EvolveOneTimestep() which calls Star::AgeOneTimestep() for each star).  No check is performed in the BSE code for change exceeding any threshold (e.g. radial change exceeding the radial change threshold MAXIMUM_RADIAL_CHANGE) - evolution just continues to completion, with a new timestep calculated for each iteration of the loop.

There are two issues:

(a) the evolutionary tracks for a star (e.g. star "S") evolved in SSE mode, and a wide binary that has star "S" as a constituent star and is evolved in BSE mode, will not be consistent for some stars, even if (as intended) the binary is sufficiently wide for there to be no interaction between the constituent stars.

(b) the check for radial change in the SSE code exists to ensure that a significant event is not stepped-over during the evolution of the star (by using a timestep that is too large).  That, or a similar, check is not performed in the BSE code, allowing the possibility that a significant event could be missed (the presumption is that the radial change check in SSE code exists for a valid reason).

Do we care about (a), or do we just accept that the evolutionary track for a star evolved in SSE mode may differ from the evolutionary track of the same star when it is a constituent star of a wide binary evolved in BSE mode?

Do we care about (b)?  If no, should we remove the radial change check from the SSE code?

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Run COMPAS in SSE mode and BSE mode and check evolutionary tracks

**Expected behavior**
Evolutionary tracks of stars evolved in SSE mode should match the evolutionary track of the same star evolved in a wide binary in BSE mode.

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Ubuntu 20.04
 - COMPAS v02.25.09

**Additional context**

**Comment by ilyamandel** [comment]
(a) Some difference between SSE and BSE (a) is unavoidable, since the timestepping in BSE, even without interactions, is driven by the minimum timestep required by the two stars -- so will generally result in one of the stars having a smaller timestep than it would have in SSE.  But, hopefully, the difference should be negligible if timesteps are small enough to ensure convergence.

(b) Yes, I think we should clamp timesteps in BSE for excessive stellar evolution -- but we will need to do this carefully, since mass transfer episodes can change stellar properties dramatically, and some do so in a single timestep, by construction.  I.e., for now, I would exclude the radial check clamp if there was mass transfer during this time step.

**Comment by TomWagg** [comment]
Perhaps a naive question @ilyamandel -- why do both stars in BSE always have to have the same timestep, isn't that wasteful? I can imagine that whilst they are detached (i.e. the regime in which SSE and BSE should be the same) it would be possible to just evolve one star for several timesteps and then do the other in one big chunk? Is there a good reason _not_ to do this?

**Comment by jeffriley** [comment]
> (a) Some difference between SSE and BSE (a) is unavoidable, since the timestepping in BSE, even without interactions, is driven by the minimum timestep required by the two stars -- so will generally result in one of the stars having a smaller timestep than it would have in SSE. But, hopefully, the difference should be negligible if timesteps are small enough to ensure convergence.

That is true.  I should have been more specific when I wrote issue (a) above.  What about:

(a) the evolutionary tracks for a star (e.g. star "S") evolved in SSE mode, and a wide binary that has star "S" as a the primary star and is evolved in BSE mode, will not be consistent for some stars, even if (as intended) the binary is sufficiently wide, and the secondary star sufficiently less massive than the primary, for there to be no interaction between the constituent stars.

Under those conditions, should we expect to see tracks with negligible differences SSE vs BSE?  The BSE timestep should be the timestep of the primary, and if there are no interactions the primary should evolve just as it would in SSE mode, shouldn't it (barring the differences that are the subject of this issue)?

**Comment by ilyamandel** [comment]
@TomWagg : We'd still need to check at every timestep (set by the more rapidly evolving star) if the stars remain detached.  Even if they are, they may still interact (e.g., through tides or winds).  Now, of course, we could just say that the slowly evolving star does nothing and copy over its parameters from the previous timestep -- but that's probably going to cause more headaches than savings.

@jeffriley : Yes, I think the differences should be negligible -- but the tracks may still not be identical to machine precision.

**Comment by avigna** [comment]
> Under those conditions, should we expect to see tracks with negligible differences SSE vs BSE? The BSE timestep should be the timestep of the primary, and if there are no interactions the primary should evolve just as it would in SSE mode, shouldn't it (barring the differences that are the subject of this issue)?

A plausible additional caveat: for very wide binaries, if masses are similar, at some point after the primary finishes the main sequence, the secondary will cross the Hertzsprung gap and will have shorter timesteps than the primary.

The point with this is that a wide binary is not a unique condition for similarity with SSE. I think you need to be wide, and your evolutionary timescale of the secondary (MS lifetime) should be less than the lifetime of the primary. This should lead to a "more similar" timestepping than only wide binaries. My 2 cents.

**Comment by ilyamandel** [comment]
@jeffriley -- am I correct that the remaining issue here is implementing radial change thresholding in BSE?

**Comment by jeffriley** [comment]
> am I correct that the remaining issue here is implementing radial change thresholding in BSE?

Yes, if the consensus is that's the right way forward.  It shouldn't be too difficult to implement - the Revert() functionality for binaries already exists, so just the check and revert if necessary is all that's needed.  For SSE we halve the timestep and continue to do that as long as the radial change is still too large, until we reach the absolute minimum timestep (100 seconds), at which time we just accept the timestep and continue evolution.  Is that what you suggest for binaries?

**Comment by jeffriley** [comment]
Implemented radial change check for BSE mode - v02.26.02 on branch bse_radial_check
Also added new (possibly temporary) option: --check-radial-change. A "BSE only" option that turns the BSE-mode radial change check on/off: off is the default. We can remove that option after testing if we don't want to keep it.

Some interesting stats:

10,000 binaries evolved with the radial check disabled takes ~105 CPU second, 1m45s elapsed time (using 1 core on my desktop)
10,000 binaries evolved with the radial check enabled takes ~465 CPU second, 7m45s elapsed time (using 1 core on my desktop)

This can be explained by the number of times the radial expansion threshold is exceeded and therefore the number of times the constituent stars are reverted and a smaller timestep is taken:

In BSE mode, with the radial check enabled, for 1,000 binaries evolved there were ~1,583,250 timesteps attempted (i.e. BaseBinaryStar::EvolveOneTimestep() was called ~1,583,250 times), and the radial change threshold was exceeded ~3,496,750 times (causing the constituent stars to be reverted and a smaller timestep attempted).
Note that the number of times the constituent stars are (possibly) reverted is not a 1:1 correspondence with the number of calls to BaseBinaryStar::EvolveOneTimestep() - there may be several retry attempts for each call).

Checking SSE mode, where the radial check is always enabled, for 1,000 stars evolved there were ~1,675,200 timesteps attempted (i.e. Star::EvolveOneTimestep() was called ~1,675,200 times), and the radial change threshold was exceeded ~6,036,280 times (causing the star to be reverted and a smaller timestep attempted).
Note that the number of times the star is (possibly) reverted is not a 1:1 correspondence with the number of calls to Star::EvolveOneTimestep() - there may be several retry attempts for each call).

I think this probably means our initial calculation of the required timestep is not right - producing more radial change than we want more often than not (or there is some other problem with the code that I haven't thought of).

@ilyamandel

**Comment by jeffriley** [comment]
> for now, I would exclude the radial check clamp if there was mass transfer during this time step.

Hmmm.  I forgot that caveat.  Let me see how easily I can implement that - shouldn't be too difficult.

**Comment by jeffriley** [comment]
I added a check for mass transfer in previous timestep when deciding whether to check radial change (pushed to branch bse_radial_check). 

The check doesn't make a big difference to the timing:

10,000 binaries evolved with the radial check enabled takes ~445 CPU second, 7m25s elapsed time (using 1 core on my desktop)

In BSE mode, with the radial check enabled, for 1,000 binaries evolved there were ~1,432,145 timesteps attempted and the radial change threshold was exceeded ~3,149,720 times.

It seems to me that our calculated required timestep is almost always too big, in that it almost always results in a radial change that is bigger than our threshold (for both SSE and BSE).  This raises some questions:

(a) is there a defect in our timestep calculations?
(b) is they way we calculate the timestep correct (i.e. the formulae/algorithm we have chosen - assuming there is no defect in the code)?
(c) is our radial change threshold the right threshold?
(d) and, of course, is the implementation of the radial change calculation and check correct and without defect (both SSE and BSE)?

@ilyamandel Thoughts?

**Comment by SimonStevenson** [comment]
@jeffriley Thanks for doing this analysis, this is very interesting. Is it possible to get a finer grained analysis of the timesteps that are rejected? For example, it would be good to know if this typically happens e.g., during the Hertzsprung gap phase (this is just a guess, but I know the radius changes a lot there). We could then focus on improving our estimate of the timestep for that phase. 

There is some discussion in this paper https://arxiv.org/abs/1902.07718 (section 2.3.1) about the choice of the numerical prefactors in the timestep calculations (they refer to these as pts1, pts2 and pts3). For example, they suggest using a smaller value of pts1 = 1E-3 (smaller timesteps on the main sequence) helps improve convergence. Looking in MainSequence.cpp, we currently use a prefactor of 1E-2, as originally suggested in Hurley et al. 2000 (https://arxiv.org/abs/astro-ph/0001295)

What command would I run to reproduce your radial check analysis above? I can experiment a bit with this and see if there are any easy fixes

Issue #470 seems related

**Comment by SimonStevenson** [comment]
There is some interesting behaviour of the timesteps on the main sequence that I don't fully understand. Using this branch, I evolved a 10 solar mass star using SSE (full command below). 

Here are some plots showing the evolution of the radius and timesteps on the main sequence. It seems that for this typical massive star, the default timestep is too big after only a quarter of the main sequence (i.e. we take too large timesteps for 75% of the main sequence!). The sharp drops in the dt plot (by a factor of 2) and the dR/R plot presumably correspond to the choice in the code to reduce the timestep by a factor of 2 if change exceeds the original threshold. In the later evolution, it seems that even further factors of 2 are required. 

It seems that even smaller timesteps than tMS/1000 (as suggested above) are taken towards the end of the evolution.

![R_MS](https://user-images.githubusercontent.com/6952112/146487507-4097221f-69fc-4507-94b2-ace60ccd2e94.png)

![dR_R_MS](https://user-images.githubusercontent.com/6952112/146484604-db920fe7-299f-4794-8ca3-51aeb221903b.png)

![dt](https://user-images.githubusercontent.com/6952112/146485270-5f20b562-979d-4b6e-80da-4a12d5b3a42c.png)

I think one useful solution could be that, if the previous timestep has already required reducing the timestep from the suggested default, and the stellar type hasn't changed, then it's probably a fairly safe assumption that the next timestep will also need to be reduced compared to the initially suggested timestep, and so we should do that straightaway, rather than trying and then reverting constantly. What do you think @ilyamandel ? How hard would this be to implement in practice @jeffriley ?

Another thought (which you are probably not going to like because it involves using the previous timestep) is to keep a running estimate of dR/dt for the star by comparing its current and previous radius. We could then use this to estimate the required timestep (with some safety factor) rather than using a fixed fraction of the main sequence lifetime.

Command to reproduce:
`./COMPAS --mode SSE --detailed-output --logfile-type CSV --initial-mass 10`

**Comment by jeffriley** [comment]
Thanks for looking at this @SimonStevenson 

> Is it possible to get a finer grained analysis of the timesteps that are rejected?

Yes, I can instrument the code a little more to trace the stellar type when timesteps are rejected, and how many times we do that per rejected timestep (if that makes sense - so if a timestep is rejected, and we divide by 2, we keep dividing by 2 until we get an acceptable radial change.  I should be able to record the number of times we divide by 2, and if we actually get an acceptable radial change or if we just go with the absolute minimum timestep).

> I think one useful solution could be that, if the previous timestep has already required reducing the timestep from the suggested default, and the stellar type hasn't changed, then it's probably a fairly safe assumption that the next timestep will also need to be reduced compared to the initially suggested timestep, and so we should do that straightaway,

We could do that.  We could also try to be a bit more dynamically adaptive (I think @ilyamandel has talked about this in the past), where we could reduce the timestep, but then gradually try to increase it - we don't really want to take lots of tiny steps if we can avoid it do we?  And if we reject an increased timestep, then reduce it, but maybe not all the way?  In other words, try to use a governor to find the optimum.

> Another thought (which you are probably not going to like because it involves using the previous timestep) is to keep a running estimate of dR/dt for the star by comparing its current and previous radius. We could then use this to estimate the required timestep (with some safety factor) rather than using a fixed fraction of the main sequence lifetime.

I think that's ok.  We do that for mass loss rate, so why not radial change rate?  We could even use that as the basis for the governor for the adaptive timestep.

**Comment by ilyamandel** [comment]
I think we need to return to this -- it's an important convergence issue (see also #24 ).

**Comment by jeffriley** [comment]
I think we should re-check some of these runs after fixing issue #855 - we still need to resolve the issues here, but some of the issue for massive stars might change.

**Comment by jeffriley** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Jeff/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Jeff/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | COMPAS   v02.35.04 (not yet merged into dev); 1,000,000 binaries with defaults except   --luminous-blue-variable-prescription BELCZYNSKI |  
  |   | Primary Star | Secondary Star |  
  |   | All Timesteps | Timesteps   for which Radial Change Exceeded 0.01 | All   Timesteps | Timesteps   for which Radial Change Exceeded 0.01 |  
  |   | Total Number of   Timesteps | Average   Radial Change* per Timestep | Maximum   Radial Change* in any Timestep | Number   of Timesteps | Fraction   of Total Timesteps | Average   Radial Change* per Timestep | Total   Number of Timesteps | Average   Radial Change* per Timestep | Maximum   Radial Change* in any Timestep | Number   of Timesteps | Fraction   of Total Timesteps | Average   Radial Change* per Timestep |  
  | All Types | 748787828 | 0.009362 | 1.000000 | 160545813 | 0.214408 | 0.036668 | 748787828 | 0.004386 | 1.000000 | 83310987 | 0.111261 | 0.031232 |  
  | MS<=0.7 | 0 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 | 40431064 | 0.000011 | 0.000000 | 0 | 0.000000 | 0.000000 |  
  | MS>0.7 | 103508267 | 0.011320 | 0.196198 | 34729051 | 0.335520 | 0.021414 | 475767457 | 0.001315 | 0.216976 | 14928403 | 0.031378 | 0.019738 |  
  | HG | 15889545 | 0.136622 | 0.223639 | 15884206 | 0.999664 | 0.136666 | 7595541 | 0.089932 | 0.223639 | 7437450 | 0.979186 | 0.091763 |  
  | FBG | 18620491 | 0.019615 | 0.180731 | 18425883 | 0.989549 | 0.019822 | 22403676 | 0.016768 | 0.180731 | 22256550 | 0.993433 | 0.016876 |  
  | CHeB | 272894717 | 0.005630 | 0.395813 | 48394368 | 0.177337 | 0.021269 | 121647353 | 0.003660 | 0.996770 | 10400545 | 0.085498 | 0.020708 |  
  | EAGB | 24926001 | 0.017658 | 0.395743 | 24488853 | 0.982462 | 0.017950 | 22882031 | 0.017060 | 0.391571 | 22587070 | 0.987109 | 0.017248 |  
  | TPAGB | 51220067 | 0.009096 | 0.977080 | 3152940 | 0.061557 | 0.100368 | 51390866 | 0.011580 | 0.980325 | 2935633 | 0.057124 | 0.165262 |  
  | HeMS | 13121219 | 0.005461 | 0.802274 | 2627056 | 0.200214 | 0.019200 | 1355842 | 0.013092 | 0.788772 | 729937 | 0.538364 | 0.021643 |  
  | HeHG | 14332295 | 0.051934 | 0.998116 | 11729760 | 0.818415 | 0.062041 | 3670495 | 0.038611 | 0.998086 | 2010076 | 0.547631 | 0.066725 |  
  | HeGB | 1150575 | 0.023807 | 0.999991 | 1092712 | 0.949709 | 0.024726 | 600 | 0.044291 | 0.999022 | 538 | 0.896667 | 0.048666 |  
  | HeWD | 6736 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 | 31255 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 |  
  | COWD | 151727269 | 0.000047 | 0.999990 | 11426 | 0.000075 | 0.618843 | 1027589 | 0.005973 | 0.999972 | 21626 | 0.021045 | 0.276469 |  
  | ONeWD | 71875666 | 0.000002 | 0.010041 | 1 | 0.000000 | 0.010041 | 39141 | 0.000331 | 0.012337 | 2 | 0.000051 | 0.011770 |  
  | NS | 4429771 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 | 478894 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 |  
  | BH | 4988964 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 | 805 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 |  
  | MR | 9557 | 1.000000 | 1.000000 | 9557 | 1.000000 | 1.000000 | 3157 | 1.000000 | 1.000000 | 3157 | 1.000000 | 1.000000 |  
  | CHE | 86688 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 | 62062 | 0.000000 | 0.000000 | 0 | 0.000000 | 0.000000 |  
  |   | *Radial Change = abs((radius - radiusPrev) / radiusPrev - i.e.   fraction of radius prior to change |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  



</body>

</html>

**Comment by jeffriley** [comment]
Not rigorous, but perhaps indicative.  Some interesting numbers there... (it's a png file, so you can click on it to make it bigger...)

![image](https://user-images.githubusercontent.com/26860470/224604481-cadf79fb-2476-4f57-a1d9-abd20702580d.png)

EDIT: Except for HG (and HeHG), I'm not sure we actually have too much of a problem with radial change being too big - which might explain why it hasn't really been noticed.

**Comment by ilyamandel** [comment]
@jeffriley -- I think you've addressed this, so we can close, right?  I'll close, but feel free to reopen if I am mistaken.
