### ISSUE TITLE
plotting script typo in examples/methods_paper_plots/detailed_evolution

### ISSUE THREAD

**Issue by katiebreivik** [TeamCOMPAS/COMPAS#714]
This issue is submitted as part of the JOSS review [#3838](https://github.com/openjournals/joss-reviews/issues/3838)

**Describe the bug**
The example use case of the detailed evolution of GW15226 plotting script fails because of a typo

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug 
urgency/severity are moderate only because it breaks a test that confirms a correct installation!

**To Reproduce**
when running the example given in the [documentation](https://compas.readthedocs.io/en/latest/pages/User%20guide/Tutorial/example-compas-run.html#tutorial-simple-compas-run), the plotting script fails because of a non-existing file. The automatically generated COMPAS output is placed in the correct directory, but since a single system is run, the `_0.h5`  in the [plotting script](https://github.com/TeamCOMPAS/COMPAS/blob/99cd751377f2a6d0d856124e6e516259386a0523/examples/methods_paper_plots/detailed_evolution/detailed_evol_plotter.py#L18) causes an error. I think this can be fixed by removing the `_0` in the plotting script.

**Comment by reinhold-willcox** [comment]
Hi @katiebreivik , thanks for catching this! I'm not sure I follow though. The `_0.h5` extension should be appended to the detailed output file even if there is only a single system. If you delete all the COMPAS_Output* directories and rerun the pythonSubmitDemo.py script, what is the path to your detailed output file?

Somewhat related, we've been heavily refactoring this plotting script recently. For the purposes of the review, would you like us to swap out the old script for the new one, or simply ensure that the old one is bug free? The new script does not reproduce the plot exactly as seen in the methods paper, but it is very similar.

**Comment by ilyamandel** [comment]
This was an issue I identified a few weeks ago, and I was sure we fixed it.  Let me check on this.

**Comment by ilyamandel** [comment]
@katiebreivik -- I confirmed that this is not an issue, as the latest COMPAS version does produce the file BSE_Detailed_Output_0.h5, which is what the plotting script expects.  What COMPAS version are you running?

**Comment by katiebreivik** [comment]
@ilyamandel You are 100% correct I was on an old version; I hadn't added the repo as an upstream remote branch which means when I fetch upstream and got nothing, I figured I had cloned directly and just did a git pull. 

On the latest dev branch (v02.25.10) I have verified that everything works!
