### ISSUE TITLE
Update online documentation to describe runSubmit.py

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#728]
Follow up on #720 .

**Comment by reinhold-willcox** [comment]
@ilyamandel Can we broaden this issue to cover all documentation updates?

**Comment by avigna** [comment]
(I will try to get on this asap, but my schedule is becoming more hectic these days... so bear with me.)

**Comment by ilyamandel** [comment]
@avigna -- ping :)

**Comment by avigna** [comment]
Yes, apologies, just returning from holidays. This is in my urgent items, hopefully by the end of this week.

**Comment by avigna** [comment]
(Mostly for my own reference) As far as I can see, I need to modify:

- https://compas.readthedocs.io/en/latest/pages/Getting%20started/dev-git-workflow.html
- https://compas.readthedocs.io/en/latest/pages/User%20guide/Running%20COMPAS/running-compas.html
- https://compas.readthedocs.io/en/latest/pages/User%20guide/Tutorial/example-compas-run.html
- https://compas.readthedocs.io/en/latest/pages/User%20guide/sampling.html
- https://compas.readthedocs.io/en/latest/pages/User%20guide/docker.html
- https://compas.readthedocs.io/en/latest/notebooks/CosmicIntegration.html?highlight=pythonSubmit
- https://compas.readthedocs.io/en/latest/pages/Getting%20started/dev-git-workflow.html?highlight=pythonSubmit

**Comment by avigna** [comment]
PR #738 created to address this.
