### ISSUE TITLE
Question about documentation: MASS_TRANSFER_TRACKER_HISTORY = 8?

### ISSUE THREAD

**Issue by HeloiseS** [TeamCOMPAS/COMPAS#733]
I'm looking at the MASS_TRANSFER_TRACKER_HISTORY definition on [this page](https://compas-docs-readthedocs.readthedocs.io/en/latest/standard-logfiles-record-specification-binary.html#binary-props-m) and I don't see a definition for 8 but I'm getting loads of 8 in my COMPAS results. What does it mean?

Also - where is the best place to ask questions like that which relate more to the documentation? If you want them on the github, would it be worth creating a special type of issue which is neither a bug report nor a feature request, but a documentation question?

**Comment by reinhold-willcox** [comment]
Hi Heloise, 

Thanks for catching this! 8 corresponds to a common envelope merger with a radiative envelope star. We also have a value 9 for CE merger due to immediate post-CE RLOF. Both of these need to be added to the documentation.

**Comment by avigna** [comment]
@reinhold-willcox uncertain if this should be closed?

**Comment by reinhold-willcox** [comment]
Thanks @avigna. I have not added this to the documentation yet, so let's leave it open. I'll set a reminder to myself to get this done.
