### ISSUE TITLE
Documentation -- runSubmit example

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#740]
Generate an example workflow using runSubmit and update documentation accordingly.

**Comment by avigna** [comment]
In the previous version of the COMPAS executable python scripts, a demo was offered using the `pythonSubmitDemo.py` file. Now that we have changed the `pythonSubmitDemo.py` for the tandem of `runSubmit.py` executable file and the `compasConfigDefault.yaml` options files, we need to rewrite the demo and the documentation to address these changes and provide a working (default) solution, as well as to deprecate the previous `pythonSubmitDemo.py` file.

**Comment by avigna** [comment]
(@themikelau @reinhold-willcox I seem to recall one of you assembled the `pythonSubmitDemo.py`, let me know if either/neither wants to tackle this)

**Comment by reinhold-willcox** [comment]
@avigna I can take a look - is there a branch you've been working on for this that I should build off of ?

**Comment by avigna** [comment]
Cool, thanks. There is no current branch for this, so you can just pull from dev and take it from there.
