### ISSUE TITLE
CO Core mass incorrect - USSN strongly affected

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#743]
**Describe the bug**
When a HeHG star undergoes MT, it should have its He envelope removed completely and be left with a bare CO core. While this is currently happening, I'm finding that the mass of the CO core (and thus the full star mass) is being set to the pre-MT total mass, i.e it's being increased artificially. Since there is now no envelope, a SN check is done. For the systems I looked at (~4000 which were USSN in a previous run), the result is now always a ECSN. This will strongly impact our DNS rates.

**Label the issue**
`urgency_high`     - This is a very urgent issue and should be resolved as soon as possible
`severity_major`    - This is a severe bug

**To Reproduce**
The following system shows the anomalous behavior. 
`--initial-mass-1 8.891924751925954 --initial-mass-2 4.509009428484924 -a 3.7728096873095587 --random-seed 100125`

This system undergoes 3 MT events - shown below are the BSE_RLOF parameter values for the events (the Zetas have been removed). The one to focus on is the 2nd one. Below that is the BSE_Supernovae output. 

It's a bit tricky, since the 2nd RLOF happens in the same timestep as the SN. But you can see in BSE_RLOF that the `Mass(1)<MT`  is 2.502, which corresponds to the mass at the beginning of the timestep. It is also type HeHG (which is why it grows so quickly from the previous MT event where it was first stripped). The `Mass(1)>MT` should be ignored, it is 1.26 because that value is grabbed at the end of the timestep, post SN, so it corresponds to the NS mass. In BSE_Supernovae, we can see that all of the pre-SN mass parameters for the (SN) star (in particular, `Mass_CO_Core@CO(SN)` and `Mass_Total@CO(SN)`) all equal 2.502. This star is also shown to be an ONeWD prior to the SN, which tells us that the pre-SN values are grabbed immediately prior to the SN code (and after the RLOF code). So even though the HeHG star started out at 2.502 and lost its envelope to the companion, the post-RLOF WD mass (i.e the CO core mass) is incorrectly set at 2.502. 

BSE_RLOF:
 |  SEED                 |  (units)  |  100125      |  100125     |  100125      |   
 |-----------------------|-----------|--------------|-------------|--------------|
 |  CEE>MT               |  Bool     |  1.000000    |  0.000000   |  0.000000    |   
 |  Eccentricity<MT      |  -        |  0.000000    |  0.000000   |  0.075230    |   
 |  Eccentricity>MT      |  -        |  0.000000    |  0.075230   |  0.000000    |   
 |  MT_Event_Counter     |  Count    |  1.000000    |  2.000000   |  3.000000    |   
 |  Mass(1)<MT           |  Msol     |  8.481525    |  2.502684   |  1.260000    |   
 |  Mass(1)>MT           |  Msol     |  2.511289    |  1.260000   |  1.260674    |   
 |  Mass(2)<MT           |  Msol     |  4.508438    |  4.508438   |  4.536080    |   
 |  Mass(2)>MT           |  Msol     |  4.508438    |  4.539410   |  0.749241    |   
 |  RLOF(1)<MT           |  Bool     |  0.000000    |  0.000000   |  0.000000    |   
 |  RLOF(1)>MT           |  Bool     |  1.000000    |  1.000000   |  0.000000    |   
 |  RLOF(2)<MT           |  Bool     |  0.000000    |  0.000000   |  0.000000    |   
 |  RLOF(2)>MT           |  Bool     |  0.000000    |  0.000000   |  1.000000    |   
 |  Radius(1)<MT         |  Rsol     |  367.157686  |  6.948473   |  0.000014    |   
 |  Radius(1)>MT         |  Rsol     |  2.528616    |  0.000014   |  0.000014    |   
 |  Radius(2)<MT         |  Rsol     |  2.725873    |  2.726233   |  17.801874   |   
 |  Radius(2)>MT         |  Rsol     |  2.725873    |  2.733700   |  0.162569    |   
 |  SemiMajorAxis<MT     |  Rsol     |  836.943499  |  18.642837  |  37.981328   |   
 |  SemiMajorAxis>MT     |  Rsol     |  18.619979   |  37.959519  |  9.026662    |   
 |  Stellar_Type(1)<MT   |  -        |  5.000000    |  8.000000   |  13.000000   |   
 |  Stellar_Type(1)>MT   |  -        |  8.000000    |  13.000000  |  13.000000   |   
 |  Stellar_Type(2)<MT   |  -        |  1.000000    |  1.000000   |  2.000000    |   
 |  Stellar_Type(2)>MT   |  -        |  1.000000    |  1.000000   |  7.000000    |   
 |  Time<MT              |  Myr      |  34.874487   |  34.904803  |  130.075331  |
 |  Time>MT              |  Myr      |  34.874487   |  34.904803  |  130.075331  |

BSE_Supernovae:
 |  SEED                        |  (units)  |  100125      |
 |------------------------------|-----------|--------------|
 |  Applied_Kick_Magnitude(SN)  |  kms^-1   |  30.777878   |
 |  ComponentSpeed(CP)          |  kms^-1   |  30.576929   |
 |  ComponentSpeed(SN)          |  kms^-1   |  30.576929   |
 |  Drawn_Kick_Magnitude(SN)    |  kms^-1   |  30.777878   |
 |  Eccentricity                |  -        |  0.07523     |
 |  Eccentricity<SN             |  -        |  0.0         |
 |  Experienced_RLOF(SN)        |  Bool     |  1           |
 |  Fallback_Fraction(SN)       |  -        |  0.0         |
 |  Is_Hydrogen_Poor(SN)        |  Bool     |  1           |
 |  Kick_Magnitude(uK)          |  -        |  0.160669    |
 |  MT_Donor_Hist(SN)           |  -        |  '5-8'       |
 |  Mass(CP)                    |  Msol     |  4.53941     |
 |  Mass(SN)                    |  Msol     |  1.26        |
 |  Mass_CO_Core@CO(SN)         |  Msol     |  2.502684    |
 |  Mass_Core@CO(SN)            |  Msol     |  2.502684    |
 |  Mass_He_Core@CO(SN)         |  Msol     |  2.502684    |
 |  Mass_Total@CO(SN)           |  Msol     |  2.502684    |
 |  Orb_Velocity<SN             |  kms^-1   |  191.560423  |
 |  SN_Kick_Mean_Anomaly(SN)    |  -        |  2.963774    |
 |  SN_Kick_Phi(SN)             |  -        |  -1.132935   |
 |  SN_Kick_Theta(SN)           |  -        |  3.994023    |
 |  SN_Type(SN)                 |  -        |  2           |
 |  SemiMajorAxis               |  Rsol     |  37.959519   |
 |  SemiMajorAxis<SN            |  Rsol     |  36.594108   |
 |  Stellar_Type(CP)            |  -        |  1           |
 |  Stellar_Type(SN)            |  -        |  13          |
 |  Stellar_Type_Prev(SN)       |  -        |  12          |
 |  Supernova_State             |  Bool     |  1           |
 |  SystemicSpeed               |  kms^-1   |  30.576929   |
 |  Time                        |  Myr      |  34.904803   |
 |  Unbound                     |  Bool     |  0           |
                  

**Expected behavior**
The core mass needs to stay fixed, and the total star mass needs to drop down to the core mass for HeHG MT. 

**Versioning (please complete the following information):**
 - COMPAS v02.27.01

**Additional context**

**Comment by ilyamandel** [comment]
Have a fix, just waiting for my previous PR to be approved since I inadvertently made the fix on the same branch but this one really ought to have its own version. :)

**Comment by ilyamandel** [comment]
Should be fixed in PR #751 .

**Comment by ilyamandel** [comment]
@reinhold-willcox -- I believe this is fixed, so closing, but please ping me if you spot any issues that I missed.
