### ISSUE TITLE
Make sure online documentation is up-to-date after sorting runSubmit / yaml upgrade.

### ISSUE THREAD

**Issue by avigna** [TeamCOMPAS/COMPAS#759]
Make sure online documentation is up-to-date after sorting out the following issues:

- [x] #740 
- [x] #741 
- [x] #750 

This implies removing all the notes suggesting any of the previous issues is pending or that the runSubmit / yaml  is not ready.

**Comment by avigna** [comment]
Minor things, but still pending from #741 

From the `stroopwafelInterface.py` script:
```
# TODO fix issues with adaptive sampling
# TODO add in functionality for alternative pythonSubmit names and locations
```

From the webpage:
> Set your desired options, then set the usePythonSubmit parameter to True in the stroopwafelInterface.py.

I suggest reopening, addressing, and then checking the tick mark and closing for real.

**Comment by reinhold-willcox** [comment]
Agreed, I think we still need to update the documentation before we can close this.
