### ISSUE TITLE
Update requested citation

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#760]
Update requested citation to point to published ApJS paper, https://ui.adsabs.harvard.edu/abs/2022ApJS..258...34R/abstract .  Incorporate JOSS paper?

[This applies to both https://compas.readthedocs.io/en/latest/pages/how-to-cite.html?highlight=citation and https://github.com/TeamCOMPAS/COMPAShttps://github.com/TeamCOMPAS/COMPAS ]

Also, add the COMPAS JOSS paper to the news section of the compas.science website.

**Comment by reinhold-willcox** [comment]
added to compas.science

**Comment by reinhold-willcox** [comment]
clicked close by accident...

**Comment by avigna** [comment]
@ilyamandel I assume that to change the webpage one needs to actually edit [the TeamCOMPAS.github.io repo](https://github.com/TeamCOMPAS/TeamCOMPAS.github.io). Two questions just for getting things straight in my head:
1. Shouldn't this issue be part of (or associated to) that repo? (Not that it matters that much.)
2. If so, it seems that we have not done PRs in that repo... is it accepted to pull/push to master, or do we now want to be more careful? The former is faster, and I assume not as risky as when changing code... but definitely get if PRs are preferred.

**Comment by reinhold-willcox** [comment]
@avigna You are correct, that repo doesn't use PRs, just commits to the master branch. Feel free to make the change

**Comment by ilyamandel** [comment]
The part about updating https://github.com/TeamCOMPAS/COMPAS is in this repo, @avigna and @reinhold-willcox .  In any case, all fixed with @reinhold-willcox 's latest commit, so closing.
