### ISSUE TITLE
No USSNe

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#761]
**Describe the bug**
We currently do not produce any USSNe in COMPAS. It is unclear why this is happening, or when it was introduced. We still have doubly-stripped systems which _should_ be flagged as USSNe, but as far as I can tell, they are all classified as ECSNe.

One possible source of the problem is that in `GiantBranch::ResolveSupernova()`, we identify ECSNe if  `(snMass < MCBUR2)` where MCBUR2 = 2.25 is defined as the "Core mass at base of the AGB above which the CO core is completely non-degenerate". So we should be comparing to the CO core mass not the total mass. 

Meanwhile, snMass comes from the function `CalculateInitialSupernovaMass()` which in GiantBranch.h just returns m_Mass, but this is overridden in some stellar type classes. Specifically, in HeHG.cpp, we have:
```
double HeHG::CalculateInitialSupernovaMass() const {
    if (utils::Compare(m_COCoreMass, m_Mass) == 0) {    // special case of ultra-stripped-star -- use current mass
        return std::max(m_Mass, m_GBParams[static_cast<int>(GBP::McBAGB)]);
    }   
    return GiantBranch::CalculateInitialSupernovaMass();
}
```

I checked for the cases of SNe which should be USSNe but are flagged as ECSNe, and the snMass is consistently 1.6 Msol (which is why the comparison with MCBUR2 always evaluates to true), even when m_Mass is larger than 1.6. I'll keep looking into this, but need to run now, so posting this issue and these first steps in case someone else has time/interest to look into this. 

**Label the issue**
`urgency_high`     - This is a very urgent issue and should be resolved as soon as possible
`severity_major`    - This is a severe bug

**To Reproduce**
Current default COMPAS with some of these systems. I have a larger grid, so these might not be representative, but I don't want to post the whole thing. 

```
 --initial-mass-1 9.322100263051011 --initial-mass-2 3.1587987252729217 -a 4.132760779522892 --random-seed 28
 --initial-mass-1 8.580491526089412 --initial-mass-2 8.104881912725139 -a 0.1390697759295803 --random-seed 332
 --initial-mass-1 11.240187803832582 --initial-mass-2 5.403709003224469 -a 0.09884499860753199 --random-seed 394
 --initial-mass-1 9.642267051178868 --initial-mass-2 5.904521565226383 -a 3.6341561146041745 --random-seed 415
 --initial-mass-1 10.024793009863979 --initial-mass-2 5.753485603089303 -a 4.894731749605503 --random-seed 485
 --initial-mass-1 7.7857720728077755 --initial-mass-2 6.643531797427209 -a 0.12856422984343968 --random-seed 500
 --initial-mass-1 11.447083709043914 --initial-mass-2 9.405316385429147 -a 0.08444318351785884 --random-seed 546
 --initial-mass-1 9.908471630123616 --initial-mass-2 8.43337510279692 -a 0.1548327098090108 --random-seed 580
 --initial-mass-1 9.236483400993375 --initial-mass-2 7.877727073242662 -a 0.2456129104998611 --random-seed 599
 --initial-mass-1 9.413357939845339 --initial-mass-2 8.522692050627962 -a 0.07610412563750199 --random-seed 757
 --initial-mass-1 12.249779968449845 --initial-mass-2 9.21058360481808 -a 0.09075176232472035 --random-seed 832
```

**Expected behavior**
Doubly stripped stars with masses > 2.25 should undergo USSNe, not ECSNe. 

**Versioning (please complete the following information):**
 - COMPAS v02.27.03

**Comment by jeffriley** [comment]
Introduced in v02.26.01
@ilyamandel

**Comment by ilyamandel** [comment]
@ilyamandel is searching for a blunt knife with which to commit harakiri.

**Comment by reinhold-willcox** [comment]
When you're done, could you leave the knife in the break room, we are sorely lacking in utensils.
