### ISSUE TITLE
Delayed update to binary properties after SN

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#768]
When a SN happens, the detailed BSE output file only updates the orbital parameters (semi-major axis, eccentricity) on the next step.  This makes plotting look awkward and could confuse users.  See the following example, from example_plots/methods_paper_plots/detailed_evolution [the semi-major axis rightly grows to 2155 Rsun by the next time step]. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/512213/154885823-071f4a1a-a495-48e7-8f5e-6677a5e2b241.png">

**Comment by reinhold-willcox** [comment]
Addressed in linked PR. Note that this PR points to the Defaults branch, which itself is under PR.
