### ISSUE TITLE
STARTRACK PPISN prescription

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#770]
**Describe the bug**
Currently the PPI_PRESCRIPTIONS for COMPAS and STARTRACK are identical. In principle, the COMPAS one tracks Woosley 2017, while the STARTRACK one tracks Belczynski 2016b. In the code, both prescriptions take the HeCore mass and calculate the neutrino mass loss based on the input options (by default, 0.9 times the He core). 

Looking at the overviews of these prescriptions outlined in Stevenson 2019 (https://arxiv.org/pdf/1904.02821.pdf), the STARTRACK prescription is supposed to give a fixed mass of 45 Msun for the He core mass, followed by any neutrino mass loss. This seems like an easy fix, which I am happy to do if someone else can confirm that this is a typo. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

 - COMPAS v02.27.05

**Comment by SimonStevenson** [comment]
Yes I can confirm that this is a typo, and your understanding is correct. In particular, I think changing line 1726 in GiantBranch.cpp from

baryonicMass = m_HeCoreMass;  

to 

baryonicMass = std::min(m_HeCoreMass, STARTRACK_PPISN_HE_CORE_MASS);

where I have defined STARTRACK_PPISN_HE_CORE_MASS in contants.h as

constexpr double STARTRACK_PPISN_HE_CORE_MASS           = 45.0;                                                     // Helium core mass remaining following PPISN as assumed in StarTrack (Belczynski et al. 2017 https://arxiv.org/abs/1607.03116)

I can submit a PR to address this

**Comment by jeffriley** [comment]
@SimonStevenson , @reinhold-willcox Can we document the changes in the changelog and update the version number please?

**Comment by reinhold-willcox** [comment]
woops, ya sorry, forgot to check that...
