### ISSUE TITLE
Envelope loss at HeHG stage

### ISSUE THREAD

**Issue by nrsegovia** [TeamCOMPAS/COMPAS#772]
**Describe the bug**

*Note: I'm not sure if this is working as intended. If so, sorry for bringing it up. It just seemed odd to me.*
Within the context of `EvaluateBinary(p_Dt)`, mass transfer episodes are evaluated using `CalculateMassTransfer(p_Dt)`. In the specific case of stable mass transfer from a donor with envelope, the entire envelope is assumed to be lost, only a fraction of which is accreted into the accretor. To decide the outcome of this interaction for the donor, `ResolveEnvelopeLossAndSwitch()` is called, which then calls `(void)SwitchTo(m_Star->ResolveEnvelopeLoss(true))`. Up to this point, the mass of the donor has **not** been updated (it happens later within `EvaluateBinary(p_Dt)`), but `ResolveEnvelopeLoss` does the following:

```
STELLAR_TYPE HeHG::ResolveEnvelopeLoss(bool p_NoCheck) {

    STELLAR_TYPE stellarType = m_StellarType;
    
    if (p_NoCheck || utils::Compare(m_COCoreMass, m_Mass) >= 0) {        // Envelope lost - determine what type of star to form
        std::cout << m_COCoreMass << ", " << m_Mass <<  "\n";
        m_CoreMass  = m_Mass;
        m_HeCoreMass= m_Mass;
        m_COCoreMass= m_Mass;
        m_Mass0     = m_Mass;
        m_Radius    = COWD::CalculateRadiusOnPhase_Static(m_Mass);
        m_Age       = 0.0;
        std::cout << m_COCoreMass << ", " << m_Mass <<  "\n";
        stellarType = (utils::Compare(m_COCoreMass, OPTIONS->MCBUR1() ) < 0) ? STELLAR_TYPE::CARBON_OXYGEN_WHITE_DWARF : STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF;
    }
    IsSupernova();
    return stellarType;
}
```
*`std::cout` lines added for testing purposes.*

Note that we go into the `if` statement through `p_NoCheck`, so in this case it is possible that `m_Mass > m_COCoreMass`. When this happens, `m_COCoreMass` is "bumped" to higher values (as `m_COCoreMass = m_Mass`), which in turn affects the value of `stellarType` and the result of `IsSupernova()`. Specifically, I have stumbled upon cases where the mass of the CO core is around 1.1 M_Sun, so the outcome should be a CO WD, but instead the envelope loss leads to a NS. I assume this is due to the "bumped" CO core mass (~1.9 M_Sun in this case) being used within `IsSupernova()`. 

It seems a similar problem might be present within the TPAGB stage. I'm also wondering if `m_COCoreMass` is the right value to use for `stellarType`, as Hurley+ 2000 seems to point towards the CO core mass at the beginning of the TPAGB (I would think it is equivalently the beginning of the HeHG), not at the moment of the mass transfer. However, a couple of tests have shown me that the difference is quite small (within my limited sample, at least), around 0.05 M_Sun.

**To Reproduce**
Example:

`./COMPAS -n 1 --detailed-output TRUE --random-seed 2473 --initial-mass-1 5.33242693076645 --initial-mass-2 4.18471764180155 -a 0.173980281865144 -e 0`

Gives the following masses for the secondary (in M_Sun):

- ~1.07 `m_COCoreMass` at the beginning of the HeHG phase.
- 1.13168 `m_COCoreMass` at envelope loss during HeHG.
- 1.90761 `m_Mass` at envelope loss. This is the value used within `stellarType` and `IsSupernova()`.

**Expected behavior**

The true value of the CO core mass should be used, so in the example case we should not get a SN (neither a NS).

**Screenshots**

![Problem](https://user-images.githubusercontent.com/64709690/156702604-f2dc94f6-234d-42d6-a00f-b6e5c2dad1cb.png)

Top and bottom panels are relevant around the jump from stage 8 to 13 of the secondary. The bottom plot shows that the CO core does not grow near `MECS` nor the Chandrasekhar Mass limit. The moment where `m_COCoreMass = m_Mass` is not plotted either, I think due to a NS being born with a fixed mass of 1.26 M_Sun in these cases.

**Versioning (please complete the following information):**
 - OS: Pop!_OS 21.10
 - COMPAS v02.27.00

**Comment by ilyamandel** [comment]
@solfreludio -- which version of dev are you using?  I note that the main issue described here was fixed around a month ago, in version 02.27.02 (see PR #751 in response to Issue #743 ).  I'll take a look at the value of the core mass to be compared against MCBUR1 shortly.

**Comment by ilyamandel** [comment]
./COMPAS -n 1 --detailed-output TRUE --random-seed 2473 --initial-mass-1 5.33242693076645 --initial-mass-2 4.18471764180155 -a 0.173980281865144 -e 0

leads to

0: Double White Dwarf: (Main_Sequence_>_0.7 -> Carbon-Oxygen_White_Dwarf) + (Main_Sequence_>_0.7 -> Carbon-Oxygen_White_Dwarf)

-- i.e., there's no SN here with the latest dev (COMPAS v02.27.05).

**Comment by ilyamandel** [comment]
Hurley+, 2000, p. 558:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/512213/156860089-08940641-2acc-48c4-b9f6-4f217533e0c4.png">

**Comment by ilyamandel** [comment]
And from p. 559:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/512213/156860793-7d9d0308-df51-4d00-ac84-70e9f643df8f.png">

**Comment by ilyamandel** [comment]
It's easy to change the TPAGB star decision making on CO vs ONe WDs to use the core mass at the start of the AGB, but I am not sure that it makes sense to use He star initial masses to decide on the outcome for He stars: whether or not Carbon will ignite off-centre should presumably be sensitive to how much mass was lost earlier during He star evolution.  On the other hand, McBGB is also not the right parameter to use for He stars.  Therefore, I suggest leaving the distinction between CO and ONe WDs as is for both AGB and He stars: to depend on the CO core mass at the moment of envelope loss.

**Comment by ilyamandel** [comment]
(Will add comments to code to clarify this -- done now, will appear in a future PR.)
