### ISSUE TITLE
ONe WDs in figure 8

### ISSUE THREAD

**Issue by nrsegovia** [TeamCOMPAS/COMPAS#773]
**Describe the bug**
Figure 8 in the Methods Paper shows that there is a narrow initial mass range which should produce ONe WDs as their final product. Trying to reproduce the same figure with the current version of COMPAS gives no ONe WDs.

I found this by running different populations (both under BSE and SSE), where no ONe WDs could be found. I thought it might have been something I broke, but reproducing the same populations within a new (clean) clone from COMPAS-dev showed the same results.

**To Reproduce**
Follow the instructions in `utils/example_plots/methods_paper_plots/fig_8_initial_core_final_mass_relations/ `, or run `n` systems with initial masses between 5-10 M_Sun.

**Expected behavior**
There should be a few ONe WDs, as seen in the Methods Paper.

**Screenshots**
Output from the Jupyter notebook for figure 8:
![image](https://user-images.githubusercontent.com/64709690/157781046-fadcb611-11f2-4d22-b93c-d88bb2454aef.png)

The top panel shows the issue, no ONe WDs between CO WDs and NS.

**Versioning:**
 - COMPAS v02.27.05

**Comment by nrsegovia** [comment]
Changing `stellarType` from `TPAGB::ResolveEnvelopeLoss` allows ONe WDs to be created once again. Specifically, changing from:

```
stellarType = (utils::Compare(m_COCoreMass, OPTIONS->MCBUR1() ) < 0) ? STELLAR_TYPE::CARBON_OXYGEN_WHITE_DWARF : STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF;
```

To: 

```
stellarType = (utils::Compare(gbParams(McBAGB), OPTIONS->MCBUR1() ) < 0) ? STELLAR_TYPE::CARBON_OXYGEN_WHITE_DWARF : STELLAR_TYPE::OXYGEN_NEON_WHITE_DWARF;
```
This is similar to what was done in the version used for the methods paper (and comes from Hurley+ 2000), although I'm not sure why it was changed and what would be the consequences of reverting the change (besides generating ONe WDs again).

Creating fig. 8 after modifying that line yields: 
[initial_core_final_mass_relations_McBAGB.pdf](https://github.com/TeamCOMPAS/COMPAS/files/8301583/initial_core_final_mass_relations_McBAGB.pdf)

**Comment by jeffriley** [comment]
> I'm not sure why it was changed

Do we know when it was changed - what version?

**Comment by ilyamandel** [comment]
Sure we do -- it's another thing I apparently messed up in PR #721 : 
https://github.com/TeamCOMPAS/COMPAS/pull/721/files

**Comment by ilyamandel** [comment]
Despite the comment 
// Note that this uses the CO core mass, rather than the core mass at base of AGB or He mass at He star birth suggested by Hurley+, 2000
this particular change should be reverted to match Hurley.

**Comment by reinhold-willcox** [comment]
@solfreludio Thanks for your patience, I'll try to push a fix for this before the end of the week!
