### ISSUE TITLE
Addition of a high-value biased probability distribution for metallicity

### ISSUE THREAD

**Issue by syedalimohsinbukhari** [TeamCOMPAS/COMPAS#775]
**Is your feature request related to a problem? Please describe.**
The metallicity distribution used in COMPAS is the log-uniform distribution and ZSolar. The former distribution is biased towards low-end metallicity values which are most likely to be present in the early galaxy/system while the latter is a fixed value. The problem arises if the user wants to simulate high metallicity stars to generate the binary systems closer to the present.

**Describe the solution you'd like**
A new distribution that samples more from the high-value tail of the distribution for metallicity.

**Comment by SimonStevenson** [comment]
Hello, thanks for reporting this issue! 

We typically use the log-uniform distribution as a sampling distribution when we want to cover all possible metallicities; we then typically reweight binaries from each metallicity according to the prevelance of that metallicity (see https://github.com/TeamCOMPAS/COMPAS/blob/dev/utils/PythonScripts/CosmicIntegration/FastCosmicIntegration.py for an example of this in the code).

As you mention, there is the possibility of using a fixed value for metallicity by setting the `--metallicity' option (either on the command line, in a grid file or in the config file (https://github.com/TeamCOMPAS/COMPAS/blob/dev/utils/preProcessing/compasConfigDefault.yaml)

For your particular issue, I would suggest making use of the grid functionality (see https://compas.readthedocs.io/en/latest/pages/User%20guide/grid-files.html). You can generate a list of metallicities (and other parameters) from whatever distribution you like ahead of time (e.g., in a Python script) and then pass that grid file to COMPAS at run time.

Let us know if these solve your issue, or if you need more help.

**Comment by syedalimohsinbukhari** [comment]
Just to clarify this for me, if I use a grid file that contains only the value of metallicity, eccentricity, and remnant-mass-prescription, the COMPAS will take the values of the remaining parameters (mass1, mass2, semi-major axis, and such) from the default distributions?

**Comment by SimonStevenson** [comment]
Yes that should work (just tested it on a small example and seems to work for me). You probably don't need to specify the remnant mass prescription seperately for each binary unless you really want to vary that as well. Let us know if this works for you and we can close the issue.

**Comment by jeffriley** [comment]
To further clarify, any options that are not specified in the grid file default to the option values specified on the command line, and options that are not specified on the command line default to the defaults in the C++ source (which are the same as the defaults specified in pythonSubit or runSubmit and the .yaml file).
