### ISSUE TITLE
Merger not recorded in detailed output?

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#800]
The final merger step is not recorded in the detailed output.  E.g., 
--initial-mass-1  60   --initial-mass-2  40   --semi-major-axis  0.3  --metallicity 0.0142 --eccentricity 0
with MULLERMANDEL remnants and kicks, otherwise default choices.

**Comment by reinhold-willcox** [comment]
What random seed are you using?

**Comment by ilyamandel** [comment]
0

**Comment by jeffriley** [comment]
Just a comment here.  A while ago I suggested we add a column to the detailed output file that would indicate the record type of the record written to the file.  We seem to have so many problems with the detailed output file - knowing when (in the evolution) records were written etc. that I think we should consider adding that field.  The field could just be an integer that indicates what the record is for, when it was written (where in the timestep maybe), etc.  Users don't have to use it, but if we do it properly then users could filter just the record types they want.  For example, if we as coders wanted to add intermediate detailed output records (to see what's happening at various points within a timestep), we would add them with a record type that indicates they are intermediate, then users could just filter them out if they don't want to use them.

**Comment by reinhold-willcox** [comment]
This system does not merge for me with seed 0, but is instead an unbound binary. I'm on v02.31.00.

**Comment by reinhold-willcox** [comment]
With updated seed 10, I see a merger correctly flagged in `BSE_System_Params`, `BSE_RLOF`, and in the detailed plotter text. As far as the detailed output, things look alright at first glance, but is there a specific parameter there you'd expect would indicate a merger?

**Comment by ilyamandel** [comment]
@reinhold-willcox : In the detailed plotter, you just decided that it's a merger because you are assuming that the only way for the binary to end evolution is either as a DCO, as an unbound binary, or a merger:
`
 isMerger = (Data['Time'][-1]<14000) and not isDCO and not isUnbound `
 
 That's actually a bit dangerous: e.g., I could choose to run for less than 14 Gyr (that's a command-line argument), and then my evolution might finish because I'm out of time, not because it's a merger.
 
 In any case, my point is still that the merger is not recorded in the detailed output.

**Comment by reinhold-willcox** [comment]
You are correct that the merger condition is not valid. This is now addressed in PR #813. 

Regarding your second point, that the merger is not recorded in detailed output: if you're referring specifically to the `BSE_Detailed_Output` file, then yes I agree, since we do not include a parameter for `isMerger`. We do have access to this information though, through the r1, r2, a and e parameters. This is how the merger endstate is redefined in the plotter in the new PR. Will that satisfy, or are you looking for an explicit 'isMerger' output parameter in the detailed output?
