### ISSUE TITLE
Binary disruption not recorded correctly in detailed_evol_plotter

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#801]
At the moment, detailed_evol_plotter continues chugging along if a binary is disrupted by a supernova, eventually printing that a binary will merge in Nan Myr if two compact objects are produced.

[Example: --initial-mass-1 6.034999559745024 --initial-mass-2 1.0 -a 1000
COMPAS --grid grid.txt --detailed --random-seed 300 --metallicity 0.0001 , see Issue #786 ].  

Easy enough to fix in the text output, but do we have a visualisation of a binary disruption (@serenavinciguerra89 ? @reinhold-willcox ?)

**Comment by reinhold-willcox** [comment]
In fact we do, I'll go about adding the graphic

**Comment by reinhold-willcox** [comment]
See #803

**Comment by reinhold-willcox** [comment]
Closing because this issue has been addressed in the linked PR
