### ISSUE TITLE
Description of CalculateMassAcceptanceRate

### ISSUE THREAD

**Issue by nrsegovia** [TeamCOMPAS/COMPAS#802]
The description of CalculateMassAcceptanceRate in both Remnants.cpp and BaseStar.cpp is wrong in the case of WDs. 

The part where it is mentioned that "The formalism of Nomoto/Claeys is used for WDs" does not describe the real behavior, since WDs follow the prescription implemented in Remnants.cpp for BHs and NSs.

**Comment by ilyamandel** [comment]
@solfreludio , @reinhold-willcox -- since this is being addressed in #822 , I'll close this issue now; feel free to re-open if I misunderstood.
