### ISSUE TITLE
maximum-evolution-time per binary

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#818]
**Is your feature request related to a problem? Please describe.**
When running with a modified maximum time in a gridfile, I get the error:

```
WARNING: Option not supported in grid file: 'maximum-evolution-time': ignored
```

This should be allowed, since we may want to evolve with different maximum times on a per binary basis. For example, I am looking at some very low mass stars, where the MS age is very long. If I evolve every binary at these longer total times, it slows down the whole run by a lot because the more massive systems are now evolving for much longer than needed.

**Comment by jeffriley** [comment]
This is a straight-forward change - I think probably two lines of code.

Whoever does this might also want to allow "maximum-number-timestep-iterations" in the grid file (same complexity - change is just two lines of code).
