### ISSUE TITLE
Binary properties missing from documentation

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#821]
The following binary properties are exposed as properties able to be added to binary log files, but are not described in the online documentation.  They should be added to the documentation:

RLOF_POST_STEP_STAR_TO_ROCHE_LOBE_RADIUS_RATIO_1
RLOF_POST_STEP_STAR_TO_ROCHE_LOBE_RADIUS_RATIO_2
RLOF_PRE_STEP_STAR_TO_ROCHE_LOBE_RADIUS_RATIO_1
RLOF_PRE_STEP_STAR_TO_ROCHE_LOBE_RADIUS_RATIO_2 

My best guesses at the respective descriptions are:

Ratio of the primary star's radius to the radius of its Roche lobe immediately following the time step
Ratio of the secondary star's radius to the radius of its Roche lobe immediately following the time step
Ratio of the primary star's radius to the radius of its Roche lobe immediately prior to the time step
Ratio of the secondary star's radius to the radius of its Roche lobe immediately prior to the time step

but I think these were added by @reinhold-willcox when he was updating the BSE_RLOF-related code (?), so he might change/elaborate as necessary.

**Versioning (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - COMPAS [e.g. v02.31.03]

**Comment by reinhold-willcox** [comment]
I can confirm the listed parameters are as you have described them.

**Comment by jeffriley** [comment]
Maybe we can do this and #826 together?

**Comment by ilyamandel** [comment]
I addressed #826 , but ran out of steam for this one -- leaving it to the next person. :)
