### ISSUE TITLE
Odd system: merger of HeMS with massless remnant

### ISSUE THREAD

**Issue by nrsegovia** [TeamCOMPAS/COMPAS#825]
**Describe the bug**
As I do not know if the following is a bug, I have just labeled it as a question.

I have been running tests with systems where at least one component goes through the HeMS phase, and I'm using the RLOF log file to check for changes in separation. Amongst these, some have `CEE>MT == 1` but `SemiMajorAxis>MT` does not show up in my plots as, for some reason, the separation is `nan`. Running one of these systems under the detailed mode shows no problems with the separation, but the simulation stops after the MT episode, and the message in the terminal says that the stars merged. However, in the last time step saved in the detailed output, the radii are ~150 and ~0.1 R_Sun while the separation is ~260 R_Sun (so no `HasStarsTouching()`). On top of that, the bigger star ends as an EAGB star according to the detailed output, but the final message in the terminal says it is a massless remnant. I checked SN flags just in case (`Supernova_State`), but nothing pops up.

So, to summarize:
* Why am I suddenly getting a `nan` value for the separation? My guess is that the "merger" caused it
* But then, why am I getting a merger when the stars do not seem to be close enough? Is a CEE being resolved but not logged?
* And finally, any clues about what leads to the printing of `massless_remnant` as final phase of the EAGB star? The `--rlof-printing` indicates that there is a CE episode before the end of the simulation, which seems to be linked to the evolution into a massless remnant.

**To Reproduce**
```
--random-seed 1952  --maximum-evolution-time 15000 --initial-mass-1 2.906743424402851 --initial-mass-2 2.183152794529362 -a 0.14299254627993116 -e 0.20219885610022265 -n 1 --common-envelope-alpha 0.25 --common-envelope-lambda-prescription LAMBDA_LOVERIDGE -z 0.005 --mass-transfer-accretion-efficiency-prescription THERMAL --allow-rlof-at-birth TRUE --detailed-output TRUE
```
And a similar run turning `--detailed-output` off, while turning `--rlof-printing` on (to check for changes before/after MT episodes).

**Versioning:**
COMPAS v02.31.04

**Comment by ilyamandel** [comment]
@solfreludio -- I think what happens to these stars is fine, but the DetailedOutput is not. :(

What happens is that there is a reverse MT phase from a 3.5 solar mass EAGB star to a 0.4 solar mass naked He star.  This phase leads to a common envelope, with an immediately ensuing RLOF, which indeed leads to a stellar merger.  However, we do not record this in DetailedOutput.  

I've now changed DetailedOutput to record this in #830 , but there are numerous other issues in DetailedOutput to be fixed.
