### ISSUE TITLE
ComponentSpeed missing from documentation

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#826]
No description of ComponentSpeed in the documentation.

**Comment by jeffriley** [comment]
Maybe we can do this and #821 together?

**Comment by ilyamandel** [comment]
Also, I just noticed that cool wind multipliers are mentioned twice in the list of options references from --use-mass-loss (https://compas.readthedocs.io/en/latest/pages/User%20guide/Program%20options/program-options-list-defaults.html#options-props-u), so let's fix that too, while we are at it. :)

**Comment by ilyamandel** [comment]
And one more, carried over from #849 : if running with --critical-mass-ratio-prescription, zeta's will not be computed correctly, so should not be trusted in the outputs.

**Comment by ilyamandel** [comment]
Addressed all of these in PR #915  ; fixed the changed name of SystemicSpeed while at it.  Closing.
