### ISSUE TITLE
--allow-H-rich-ECSN flag does not work

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#827]
I found ECSNe labeled as H-poor (I ran with --allow-H-rich-ECSN: False ) in binaries with huge separations — sometimes >1000 AU.

This is odd, because H-poor SNe should only happen in stripped stars, and stripping can only happen in interacting binaries.

On investigation, it turns out that we assume that H-poor stars are those that formed from objects of type HeMS and later.  Of course, ECSNe are formed from ONe WDs, so always satisfy this — i.e., all ECSNe are always H-poor, and the flag is meaningless.

What the flag was supposed to represent is whether the star had been stripped of its H envelope earlier, but it does not detect this as currently implemented.

P.S. A probably unrelated issue — but still one to fix -- is that our ONeWDs can have total masses larger than He core masses.

**Comment by ilyamandel** [comment]
Not closing yet because of 

P.S. A probably unrelated issue — but still one to fix -- is that our ONeWDs can have total masses larger than He core masses.

**Comment by ilyamandel** [comment]
`“A probably unrelated issue — but still one to fix -- is that our ONeWDs can have total masses larger than He core masses.”  `

It turns out that all of these are due to Accretion Induced Collapse of ONeWDs.  And it’s not that rare — 4.5% of all ECSNe are actually AICs.  Now, partly this will be addressed by @solfreludio's fixes of MT onto WDs (i.e., they shouldn’t just end up with loads of hydrogen on top).  But this also brings up the issue that, perhaps, we really should consider AICs as a separate SN type.  Thoughts?

**Comment by ilyamandel** [comment]
This also made me realise that checking for a non-empty MT history string, as @reinhold-willcox  has done, doesn’t quite catch the requirement of looking for stripped ECSN donors, since accretors that were never stripped would also pass.  So I’ll assign the issue to Reinhold again.  I think we should check specifically whether the star experiencing a possible ECSN was ever a donor.  This may require a separate variable to be tracked.

**Comment by reinhold-willcox** [comment]
Issue addressed in linked PRs #828 and #832
