### ISSUE TITLE
Add zeta prescription options to help output

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#837]
The help output states that for `--stellar-zeta-prescription`, the default is SOBERMAN, but doesn't list the other options. Very easy fix, good first issue.

**Comment by ilyamandel** [comment]
It looks like this issue is addressed in #849 , so I am closing this -- @reinhold-willcox and @LewisPicker , please feel free to reopen if I made a mistake.
