### ISSUE TITLE
Incorrectly implemented option "--mass-transfer-thermal-limit-accretor"

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#850]
**Describe the bug**
The option "--mass-transfer-thermal-limit-accretor" is unclearly documented and likely incorrectly impemented. 

The option sets the parameter `OPTIONS->MassTransferThermallyLimitedVariation()` to either `MT_THERMALLY_LIMITED_VARIATION::RADIUS_TO_ROCHELOBE` or `MT_THERMALLY_LIMITED_VARIATION::C_FACTOR` (the default). 
The only place this is called is in BaseStar

```
 /*
  * Calculate thermal mass acceptance rate
  *
  *
  * double CalculateThermalMassAcceptanceRate(const double p_Radius)
  *
  * @param   [IN]    p_Radius                    Radius of the accretor (Rsol) [typically called with Roche Lobe radius]
  * @return                                      Thermal mass acceptance rate
  */
 double BaseStar::CalculateThermalMassAcceptanceRate(const double p_Radius) const {
              
     return OPTIONS->MassTransferThermallyLimitedVariation() == MT_THERMALLY_LIMITED_VARIATION::RADIUS_TO_ROCHELOBE
             ? (m_Mass - m_CoreMass) / CalculateThermalTimescale(p_Radius)
             : CalculateThermalMassLossRate();
 }
```
It's unclear to me what the true case (the line starting with `?`) is intended to do. I think it's doing the same thing as the following line, except that the following line defines this for different stellar types. When I look into the function

```
 /*
  * Calculate thermal timescale
  *
  * pre-factor from Kalogera & Webbink 1996 (https://arxiv.org/abs/astro-ph/9508072), equation 2, 
  * combined with p_Mass * p_EnvMass case from equation 61 from https://arxiv.org/abs/astro-ph/0201220 for k in {2,3,4,5,6,8,9}
  * [note that equation 61 of BSE (https://arxiv.org/abs/astro-ph/0201220) approximates this with a value a factor of 3 smaller]
  *          
  *      
  * double CalculateThermalTimescale(const double p_Radius) const
  *          
  * @param   [IN]    p_Radius                    Radius in Rsol
  * @return                                      Thermal timescale in Myr
  *
  * The p_Radius parameter is to accommodate the call (of this function) in BaseBinaryStar::CalculateMassTransfer()
 */
 double BaseStar::CalculateThermalTimescale(const double p_Radius) const {
     return 31.4 * m_Mass * (m_Mass == m_CoreMass ? m_Mass : m_Mass - m_CoreMass) / (m_Radius * m_Luminosity); // G*Msol^2/(Lsol*Rsol) ~ 31.4 Myr (~ 30 Myr in Kalogera & Webbink)
 }

```

The function takes `p_Radius` as an argument but then doesn't use it. So this is a secondary bug, but not so severe. 

We should either clean up the  "--mass-transfer-thermal-limit-accretor" option, or remove it to avoid confusion. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**Versioning (please complete the following information):**
 - COMPAS v02.33.00

**Comment by avigna** [comment]
The choice of using the Roche-lobe radius instead of the stellar radius is mainly to avoid any problems when RLOF occurs during expasion in the Hertzsprung Gap; for example, the condition for RLOF is met regardless of the star barely or significantly filling its Roche lobe. In principle, one could refine the moment where RLOF occurs, but one would need to be careful about not spending to much calculation time on this.

Following a quick read to the code, I think I agree with your assessment about cleaning the function and structure to determine the `--mass-transfer-thermal-limit-accretor`.

Finally, I am not sure if this actually qualifies as a bug. I would probably consider it as a request for an enhancement.

**Comment by ilyamandel** [comment]
@avigna , @reinhold-willcox : RADIUS_TO_ROCHELOBE is meant to refer to the accretor, not the donor.  Philipp Podsiadlowski suggested computing the accretor thermal time scale as if it already expanded to its RL radius in lieu of the arbitrary factor of 10.  @serenavinciguerra89 actually found that it didn't make much difference, but we kept the option.  I'll investigate / clean up the comments shortly.

The other issue @reinhold-willcox pointed out is the one @jeffriley entered as #853 -- and that's just a mistake, fixing that, too.
