### ISSUE TITLE
Question re parameter to BaseStar::CalculateThermalTimescale() - possible defect?

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#853]
**Describe the bug**
In this commit:

https://github.com/TeamCOMPAS/COMPAS/commit/2c9991c2daddb61d395babc3ec04f89986644c1d

we added (or moved?) BaseStar::CalculateThermalTimescale(const double p_Radius), but the body of the function does not actually use the parameter p_Radius - it uses m_Radius.

@ilyamandel I think this was your commit - can you take a look to see if this was an oversight?

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
Look at the source...

**Expected behavior**
Either use the parameter to BaseStar::CalculateThermalTimescale() or remove it (if it is no longer used it is confusing to have it there).

**Versioning (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - COMPAS [e.g. v02.23.00 and greater

**Comment by jeffriley** [comment]
@ilyamandel also see issue #850

**Comment by ilyamandel** [comment]
Yes, this is a mistake.  Fixed in #866 .
