### ISSUE TITLE
Super-Eddington accretion during a common-envelope event

### ISSUE THREAD

**Issue by avigna** [TeamCOMPAS/COMPAS#859]
It would be a useful enhancement to have the possibility of super-Eddington accretion onto a neutron star or black hole during a common-envelope event. This is in a similar vein to what was done and considered in [van Son et al. (2020)](https://ui.adsabs.harvard.edu/abs/2020ApJ...897..100V/abstract), but that version never made it to the main COMPAS repo. One could think of having a multiplicative factor to the Eddington limit, as well as alternative criteria.

See, e.g., a brief discussion here: https://compashq.slack.com/archives/CMCEQ0RS8/p1666102881607499

**Comment by blazehoulden** [comment]
Just had a look through this and the van Son et al. (2020) paper, and it looks like the common-envelope super-Eddington accretion was modelled (model 2), as well as a stable mass transfer (model 1) and a combination of the two (model 3) that was all done through COMPAS, would @LiekeVanSon have that version of COMPAS code that could be brought into the repo? This would allow for a few different possible avenues to explore the super-Eddington accretion scenario.
