### ISSUE TITLE
run_details in COMPAS_Output.h5 'default' values not stored -- just 'default' string

### ISSUE THREAD

**Issue by avivajpeyi** [TeamCOMPAS/COMPAS#860]
It may be helpful to store the actual values used for various parameters for a run, instead of just `DEFAULT_USED`.  This currently forces users to have to dig up the `DEFAULT_VALUE` in the docs.

This may also be helpful for keeping track of run configs if in the future the `DEFAULT_VALUE` changes.

**Comment by jeffriley** [comment]
@avivajpeyi the values are stored (DEFAULT_USED is just an indication that the user didn't specify a value - but the value is actually there). Remember though that the RUN_DETAILS file only stores values for parameters that were specified on the commandline - if you are using a grid file then your grid file is where you need to look for the values used for individual binaries - the grid file is copied to the output folder.

Edit:

e.g. this line in the Run_Details file:

    PISN-upper-limit = 135.000000, DEFAULT_USED, DOUBLE

means that the value used for PISN-upper-limit was 135.0, and that the user did not specify a value on the commandline, so the default was used (and the data type was double precision floating point).

Whereas this line:

    initial-mass-1 = 10.000000, USER_SUPPLIED, DOUBLE

means that the value used for initial-mass-1 was 10.0, and that the user specified that value on the commandline (and the data type was double precision floating point).

You should be able to construct the commandline that the user used from the contents of the Run_Details file

If you want to use the Run_Details group in the HDF5 output file, try running 'h5view.py -H' across the file to see the column (dataset) names/keys (h5view.py is in the 'utils' directory)

https://compas.readthedocs.io/en/latest/pages/User%20guide/Post-processing/post-processing-h5view.html

**Comment by jeffriley** [comment]
Closed - user misunderstanding
