### ISSUE TITLE
duplicates of .ipynb? 

### ISSUE THREAD

**Issue by avivajpeyi** [TeamCOMPAS/COMPAS#861]
Hey -- it looks like there are duplicate ipynb present: 

[COMPAS/online-docs/notebooks](https://github.com/TeamCOMPAS/COMPAS/blob/dev/online-docs/notebooks/CosmicIntegration.ipynb)
[COMPAS/utils/Tutorial](https://github.com/TeamCOMPAS/COMPAS/blob/dev/utils/Tutorial/CosmicIntegration.ipynb) 

Initially it was a bit unclear to me which one I should be using -- but it looks like the Tutorial files have been copied over into the docs folder.

Maybe just keep the `Tutorial` folder in the `doc` dir? This may help future users from getting confused by this.

Examples of where this has been done in other repos: 

https://docs.exoplanet.codes/en/latest/

<img width="869" alt="Screen Shot 2022-11-04 at 12 27 06 pm" src="https://user-images.githubusercontent.com/15642823/199865483-e02e9394-4b69-4fdf-9401-58cc03297df7.png">

Alternatively, maybe just include links to github where the notebooks are located in the `utils/Tutorials/` folder (rather than coping the files from tutorials --> docs/notebooks`)

**Comment by reinhold-willcox** [comment]
I spoke to avi about this. Yes, these are duplicates, we copy the notebooks from the utils foler into the online-docs so that we can access them in both places and make sure they are consistent between each other. I agree that this is unnecessary and we can simply keep them in the online docs.

**Comment by avivajpeyi** [comment]
Also -- its not clear to me in the docs where the tutorials live: 
<img width="819" alt="Screen Shot 2022-11-05 at 12 26 47 am" src="https://user-images.githubusercontent.com/15642823/199983797-2153b7c5-b750-411c-8767-e716a04dd7b2.png">

They don't appear in the sidebar, not sure which category they fall in.

**Comment by jeffriley** [comment]
As far as I remember, most, if not all, the tutorials are for the post-processing code - so maybe look here in the User Guide:

https://compas.readthedocs.io/en/latest/pages/User%20guide/Post-processing/post-processing.html

Also, there is a search bar you can use - just enter "tutorial" there and you'll find the tutorials.

**Comment by ilyamandel** [comment]
@avivajpeyi , @reinhold-willcox -- is this issue still relevant in view of the restructuring you've undertaken?

**Comment by reinhold-willcox** [comment]
@ilyamandel Yes this is relevant, but we hope to have it resolved when the restructuring is complete.
