### ISSUE TITLE
git-workflow docs outdated? 

### ISSUE THREAD

**Issue by avivajpeyi** [TeamCOMPAS/COMPAS#862]
Hey i think that the git-workflow docs are outdated? 
I think there might not be a prod branch? 

https://compas.readthedocs.io/en/latest/pages/Getting%20started/dev-git-workflow.html#the-compas-git-workflow

**Comment by reinhold-willcox** [comment]
Yes, these are outdated. We can update them alongside the other repo clean ups.

**Comment by ilyamandel** [comment]
@avivajpeyi , @reinhold-willcox -- ping on this one?

**Comment by ilyamandel** [comment]
Hi @avivajpeyi , what's the status of #1110 ?
