### ISSUE TITLE
Remove superfluous p_NoCheck parameter of the ResolveEnvelopeLoss() function(s)

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#873]
The function ResolveEnvelopeLoss() modifies a star's attributes after it loses its envelope - if it in fact lost its envelope. ResolveEnvelopeLoss() first checks whether the envelope has been lost - the check is some variation of core mass >= mass depending upon stellar type - if that is true then the envelope is gone and the attributes of the star are updated. We don't want to update the attributes if the star hasn't actually lost its envelope, even if the updates would be benign (in terms of affecting the attributes of the star) - the calculations are not trivial, so we don't want to negatively affect performance by doing non-trivial calculations that are not necessary.

The p_NoCheck parameter of the ResolveEnvelopeLoss() function allows callers of the function to force the calculations to happen - that is, if p_NoCheck is passed as TRUE, no check is performed, and the star's attributes are updated without checking whether it still has an envelope. p_NoCheck is (currently) only passed as true in three places in the code:

    GiantBranch::CalculateRadialExtentConvectiveEnvelope()
    HG::CalculateRadialExtentConvectiveEnvelope()
    Star::ResolveEnvelopeLossAndSwitch()

In the first two cases we clone the star and then call ResolveEnvelopeLoss(true) to force the calculations so we can pick up the newly calculated radius of the star.

In the third case we assume we already know the envelope is gone, so don't bother checking again (this could be an issue in the current code - see issue #874 ).

The p_NoCheck parameter exists because the legacy code did the envelope existence check, and bypassed it (differently, but still bypassed it) in the cases described above. The first two cases where we bypass the check, we're just trying to figure out the new radius of the star after losing its envelope - we don't want to update it yet, we just want to know what the value would be. When I ported the code I wondered if bypassing the check was actually required. If we call ResolveEnvelopeLoss() and always perform the check for envelope loss, then in the event of no envelope loss the radius of the star would be unchanged, and we would use that unchanged radius in the two cases above (that have p_NoCheck = true). I planned to check if that actually made a difference, but I didn't get back to it until now.

As described above, the p_NoCheck parameter to ResolveEnvelopeLoss() overrides the check at the top of the function that checks whether the star actually has lost its envelope - if p_NoCheck is TRUE, the check is not performed. What that means is that if p_NoCheck is TRUE, the loss of the star's envelope is resolved (i.e. attributes of the star are recalculated) whether it has lost it's envelope or not.

The check at the top of the *::ResolveEnvelopeLoss() functions is to determine if in fact the star has lost its envelope - no point resolving the loss of an envelope if the envelope was not actually lost. That check is implemented differently for different stellar types. Here are the current checks by stellar type:

    MS    : m_Mass <= 0
    HG    : m_CoreMass >= m_Mass
    FGB   : m_CoreMass >= m_Mass
    CHeB : m_CoreMass >= m_Mass
    EAGB : m_HeCoreMass >= m_Mass
    TPAGB: m_CoreMass >= m_Mass
    HeMS : m_Mass <= 0.0
    HeHG : m_COCoreMass >= m_Mass

Other stellar types inherit as usual.

I ran a test of 1,000,000 binaries, and found that in all cases whenever ResolveEnvelopeLoss() was called with p_NoCheck = TRUE, the envelope lost check at the top of the function was also satisfied - i.e. every call to ResolveEnvelopeLoss() with p_NoCheck = TRUE would have resulted in the code being executed anyway because the envelope lost check was also satisfied. It would seem then that the p_NoCheck parameter is superfluous and can safely be removed.

Based on the result of the test of 100,000 binaries described above, my recommendation is to remove the p_NoCheck parameter for all variants of the function (and callers).

**Comment by ilyamandel** [comment]
My first comment when looking at this is that the following comment in GiantBranch::CalculateRadialExtentConvectiveEnvelope() is misleading:

 * Hurley et al. 2000, sec. 2.3, particularly subsec. 2.3.1, eqs 36-40

There is no section 2.3 in Hurley et al. 2000, and I believe this should point to Hurley et al. 2002. :-)

**Comment by ilyamandel** [comment]
The goal of cloning the star in GiantBranch::CalculateRadialExtentConvectiveEnvelope() and then removing the clone's envelope is to ask what would have been the radius of the core alone.  I do not understand why a giant star would already evaluate to satisfying the condition for ResolveEnvelopeLoss in the absence of forcing, unless the clone is not faithful in this case.  I don't see the constructor code for BaseStar -- but the first thing I'd check is that the clone has the same values for core mass and total mass as the original GiantStar before ResolveEnvelopeLoss() is called on the clone.

**Comment by jeffriley** [comment]
Hmmm.  Ok, I'll run my test again and take a look.

**Comment by ilyamandel** [comment]
I am not questioning what your test says (I believe you when you say that p_NoCheck doesn't make a difference).  I am wondering if the cloned star is not doing what we intended.  Can you check that the clone has the same values for core mass and total mass as the original GiantStar before ResolveEnvelopeLoss() is called on the clone?

**Comment by jeffriley** [comment]
Yeah, that's what I meant - I'd run my test and check the clone

**Comment by ilyamandel** [comment]
@jeffriley -- is this still relevant given your recent work on clones?

**Comment by ilyamandel** [comment]
@jeffriley -- this might be the easy one I mentioned today :-)

**Comment by jeffriley** [comment]
@ilyamandel 

Well, we know the clones weren't working back then - but GiantBranch::CalculateRadialExtentConvectiveEnvelope() no longer uses a clone.

The only place we call `ResolveEnvelopeLoss()` with `p_NoCheck = true` is in `ResolveEnvelopeLossAndSwitch()` in `Star.h`.

`ResolveEnvelopeLossAndSwitch()` is called in `BaseBinaryStar::ResolveCommonEnvelopeEvent()` and `BaseBinaryStar::CalculateMassTransfer()`.

There are cases where `p_NoCheck = true` actually does override the envelope check in `ResolveEnvelopeLoss()`:

(a) when `ResolveEnvelopeLossAndSwitch()` is called from `BaseBinaryStar::CalculateMassTransfer()`:

    `ResolveEnvelopeLossAndSwitch()` is called thus:

        if (isEnvelopeRemoved) m_Donor->ResolveEnvelopeLossAndSwitch(); 

    Presumably we use 'p_NoCheck = true' here because we've already decided the donor's envelope has been removed, but that's not quite true.  We do this just before the call to `m_Donor->ResolveEnvelopeLossAndSwitch()`: 

    m_Donor->SetMassTransferDiffAndResolveWDShellChange(massDiffDonor);                                                 // set new mass of donor

   but that function doesn't actually update the mass - it sets the amount by which the mass should be changed, but the actual change is done later (I think in ResolveMassLoss() or similar).

   So here, the `p_NoCheck` parameter is required (the way the code is currently structured).

(b) when `ResolveEnvelopeLossAndSwitch()` is called from `BaseBinaryStar::ResolveCommonEnvelopeEvent()`:

    Here we do a similar thing. `envelopeFlag1` and `envelopeFlag2` are calculated at the top of the function, and used later to call `ResolveEnvelopeLossAndSwitch()`.  In this case we do update the mass of the star, but when we get to `ResolveEnvelopeLoss()` we see that:

    m_Mass = 1.190733986509239, and  m_CoreMass = 1.190733986509239, which might look to be the same value, but printing `m_CoreMass - m_Mass` gives `-0.000000000000000` (note the minus sign), and `m_Coremass < m_Mass` resolves to `true`.

I've only looked at a single example of each of the above.  (a) is just a matter of timing, and is probably why the (equivalent of the) `p_NoCheck` parameter existed in the legacy code.  (b) could be solved by using a threshold on the compare.

I'll do some more checking tomorrow, but I don't think is an easy close...

**Comment by ilyamandel** [comment]
Discussed ad nauseam, agreed that no change is needed, some code cleaning in #1124.
