### ISSUE TITLE
h5copy bloats the output

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#923]
**Describe the bug**
When using the h5copy.py file to combine various individual COMPAS output files, the resultant file is much larger than the sum of the individual inputs. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
```
COMPAS --random 0 -c out0 && COMPAS --random 10 -c out1
mkdir out_both
python h5copy.py out0/out0.h5 out1/out1.h5 -o out_both/out_both.h5
ls -hl out*/*.h5
```
The output of the last command is:
```
-rw-rw-r-- 1 rwillcox rwillcox 7.1M Feb 16 16:06 out0/out0.h5
-rw-rw-r-- 1 rwillcox rwillcox 7.1M Feb 16 16:06 out1/out1.h5
-rw-rw-r-- 1 rwillcox rwillcox 559M Feb 16 16:08 out_both/out_both.h5
```
Showing that the individual files are 7.1M each, but the combined file is 559M. I'm not sure where all this bloat comes from, but it should be removed. 

**Expected behavior**
The combined file size should be the sum of the inputs (give or take some small amount for overhead). 

**Versioning (please complete the following information):**
 - COMPAS v02.35.00

**Comment by jeffriley** [comment]
@reinhold-willcox Read the section on chunking in the documentation:

https://compas.readthedocs.io/en/latest/pages/User%20guide/Post-processing/post-processing-hdf5-info.html

or in the comments at the start of h5copy.

It may be that you're a victim of the choice of chunk size here - try playing with the the chunk size, and if that doesn't help send me the two files you're combining and I'll take a look.

**Comment by reinhold-willcox** [comment]
Closing because we have existing options to address this issue, I just wasn't well-informed on how they worked.

**Comment by jeffriley** [comment]
@reinhold-willcox I know this is old, but have a look at h5repack

To install it on Ubuntu use

    apt-get install hdf5-tools
