### ISSUE TITLE
Make HeSD a subset of Type Ia

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#945]
Following Ilya's suggestion in PR #822, the HeSD SN type should be a sub-class of Type Ia, identically to how USSNe are a subset of CCSNe. 

This is non-urgent, but could be a good first problem for the interested new developer.

**Comment by ilyamandel** [comment]
@reinhold-willcox -- I agree with making this a separate issue.  In the meantime, congratulations to you and @solfreludio on completing #822 !

**Comment by ilyamandel** [comment]
Fixed in #994 .
