### ISSUE TITLE
changelog out of order & what's new page out of sync with changelog

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#947]
After this commit

https://github.com/TeamCOMPAS/COMPAS/commit/84910190d5b9dcafa36cd8f7e6e5bacf8374f183

from this PR

https://github.com/TeamCOMPAS/COMPAS/pull/822

the last few entries of the changelog are out of order and mislabelled wrt version numbers.

Also, the What's New page is out of sync with the changelog - version numbers don't match change descriptions, and don't match changelog.

`urgency_moderate` - This is a moderately urgent issue - only because we should get the version numbers right and in sync before the next merge - too hard to fix the longer we wait.

`severity_moderate` - This is a moderately severe bug - same reason as above

**Versioning (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - COMPAS e.g. v02.36.00 - v02.37.10

**Additional context**

I think this may have been a bad fix to a merge conflict

**Comment by ilyamandel** [comment]
Addressed by @jeffriley  in #949 , closing.
