### ISSUE TITLE
Change defaults proposal

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#957]
I propose changing the following defaults and would appreciate feedback on this (no need to make a PR yet -- I will make one if there are no objections or once we reach a consensus):

Code defaults:

--allow-non-stripped-ECSN: FALSE (was true -- see Willcox+, 2021)
--evolve-unbound-systems: TRUE (was false -- this takes very little extra time and is often useful)
--wolf-rayet-multiplier: 0.1 (was 1.0 -- see, e.g., Stevenson & Clarke, 2022, showing that this is closest to more modern prescriptions; also Neijssel+, 2021, etc.)
--muller-mandel-kick-multiplier-NS: 520.00 (was 400 -- calibrated by Kapil+, 2023)
--remnant-mass-prescription: MULLERMANDEL (was FRYER2012 -- this is now well tested, see above)
--kick-magnitude-distribution: MULLERMANDEL (was MAXWELLIAN -- this is now well tested, see above)
--retain-core-mass-during-caseA-mass-transfer: TRUE (was false -- see Romero-Shaw+, 2023)

In FastCosmicIntegrator, change default binary fraction from fbin=0.7 to fbin=1.0 (as discussed in several of our papers, the broad mass separations we consider effectively incorporate single stars, which are generally rare for massive binaries, anyway).

**Comment by jeffriley** [comment]
What about changing --luminous-blue-variable-prescription from HURLEY-ADD to BELCZYNSKI?

**Comment by ilyamandel** [comment]
On winds: work is progressing (thanks to @jmerritt1 , @SimonStevenson ), et al.  And yes, more updates will be needed, including to LBV winds — but no harm in making at least small fixes in the meantime.  Simon and Teagan showed in their paper that fWR=0.1 in our old prescription is a reasonably good fit to the newer WR wind models, and we have a lot of other work (from Coen, from Isobel, etc.) showing that WR winds must be much lower than our current default.

On exploring the impacts of kick prescriptions: I think these are already explored in e.g., https://ui.adsabs.harvard.edu/abs/2021MNRAS.500.1380M,  https://ui.adsabs.harvard.edu/abs/2023MNRAS.519.5893K -- but, of course, more exploration is always welcome!

Pushing a PR with the changes above in #961 , so closing this.
