### ISSUE TITLE
`h5copy.py FILE -o OUT_FILE` appends to OUT_FILE (does not overwrite/log that it is appending)

### ISSUE THREAD

**Issue by avivajpeyi** [TeamCOMPAS/COMPAS#964]
I ran `h5copy` on the COMPAS zenodo `Z_all` dataproduct (~6GB) and excluded the groups 'Run_Details BSE_Supernovae'

```
python h5copy.py ~/data/Z_all/COMPAS_Output.h5 -x Run_Details BSE_Supernovae -o ~/data/Z_all/DCO_data.h5
```

The new file is `15.5866` GB`. Additionally, `Run_Details` is still present... Any ideas what's going on?

```bash
❯ compas_h5view ~/data/Z_all/COMPAS_Output.h5 


Summary of HDF5 file ~/data/Z_all/COMPAS_Output.h5
================================================================================================================

File size    : 6.5059 GB
Last modified: 2022-03-11 03:19:25

COMPAS Filename              Columns   Entries   Unique SEEDs
--------------------------   -------   -------   ------------
Run_Details                      370        25
BSE_Common_Envelopes              73   2272520        2168068
BSE_Double_Compact_Objects        12     80123          80123
BSE_Supernovae                    32   3250698        2293674
BSE_System_Parameters            147   5000000        5000000


compas_ml_surrogate/tests/test_data on  main [!] via 🐍 v3.8.10 (ligo_venv) 
❯ compas_h5copy ~/data/Z_all/COMPAS_Output.h5 -x BSE_Supernovae Run_Details -o ~/data/Z_all/DCO_data.h5
Copying file /home/avaj040/data/Z_all/COMPAS_Output.h5



compas_ml_surrogate/tests/test_data on  main [!] via 🐍 v3.8.10 (ligo_venv) 
❯ compas_h5view ~/data/Z_all/DCO_data.h5


Summary of HDF5 file ~/data/Z_all/DCO_data.h5
===========================================================================================================

File size    : 15.5866 GB
Last modified: 2023-05-02 14:58:59.707492

COMPAS Filename              Columns   Entries    Unique SEEDs
--------------------------   -------   --------   ------------
Run_Details                      370         50
BSE_Common_Envelopes              73    4545040        2168068
BSE_Double_Compact_Objects        12     240369          80123
BSE_System_Parameters            147   15000000        5000000


```

**Comment by avivajpeyi** [comment]
Ah, its because i already had an outfile at the `-o path` 

Deleting the outfile and then running `h5copy` resulted in a smaller file (5.8GB)

```
compas_ml_surrogate/tests/test_data on  main [!] via 🐍 v3.8.10 (ligo_venv) took 9s 
❯ compas_h5view ~/data/Z_all/DCO_data.h5 


Summary of HDF5 file ~/data/Z_all/DCO_data.h5
===========================================================================================================

File size    : 5.8174 GB
Last modified: 2023-05-02 15:14:53.610362

COMPAS Filename              Columns   Entries   Unique SEEDs
--------------------------   -------   -------   ------------
Run_Details                      370        25
BSE_Common_Envelopes              73   2272520        2168068
BSE_Double_Compact_Objects        12     80123          80123
BSE_System_Parameters            147   5000000        5000000

```

**Comment by avivajpeyi** [comment]
Maybe a warning/log should be included in h5copy if the `-o OUTPUT` file already exists...

@jeffriley, any thoughts on the following?
- Should `h5copy` be appending data to the outfile if it already exists? (if so maybe a warning should be logged)
- Should `h5copy`  raise an error and quit if the outfile already exists? 
- Should `h5copy`  overwrite an existing outfile?

**Comment by jeffriley** [comment]
@avivajpeyi 
python3 h5copy.py -h and see -e commandline argument

    python3 h5copy.py -h
    usage: h5copy.py [-h] [-b BUFFER_SIZE] [-c CHUNK_SIZE] [-e] [-f FILENAME_FILTER]
                     [-o OUTPUT_FILENAME] [-r [RECURSION_DEPTH]] [-s]
                     [-x EXCLUDE_GROUP [EXCLUDE_GROUP ...]]
                     input [input ...]
    
    HDF5 file copier.
    
    positional arguments:
      input
        input directory and/or file name(s)
    
    optional arguments:
      -h, --help
        show this help message and exit
      -b BUFFER_SIZE, --buffer-size BUFFER_SIZE
        IO buffer size (number of HDF5 chunks, default = 10)
      -c CHUNK_SIZE, --chunk-size CHUNK_SIZE
        HDF5 output file dataset chunk size (default = 100000)
      -e, --erase-output
        erase existing output file before copying input files (default = False)
      -f FILENAME_FILTER, --filter FILENAME_FILTER
        input filename filter (default = *)
      -o OUTPUT_FILENAME, --output OUTPUT_FILENAME
        output file name (default = h5out.h5)
      -r [RECURSION_DEPTH], --recursive [RECURSION_DEPTH]
        recursion depth (default is no recursion)
      -s, --stop-on-error
        stop all copying if an error occurs (default is skip to next file and continue)
      -x EXCLUDE_GROUP [EXCLUDE_GROUP ...], --exclude EXCLUDE_GROUP [EXCLUDE_GROUP ...]
        list of input groups to be excluded (default is all groups will be copied)

**Comment by avivajpeyi** [comment]
Ah! I missed that -- in this case, it might be helpful to print a warning stating that the `copy` is appending to an existing file if the file already exists?

**Comment by jeffriley** [comment]
> in this case, it might be helpful to print a warning stating that the copy is appending to an existing file if the file already exists?

The ordinary use of h5copy is to concatenate many files from a single run split over many cores into a single file - that's why the passive path is to append.  I think a warning would get tedious.  Nothing is lost if the data is appended, so no harm done - so no real need for a warning.  If you append when you meant erase, you have lost nothing and you can just do it again with the "-e" option.  The extra-ordinary use of h5copy is to just copy a single file to a new file, hence the use of the option.

**Comment by jeffriley** [comment]
> The new file is 15.5866 GB

See issue #923 and the answer therein

**Comment by avivajpeyi** [comment]
Ah! I forgot that h5copy is meant for combining multiple out files!
