### ISSUE TITLE
Consider migrating to C++17 for compiling COMPAS (required by boost.math)

### ISSUE THREAD

**Issue by jeffriley** [TeamCOMPAS/COMPAS#984]
**Describe the bug**

After upgrading to boost 1.82, the following compiler warning appears:

warning: "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"

As the warning indicates, as of the boost 1.82 release, the minimum C++ version for Boost.Math is C++14.  Currently we compile COMPAS with C++11.  We use Boost.Math is a few places throughout the code.  If we can't rewrite the code that uses Boost.Math so that it doesn't (we probably could, but probably don't want to...), we need to either advise users not to upgrade to boost v1.82 (or beyond), or ensure we can compile COMPAS with at least C++14 - I think we should look at migrating to C++17.

**Label the issue**

`urgency_low`      - This issue is not urgent (yet)

`severity_minor`    - This is a minor issue with minimal impact (for now)

**To Reproduce**
1. Upgrade boos to v1.82
2. Compile COMPAS using C++11
3. See compile warning

**Expected behavior**

We can compile, link, and run COMPAS using the boost.math functionality even after upgrading to boost v1.82 (we'll have to move there eventually)

**Screenshots**
n/a

**Versioning (please complete the following information):**
 - OS: Ubuntu 22.04, MacOS Ventura 13.4.1
 - COMPAS latest

**Additional context**
n/a

**Comment by ilyamandel** [comment]
@jeffriley -- if/when you get around to this, another warning I get is 

Log.cpp:438:44: warning: 'copy_file' is deprecated: Use copy_options instead of copy_option [-Wdeprecated-declarations]
                        boost::filesystem::copy_file(OPTIONS->LogfileDefinitionsFilename(), dstFn, boost::filesystem::copy_option::overwrite_if_exists); // copy logfile-definitions file - overwrite any existing file (shouldn't be one, but just in case we want this one)
