### ISSUE TITLE
wind mass transfer via bondi accretion or wind RLOF

### ISSUE THREAD

**Issue by astro-sjgao** [TeamCOMPAS/COMPAS#991]
I simulated the evolution of several binaries, yet I observed no accretion onto the accretor through wind accretion.

My exploration led me to the COMPAS paper, and I found that:

"Currently we do not consider wind accretion (e.g., Bondi & Hoyle 1944), wind RLOF (Mohamed & Podsiadlowski 2007; Hirai & Mandel 2021), or wind interaction with the companion (Brookshaw & Tavani 1993; Schrøder et al. 2021)."

It appears that the incorporation of wind accretion into COMPAS might be necessary to simulate the wind-fed HMXBs, symbiotic stars and symbiotic X-ray binaries.

**Comment by ilyamandel** [comment]
Dear @xiaoe475 , 

You are absolutely right that wind accretion is critical for the observations of HMXBs.  On the other hand, the mass growth through wind accretion is probably not very important in these systems: if you imagine that the compact object is Eddington-limited in its accretion rate, it would take ~10^8 years to double its mass, while the lifetime of HMXBs with high-mass donors is likely under 10^6 years.  In other words, the compact object probably accretes \lesssim 1% of its mass, allowing us to ignore the mass accretion at lowest order from the perspective of binary evolution.  

Does this sound sensible?

**Comment by astro-sjgao** [comment]
> Dear @xiaoe475 ,
> 
> You are absolutely right that wind accretion is critical for the observations of HMXBs. On the other hand, the mass growth through wind accretion is probably not very important in these systems: if you imagine that the compact object is Eddington-limited in its accretion rate, it would take ~10^8 years to double its mass, while the lifetime of HMXBs with high-mass donors is likely under 10^6 years. In other words, the compact object probably accretes \lesssim 1% of its mass, allowing us to ignore the mass accretion at lowest order from the perspective of binary evolution.
> 
> Does this sound sensible?

Got it, thanks!
